### ISSUE TITLE
ESP32 Crash at first client connection  (ESP-IDF) with ESPAsyncWebServer

### ISSUE THREAD

**Issue by youssefIOT** [me-no-dev/ESPAsyncWebServer#1001]
Hi
Im face a problem with ESPAsyncWebsrevr. I use it as arduino idf component.
the program compile well but if i open a web page , my ESP crash  immediatly with the following error !!.
I read some posts talking about memory heap exception and i dont know if this is my case. 
Notes :
 1- I havn't any delay in my callbacks 
 2 - It worked fine in arduino IDE
 3- my web task is in a freertos task
 4- even if without freertos task [code in setup] the esp crash with the same  errors
5 - the web page is loaded one time but any refresh attemp or connection leeds to crash !!! -:((( 
Please Help !!!! 

here is  a simple callback causing the crash
server.on("/", HTTP_GET, [](AsyncWebServerRequest *request){

    if(!request->authenticate(http_username, http_password))
return request->requestAuthentication();
    request->send(SPIFFS, "/index.html", "text/html");
  });

here is the output errors
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400e3c1f  PS      : 0x00060a30  A0      : 0x800e3d39  A1      : 0x3ffd4250  
0x400e3c1f: AsyncWebServerRequest::_removeNotInterestingHeaders() at /home/ammar/esp/SSH_TO_IDF/build/../components/arduino/cores/esp32/WString.h:304
 (inlined by) ?? at /home/ammar/esp/SSH_TO_IDF/build/../components/arduino/cores/esp32/WString.h:322
 (inlined by) ?? at /home/ammar/esp/SSH_TO_IDF/build/../components/arduino/cores/esp32/WString.h:230
 (inlined by) AsyncWebServerRequest::_removeNotInterestingHeaders() at /home/ammar/esp/SSH_TO_IDF/build/../components/arduino/libraries/ESPAsyncWebServer/src/WebRequest.cpp:184

A2      : 0x3ffd57a8  A3      : 0x3ffb8c5c  A4      : 0x3ffb8c5c  A5      : 0x3ffb8c5c  
A6      : 0x3ffd57b8  A7      : 0x00000000  A8      : 0x800e3c90  A9      : 0x3ffd4230  
A10     : 0x3ffd4c20  A11     : 0x89403352  A12     : 0x3ffd4c20  A13     : 0x00000000  
A14     : 0x0000000d  A15     : 0x00000000  SAR     : 0x0000001c  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x89403361  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xfffffffe  

Backtrace:0x400e3c1c:0x3ffd4250 0x400e3d36:0x3ffd42a0 0x400e3e39:0x3ffd42e0 0x400e402d:0x3ffd4340 0x400e7091:0x3ffd4360 0x400e70e1:0x3ffd4390 0x400e7129:0x3ffd43b0 0x400e7246:0x3ffd43d0 0x400e730a:0x3ffd43f0 0x4008cf15:0x3ffd4420
0x400e3c1c: AsyncWebServerRequest::_removeNotInterestingHeaders() at /home/ammar/esp/SSH_TO_IDF/build/../components/arduino/libraries/ESPAsyncWebServer/src/StringArray.h:35
 (inlined by) ?? at /home/ammar/esp/SSH_TO_IDF/build/../components/arduino/libraries/ESPAsyncWebServer/src/StringArray.h:55
 (inlined by) AsyncWebServerRequest::_removeNotInterestingHeaders() at /home/ammar/esp/SSH_TO_IDF/build/../components/arduino/libraries/ESPAsyncWebServer/src/WebRequest.cpp:183

0x400e3d36: AsyncWebServerRequest::_parseLine() at /home/ammar/esp/SSH_TO_IDF/build/../components/arduino/libraries/ESPAsyncWebServer/src/WebRequest.cpp:571

0x400e3e39: AsyncWebServerRequest::_onData(void*, unsigned int) at /home/ammar/esp/SSH_TO_IDF/build/../components/arduino/libraries/ESPAsyncWebServer/src/WebRequest.cpp:123

0x400e402d: operator() at /home/ammar/esp/SSH_TO_IDF/build/../components/arduino/libraries/ESPAsyncWebServer/src/WebRequest.cpp:76
 (inlined by) _M_invoke at /home/ammar/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/8.4.0/bits/std_function.h:297

0x400e7091: std::function<void (void*, AsyncClient*, void*, unsigned int)>::operator()(void*, AsyncClient*, void*, unsigned int) const at /home/ammar/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/8.4.0/bits/std_function.h:687

0x400e70e1: AsyncClient::_recv(tcp_pcb*, pbuf*, signed char) at /home/ammar/esp/SSH_TO_IDF/build/../components/arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:934

0x400e7129: AsyncClient::_s_recv(void*, tcp_pcb*, pbuf*, signed char) at /home/ammar/esp/SSH_TO_IDF/build/../components/arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:1210

0x400e7246: _handle_async_event(lwip_event_packet_t*) at /home/ammar/esp/SSH_TO_IDF/build/../components/arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:162

0x400e730a: _async_service_task(void*) at /home/ammar/esp/SSH_TO_IDF/build/../components/arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:197

0x4008cf15: vPortTaskWrapper at /home/ammar/esp/esp-idf/components/freertos/port/xtensa/port.c:168

ELF file SHA256: f279d86be045193a

Rebooting...

**Comment by ZanzyTHEbar** [comment]
how did you fix this? Same issue.
