### ISSUE TITLE
Template/placeholder issue

### ISSUE THREAD

**Issue by Brekel42** [me-no-dev/ESPAsyncWebServer#1008]
There appears to be an issue when the progmem data contains % signs.

eg my data contains html  with the text "border-radius: 50%".  Later on in the html, I have the placeholder "%PLACEHOLDER%".

Looking at the data sent  back, when processed it is taking everything between the % in "50%" and the first % in "%PLACEHOLDER%" as being the placeholder, so all the intervening html code is replaced with "".

**Comment by Brekel42** [comment]
Just found issue 300, same problem.,  plus resolution

**Comment by chupocro** [comment]
> 
> 
> Just found issue 300, same problem., plus resolution

I wouldn't say changing the library is the solution. What will happen after the library update?

**Comment by Brekel42** [comment]
I agree, more of a work around than a solution. But I figured that since the issue was already raised on issue #300,  it didn't need to be on a separate issue as well.
