### ISSUE TITLE
WebSocket handshake: Unexpected response code: 500

### ISSUE THREAD

**Issue by xoseperez** [me-no-dev/ESPAsyncWebServer#101]
Example code fails with a

`WebSocket connection to 'ws://192.168.1.114/ws' failed: Error during WebSocket handshake: Unexpected response code: 500`

in the browser. Latest working commit is 3e6e890808, so I guess the problem started with a7c4dfb04fd6a06001d9f87ba9935cc67cb256d5.

**Comment by me-no-dev** [comment]
please try the latest commit :)

**Comment by xoseperez** [comment]
Yes it works!
(PlatformIO had not updated the library until one hour ago, I was not in the latest commit, sorry)
