### ISSUE TITLE
How to tell if AsyncWebSocket has a client connected

### ISSUE THREAD

**Issue by unkajah** [me-no-dev/ESPAsyncWebServer#1033]
Hello, I cannot figure out how to only send messages if there is an active client connected to my AsyncWebSocket

I don't want to be sending or attempting if there are no active connections. is there a best practice for this?

Thank you!

**Comment by Pablo2048** [comment]
Just take a look into the source code...
https://github.com/me-no-dev/ESPAsyncWebServer/blob/1d46269cedf477661ca8a29518414f4b74e957d4/src/AsyncWebSocket.cpp#L893
You get the number of connected clients.
