### ISSUE TITLE
Send to the HTML an array of data

### ISSUE THREAD

**Issue by AlvaroMacipe** [me-no-dev/ESPAsyncWebServer#1046]
Hi!

I want to send with server.on(...) some Strings. 
Like String array[3] = {"A", "B", "C"}

I can send data for one object, but not more. I dont know if I can do a loop or I only can do this by JSON .

Thanks

**Comment by dduehren** [comment]
JSON worked for me.  I use JSON to update multiple variables per page using xhhyp.  Here's my html script, for example:
`  function parseResponse(p1){
  jsonResponse = p1;
        document.getElementById("temperature").innerHTML = jsonResponse.TMP;
        document.getElementById("humidity").innerHTML = jsonResponse.HUM;
        document.getElementById("CO2Lvl").innerHTML = jsonResponse.CO2;
        document.getElementById("light").innerHTML = jsonResponse.LED;
        document.getElementById("time").innerHTML = jsonResponse.TIM;
		document.getElementById("dCount").innerHTML = jsonResponse.CNT;
		document.getElementById("error").innerHTML = jsonResponse.ERR;
		document.getElementById("wifi").innerHTML = jsonResponse.WIFI;
  }
  setInterval(function ( ) {
    var xhttp = new XMLHttpRequest();
    xhttp.onreadystatechange = function() {
        if (this.readyState == 4 && this.status == 200){
        var jsonResponse = JSON.parse(this.responseText);
        console.log(jsonResponse);
		parseResponse(jsonResponse);
        }
    };
    xhttp.open("GET", "/Main", true);
    xhttp.send();
  }, 2000 ) ;`

**Comment by zekageri** [comment]
Show us your approach and I could help you with code
