### ISSUE TITLE
Change port in routine?

### ISSUE THREAD

**Issue by andrecortica** [me-no-dev/ESPAsyncWebServer#1058]
Its possible change port in my setup routine?

**Comment by andrecortica** [comment]
please does anyone have any ideas?

**Comment by Connect-and-Exchange** [comment]
`  server = new AsyncWebServer(port);`

**Comment by andrecortica** [comment]
> ` server = new AsyncWebServer(port);`

Hi Connect-and-Exchange
Thanks for the help, but the following error appears:

exit status 1
invalid user-defined conversion from 'AsyncWebServer*' to 'const AsyncWebServer&' [-fpermissive]

**Comment by andrecortica** [comment]
> ` server = new AsyncWebServer(port);`

Hi @Connect-and-Exchange 
Thanks for the help, but the following error appears:

exit status 1
invalid user-defined conversion from 'AsyncWebServer*' to 'const AsyncWebServer&' [-fpermissive]

**Comment by vernonet** [comment]
AsyncWebServer * server;
......
// Start the server
server = new AsyncWebServer(8888);
server->begin();

**Comment by zekageri** [comment]
This going to wreck your heap if you allocate two server space

**Comment by vernonet** [comment]
AsyncWebServer * server;
......
server = new AsyncWebServer(7777);
server->begin();
.......
.......
delete server;
// Start the server
server = new AsyncWebServer(8888);
server->begin();

**Comment by andrecortica** [comment]
Please, what would the following code look like


#include <Arduino.h>
#include <WiFi.h>
#include <AsyncTCP.h>
#include <ESPAsyncWebServer.h>

const char* ssid = "";
const char* password = "";

AsyncWebServer server(80);

void setup(void) {
  Serial.begin(115200);
  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);
  Serial.println("");

  // Wait for connection
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.print("Connected to ");
  Serial.println(ssid);
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());

  server.on("/", HTTP_GET, [](AsyncWebServerRequest *request) {
    request->send(200, "text/plain", "Hi! I am Andre.");
  });

  server.begin();
  Serial.println("HTTP server started");

}

void loop(void) {
  
}

**Comment by zekageri** [comment]
Looks normal

**Comment by vernonet** [comment]
to **andrecortica**

> ```
> #include <Arduino.h>
> #include <WiFi.h>
> #include <AsyncTCP.h>
> #include <ESPAsyncWebServer.h>
> 
> const char* ssid = "";
> const char* password = "";
> 
> AsyncWebServer *server;
> 
> void setup(void) {
> Serial.begin(115200);
> WiFi.mode(WIFI_STA);
> WiFi.begin(ssid, password);
> Serial.println("");
> 
> // Wait for connection
> while (WiFi.status() != WL_CONNECTED) {
> delay(500);
> Serial.print(".");
> }
> Serial.println("");
> Serial.print("Connected to ");
> Serial.println(ssid);
> Serial.print("IP address: ");
> Serial.println(WiFi.localIP());
> 
> server->on("/", HTTP_GET, [](AsyncWebServerRequest *request) {
> request->send(200, "text/plain", "Hi! I am Andre.");
> });
> 
> server = new AsyncWebServer(80);
> server->begin();
> Serial.println("HTTP server started");
> 
> }
> 
> void loop(void) {
> 
> }
> ```

**Comment by Pablo2048** [comment]
@vernonet very bad - you can not do `server->on()` before `server = new AsyncWebServer(80);` actually...

**Comment by vernonet** [comment]
yes, I made a mistake :
```
.....
server = new AsyncWebServer(80);
server->on("/", HTTP_GET, [](AsyncWebServerRequest *request) {
request->send(200, "text/plain", "Hi! I am Andre.");
});

server->begin();
Serial.println("HTTP server started");
}

void loop(void) {

}
```

**Comment by andrecortica** [comment]
> yes, I made a mistake :
> ```
> .....
> server = new AsyncWebServer(80);
> server->on("/", HTTP_GET, [](AsyncWebServerRequest *request) {
> request->send(200, "text/plain", "Hi! I am Andre.");
> });
> 
> server->begin();
> Serial.println("HTTP server started");
> }
> 
> void loop(void) {
> 
> }
> ```

Hi @vernonet , Thanks a lot for the help. Worked perfectly! 😀😀
