### ISSUE TITLE
(failed)net::ERR_CONTENT_DECODING_FAILED for css and js files

### ISSUE THREAD

**Issue by GeorgeFlorian** [me-no-dev/ESPAsyncWebServer#1060]
I am trying to improve the speed of an [ESPAsyncWebServer][1] that's on an ESP32 and in that regard I'm trying to serve the files as `gz` files.

The problem is that the `css` and `js` files return the error: `(failed)net::ERR_CONTENT_DECODING_FAILED`

I've set a default header for all of the server responses:
```cpp
  DefaultHeaders::Instance().addHeader("Content-Encoding", "gzip");
```
I've written some GET handlers for the two pages that I have:
```cpp
  server.on("/dashboard", HTTP_GET, [](AsyncWebServerRequest *request)
            {
              AsyncWebServerResponse *response = request->beginResponse(SPIFFS, "/www/index.html.gz", "text/html");
              // response->addHeader("Content-Encoding", "gzip");
              request->send(response);
            });
  server.on("/settings", HTTP_GET, [](AsyncWebServerRequest *request)
            { request->send(SPIFFS, "/www/settings.html.gz", "text/html"); });

```

And the rest I serve as static files:
```cpp
  server.serveStatic("/", SPIFFS, "/");
  server.serveStatic("/", SPIFFS, "/ap").setFilter(ON_AP_FILTER);
  server.serveStatic("/", SPIFFS, "/www").setFilter(ON_STA_FILTER);
  server.onNotFound([](AsyncWebServerRequest *request)
                    { request->redirect("/dashboard"); });
```

Inside the html pages I have:
```html
    <link rel="stylesheet" href="../style.css" />
    <script src="../ap/bootstrap.js"></script>
    <script src="../script.js"></script>
```

First of all, if I succeed in serving compressed files, will the speed actually improve ?  
Because the ESP will also run in AP mode (no internet access), I need the Bootstrap `css` and `js` files to be local. If I don't find a method to compress them, they take around 1-2 seconds each to load from the ESP's memory.
 
Secondly, should I reference the `css` and `js` files normally or with `.gz` extension ?

Thirdly, should I keep both the normal file and the one with `.gz` extension ?

Also, should I just write handlers for each file that I wish to be compressed and add the `"Content-Encoding", "gzip"` to each `html`, `css` and/or `js` file I serve ?
```
  server.on("/dashboard", HTTP_GET, [](AsyncWebServerRequest *request)
            {
              AsyncWebServerResponse *response = request->beginResponse(SPIFFS, "/www/index.html.gz", "text/html");
              response->addHeader("Content-Encoding", "gzip");
              request->send(response);
            });
```

Lastly, how can I serve the `css` and `js` files without and actual path ? Let's say we have the following handler:
```
  server.on("/script.js", HTTP_GET, [](AsyncWebServerRequest *request)
            {
              AsyncWebServerResponse *response = request->beginResponse(SPIFFS, "/script.js.gz", "text/javascript");
              response->addHeader("Content-Encoding", "gzip");
              request->send(response);
            });
```
If the user goes to `/script.js` he will have access to the file and this seems like a security issue.

  [1]: https://github.com/me-no-dev/ESPAsyncWebServer

**Comment by yusp75** [comment]
Just use 7zip to compress css and js file, format would be  'gzip', and your code is right.
