### ISSUE TITLE
serveStatic():  add charset attribute to content-type header

### ISSUE THREAD

**Issue by marcboon** [me-no-dev/ESPAsyncWebServer#1083]
The content-type for files served with serveStatic is based on the filename extension. However, sometimes you want to include a charset attribute, e.g. Content-Type: application/json; charset=utf-8.

For my own use I modified the function AsyncFileResponse::_setContentType() in WebResponses.cpp to add this attribute for all text files, but it might be better to make it optional, for example to add an extra parameter to serveStatic(). (Or maybe there is already a proper way to do it, that I'm not aware of).
```
void AsyncFileResponse::_setContentType(const String& path){
  if (path.endsWith(".html")) _contentType = "text/html; charset=utf-8";
  else if (path.endsWith(".htm")) _contentType = "text/html; charset=utf-8";
  else if (path.endsWith(".css")) _contentType = "text/css; charset=utf-8";
  else if (path.endsWith(".json")) _contentType = "application/json; charset=utf-8";
  else if (path.endsWith(".js")) _contentType = "application/javascript; charset=utf-8";
  else if (path.endsWith(".png")) _contentType = "image/png";
  else if (path.endsWith(".gif")) _contentType = "image/gif";
  else if (path.endsWith(".jpg")) _contentType = "image/jpeg";
  else if (path.endsWith(".ico")) _contentType = "image/x-icon";
  else if (path.endsWith(".svg")) _contentType = "image/svg+xml";
  else if (path.endsWith(".eot")) _contentType = "font/eot";
  else if (path.endsWith(".woff")) _contentType = "font/woff";
  else if (path.endsWith(".woff2")) _contentType = "font/woff2";
  else if (path.endsWith(".ttf")) _contentType = "font/ttf";
  else if (path.endsWith(".xml")) _contentType = "text/xml; charset=utf-8";
  else if (path.endsWith(".pdf")) _contentType = "application/pdf";
  else if (path.endsWith(".zip")) _contentType = "application/zip";
  else if(path.endsWith(".gz")) _contentType = "application/x-gzip";
  else _contentType = "text/plain; charset=utf-8";
}
```

**Comment by akash6190** [comment]
@marcboon for me it works by just removing `.gz` in URL. This [code](https://github.com/me-no-dev/ESPAsyncWebServer/blob/2f784268f0a358741ee6384480d48656e159d726/src/WebHandlers.cpp#L144) checks if gzip file already exits and serves that, and this [code](https://github.com/me-no-dev/ESPAsyncWebServer/blob/2f784268f0a358741ee6384480d48656e159d726/src/WebResponses.cpp#L523) reads the request path and sets current content-type.
