### ISSUE TITLE
MacOS and iOS Safari Webkit "NSURLSession Websocket" crashes ESP

### ISSUE THREAD

**Issue by teknoel** [me-no-dev/ESPAsyncWebServer#1097]
After some instinctive snooping, I have found a major incompatibility with Apple Safari on MacOS and iOS. I'm not sure what exactly is going on, but definitely put my finger on the issue being **_NSURLSession Websocket_** enabled in Safari "Experimental Feature" settings. This will crash the ESP when closing and reopening the websocket with the same client. I have confirmed that disabling Apple Safari **_NSURLSession Websocket_** stops the ESP from crashing. 

Apple started enabling NSURLSession Websocket by default in iOS15 and MacOS 11+ (Big Sur or Monterey ?) Hence, the problem started showing up on Mac and iPhones etc.

Older system software has the experimental feature disabled by default: iOS 14.2 and Mac OS 10.14.x (Mojave)

I'm not a internet transport protocol geek, so I can't help other than tell you this general incompatibility issue. I was googling about what NSURL is doing and some developers were suggesting that: a) apple is transmitting a bad websocket data closure frame, or. b) it is a new standard for websocket protocol?¿

This bug is a real show stopper as it kills my ESP product dev.

Sincerely,

Noel Rubin http:://teknoelogy.com

**Comment by arjenhiemstra** [comment]
+1
Here is a thread on the issue:
https://developer.apple.com/forums/thread/685403

I've combined some changes from forks that solved most of the issues for me (but I'm not really sure what it fixed):
https://github.com/arjenhiemstra/ESPAsyncWebServer

But still, in high traffic situations the ESP sometimes crashes
