### ISSUE TITLE
How to buffer WebSocket messages when using different tasks?

### ISSUE THREAD

**Issue by MaximilianMM** [me-no-dev/ESPAsyncWebServer#1104]
Hello,
I use a different task to handle the data of WebSocket messages. 
If a WebSocket message arrives I pass the data to global variable and set a flag (newMessage) to true. 
In a separate task I then handle the data. This approach works for me most of the times, but if the Client send messages in quick succession, only the first message gets handled. 
Because of the different tasks, a new Websocket message may arrive before the old one is handled in the communicationTask, therefore the new message gets lost.
I know this behavior is expected, but I would like to know which options I have to prevent the loss of data? Do I have to implement my own ring buffer, or are there other ways to achieve this?

```
void onEvent(AsyncWebSocket       *server,
             AsyncWebSocketClient *client,
             AwsEventType          type,
             void                 *arg,
             uint8_t              *data,
             size_t                len) {

    switch (type) {
        case WS_EVT_CONNECT:
            Serial.printf("WebSocket client #%u connected from %s\n", client->id(), client->remoteIP().toString().c_str());
            break;
        case WS_EVT_DISCONNECT:
            Serial.printf("WebSocket client #%u disconnected\n", client->id());
            break;
        case WS_EVT_DATA:  
            if(messageHandled){        
              xSemaphoreTake(changeSharedData, portMAX_DELAY); 
                  messageHandled = false;
                  messageData = (uint8_t*)malloc(sizeof(uint8_t)*len);   
                  memcpy(messageData, data, len+1);              
                  newMessage = true;
              xSemaphoreGive(changeSharedData);    
            }             
            break;
        case WS_EVT_PONG:
        case WS_EVT_ERROR:
            break;
    }
}
```
```
void communicationTask(void * parameter){
    while(1){    
        if(newMessage){             
            xSemaphoreTake(changeSharedData, portMAX_DELAY);    
            newMessage = false;
            messageHandled = false;
            xSemaphoreGive(changeSharedData);  

            const uint8_t size = JSON_OBJECT_SIZE(8);//5?
            StaticJsonDocument<size> json;
            DeserializationError err = deserializeJson(json, messageData);
            /*
            More Code here
            */
            xSemaphoreTake(changeSharedData, portMAX_DELAY); 
            messageHandled = true;
            xSemaphoreGive(changeSharedData); 
        }
    }
}
```

**Comment by zekageri** [comment]
What i did was created 10 client structs at the start of the program for each client.
If i got a client connection i fill one struct with the client id and message data.
if i got a message from a specific client id, i search for this id in my structs and put this client's message into its own struct.
if the client disconnects i indicate in it's struct that this is a free space and other clients can occupy it.

After that i created a loop task for processing client messages. One by one.

Client connect --> put it's id in a free struct.

Client message --> search for client id in array of structs --> put it's message in the struct ( inside preallocated char array )

loop task --> looping throught every struct in the struct array and check if there is an unprocessed message

Client disconnect --> search for client id in array of structs --> indicate disconnected client by ID with a flag
