### ISSUE TITLE
AsyncWebServer & FreeRTOs

### ISSUE THREAD

**Issue by PabloASua** [me-no-dev/ESPAsyncWebServer#1110]
Hi there!
I have been trying to run an AsyncWebServer into a FreeRTO Task when the begin() method is executed I got this message: [E][AsyncTCP.cpp:1290] begin(): failed to start task.
Changing the Task Stack size seems doesn't have any effect.

Any Idea?

Regards

**Comment by zekageri** [comment]
This webserver already uses it's own task.
