### ISSUE TITLE
Download SD card contents

### ISSUE THREAD

**Issue by mugginsjm** [me-no-dev/ESPAsyncWebServer#1114]
I have spent many hours on this site and others, but my skillset is limited.
I am trying to download a file from the SD card attached to ESP8266 and had success with this code, until the file size exceeded 1K
It seems that "chunking" is the way forward but I've tried every permutation with no success. Please help.

server.on("/download", HTTP_POST, [](AsyncWebServerRequest *request){
  Serial.println("*** download ***");    
    SD.begin(D8); 
    File file = SD.open("/leccy.csv");   
    if(!SD.begin(D8)) {
        Serial.println("Card Mount Failed");
        request->send (200, "text/html", "Card Mount Failed");
    } 
    else if(!file){
        Serial.println("Failed to open file for reading");
        request->send (200, "text/html", "Failed to open file for reading");
    }
    else{
    request->send(file, "/leccy.csv", "text/xhr", true);  // this works for small files
        Serial.println(request->client()->remoteIP());
file.close();
    } 
    request->send(204);
});

**Comment by simkard69** [comment]
Hello,

What if we want to serve files of 500kB or more ?
Is there a way to deal with that as I've tried to use something like that and it failed with a "CORRUPT HEAP: Bad head at ..."
`//server.on("/", HTTP_GET, [](AsyncWebServerRequest *request){                            request->send(SD, "/webui/index.htm", "text/html"); });`

Thanks
