### ISSUE TITLE
Support for FATFS filesystem 

### ISSUE THREAD

**Issue by Vishnu-Karthikeyan** [me-no-dev/ESPAsyncWebServer#1122]
Is there any way that we can use ESPAsyncWebServer with FATFS filesystem.
Trying to call images or files from flash(FATFS) using "server.on  request->send" does not work as there is no support for it.

**Comment by zekageri** [comment]
I don't know about that but LITTLEFS is faster. ^^

**Comment by Vishnu-Karthikeyan** [comment]
What if the Flash size is 16MB. We do not have an option for SPIFFS/ LITTLEFS.
.
.
.
.
.
![flashsize](https://user-images.githubusercontent.com/57656288/155083745-706d01ef-e5e6-4715-b358-7932ddd3b75c.png)

**Comment by zekageri** [comment]
In theory you can use any file system with async webserver, it is a little weird that you can not use it. 

You can build your own partition.csv and you can configure any size for the file system you want. 

I don't know how to import this to Arduino but on platform IO it is fairly easy

**Comment by Vishnu-Karthikeyan** [comment]
This method works for me 
       File file = FFat.open("/abc.txt");
       request->send(file, "/abc.txt", "text/plain", true);  //downloading
       request->send(file, "/abc.txt", "text/plain");          // to load
       file.close();

Thank you :)
