### ISSUE TITLE
Use % not as Placeholder or Template

### ISSUE THREAD

**Issue by MxFrs** [me-no-dev/ESPAsyncWebServer#1127]
Hi,
I wnat to send some CSS Styles with my response, which contain things like `width: 90%`. This breaks the whole webpage, because the parts between the `%` are eliminated. Is it possible to use `%` but not replace the parts between?

Greetings
Max

**Comment by vatsake** [comment]
Use %%

**Comment by minolta** [comment]
> Use %%

Working !! thank you

**Comment by kjyv** [comment]
Could this be added to the documentation? It is indeed quite helpful
