### ISSUE TITLE
ResponseStream send only cca 5.5kB ?

### ISSUE THREAD

**Issue by pantata** [me-no-dev/ESPAsyncWebServer#113]
Please any advice? Thanks, LS.

Sample code:

void printSampligsTest(AsyncResponseStream *response) {
	response->printf("[\n");
	for (int m=1; m < 32;m++) {
		for (int y=0; y< 10;y++) {
			 response->printf("[%d, %d, null, null, null, null, null, null, null, null],\n", m,y);
		}
	}
	response->printf("]");
}

server.on("/test.cgi",HTTP_GET,[](AsyncWebServerRequest *request) {
		uint32_t startTime=millis();
		AsyncResponseStream *response = request->beginResponseStream("application/json");
		response->print("{\n\"dtmo\":\"");
		printSampligsTest(response);
		response->printf("\",\n \"time\":%d}",millis()-startTime);
		request->send(response);
  });

**Comment by me-no-dev** [comment]
you can at most fit two packets worth of data in a response stream. That is roughly 3KB worth of data :) If you need larger data, you can look into StreamString and just respond with that, like it's Serial.
