### ISSUE TITLE
Re-run processor

### ISSUE THREAD

**Issue by lancelevine** [me-no-dev/ESPAsyncWebServer#1130]
Hi, sorry for the basic question but I am updating data on the backend and would like to refresh the frontend. If I manually refresh the webpage the values are updated, but is there code to cause the webpage to refresh? Specifically I would like my template processor to run to update the values in HTML. For example, inside an HTML GET request I have this: 

```
sliderValue8 = 10;
request->send(200, "text/plain", "OK");
```

Inside my processor I have:

```
else if (var == "SLIDERVALUE8") {
    return sliderValue8;
```

and in my HTML I have 
`<span id="textSliderValue8">Intensity 2: %SLIDERVALUE8%</span>`

If the processor runs, the slider is updated, but I am having difficulty telling the processor to run.

I have tried changing the response to:
request->send_P(200, "text/html", index_html, processor);

But this does not work, I guess because the page is already loaded? I know this is probably very basic but I am new to web servers and would appreciate any guidance. Thanks.

**Comment by zekageri** [comment]
What you want can be achieved in a different way. You can use websockets for data transfer or http requests. In the case of HTTP requests, the client ( web js ) has to initiate the request towards the backend. There are multiple ways for this. GET,POST,ANY, etc... 

But I recommend websockets for this. Websocket is basically an upgraded http request but none of the participants close the connection. That way you have a bidirectional communication.

Both the server and the client can send data to each other. 

On the server you start a listen on a port. When the client's webpage loads, it can connect to the server port which has Websocket.

If the connection is success you can send data to the server without asking it, and the server can send data without asking.
And you don't have to reload the page, data can be updated in real time without interaction.
