### ISSUE TITLE
esp32 simple server example fail

### ISSUE THREAD

**Issue by lwshowl** [me-no-dev/ESPAsyncWebServer#1136]
after compiling with platformio ,esp32 launched with error message Wifi Failed
things i have changed :
SSID = "esp32-cam"
password "123456789"

**Comment by zekageri** [comment]
Copy the whole error code please, and full sketch.

**Comment by lwshowl** [comment]
@zekageri  i dont know where to check the error code, 
the whole sketch is copy pasted from the example except that i changed the ssid and password

this is the whole code:

//
// A simple server implementation showing how to:
//  * serve static messages
//  * read GET and POST parameters
//  * handle missing pages / 404s
//

#include <Arduino.h>
#ifdef ESP32
#include <WiFi.h>
#include <AsyncTCP.h>
#elif defined(ESP8266)
#include <ESP8266WiFi.h>
#include <ESPAsyncTCP.h>
#endif
#include <ESPAsyncWebServer.h>

AsyncWebServer server(80);

const char* ssid = "esp32";
const char* password = "123456789";

const char* PARAM_MESSAGE = "message";

void notFound(AsyncWebServerRequest *request) {
    request->send(404, "text/plain", "Not found");
}

void setup() {

    Serial.begin(115200);
    WiFi.mode(WIFI_STA);
    WiFi.begin(ssid, password);
    if (WiFi.waitForConnectResult() != WL_CONNECTED) {
        Serial.printf("WiFi Failed!\n");
        return;
    }

    Serial.print("IP Address: ");
    Serial.println(WiFi.localIP());

    server.on("/", HTTP_GET, [](AsyncWebServerRequest *request){
        request->send(200, "text/plain", "Hello, world");
    });

    // Send a GET request to <IP>/get?message=<message>
    server.on("/get", HTTP_GET, [] (AsyncWebServerRequest *request) {
        String message;
        if (request->hasParam(PARAM_MESSAGE)) {
            message = request->getParam(PARAM_MESSAGE)->value();
        } else {
            message = "No message sent";
        }
        request->send(200, "text/plain", "Hello, GET: " + message);
    });

    // Send a POST request to <IP>/post with a form field message set to <message>
    server.on("/post", HTTP_POST, [](AsyncWebServerRequest *request){
        String message;
        if (request->hasParam(PARAM_MESSAGE, true)) {
            message = request->getParam(PARAM_MESSAGE, true)->value();
        } else {
            message = "No message sent";
        }
        request->send(200, "text/plain", "Hello, POST: " + message);
    });

    server.onNotFound(notFound);

    server.begin();
}

void loop() {
}

**Comment by zekageri** [comment]
No way that this was in an example.
Anyway, here is your problem.

```C
WiFi.begin(ssid, password);
if (WiFi.waitForConnectResult() != WL_CONNECTED) {
    Serial.printf("WiFi Failed!\n");
    return;
}
```

You did not wait for the connection. You initiate the connection and immidiatly timeouting. You must wait for it to connect.

**Something like this:**


```C
WiFi.begin(ssid, password);
Serial.print("Connecting...");
if (WiFi.waitForConnectResult() != WL_CONNECTED) {
    Serial.print(".");
    delay(100);
}
Serial.printf("\nConnected to: %s\n",ssid);
```

**Comment by zekageri** [comment]
Oh sorry. I did not noticed the wiFi.waitForConnecTresult() function call.
You specified a wrong SSID for the network you are try to connect to!

This is not AP mode. Your esp try to connect to an existing network. 
If you want to make an AP mode you should use this function:

`WiFi.softAP(ssid, password);`

instead of  `WiFi.begin(ssid, password);`

**Comment by zekageri** [comment]
Here is a link for an AP mode code example: [AP MODE EXAMPLE](https://randomnerdtutorials.com/esp32-access-point-ap-web-server/)

**Comment by lwshowl** [comment]
@zekageri  -@_@  thanks for your patient reply
