### ISSUE TITLE
[Question] Is it possible to bind server on both Station and AP interfaces?

### ISSUE THREAD

**Issue by gfoiani** [me-no-dev/ESPAsyncWebServer#114]
Hi,

I'm developing an application on ESP8266 that needs to be reachable from both Station and AP interfaces.
The device is running in AP_STA mode, at the moment the server correctly responds to devices connected to Station interface, but it does not respond when the requests are sent from devices connected to AP interface.
Is ti possible to bind the server to both Station and Access Point interfaces?
The desired behavior is like binding the server to 0.0.0.0 in order to accept connections and requests from any IP address.

Thanks

**Comment by me-no-dev** [comment]
The server is running fine on both interfaces. I have no idea why it's not on yours. Maybe share some code?

**Comment by gfoiani** [comment]
Sorry it was my fault, the server responds correctly using Access Point IP Address but it doesn't work using the hostname associated to AP with mDNS.
mDNS works fine with Station but not with AP.
I associated two different hostnames one for the station and one for the AP, like this (the first is for Station and the second is fo AP):

`MDNS.begin("esp8266", WiFi.localIP());`
`MDNS.begin("esp8266-ap", WiFi.softAPIP());`

Both functions return true.
Is it correct?
I know this is out from the issue topic so if it is not acceptable I'll close the issue.

Thanks

**Comment by me-no-dev** [comment]
that is a "problem" in mDNS :) maybe you want to look into starting DNS on the AP interface and forward all requests to the ESP (captive portal)

**Comment by gfoiani** [comment]
Ok thanks, now it works using a captive portal solution like [this](https://github.com/esp8266/Arduino/blob/master/libraries/DNSServer/examples/CaptivePortalAdvanced/CaptivePortalAdvanced.ino).
