### ISSUE TITLE
gzipped file not recognized by the browser

### ISSUE THREAD

**Issue by gfoiani** [me-no-dev/ESPAsyncWebServer#115]
Hi,

due to the small size of the SPIFFS in my ESP8266 (1 MB) I need to gzip the JS file that is loaded from my web application (a single page application made with ReactJS). 
I have to remove the original JS file because it's too large, keeping only the .js.gz file on the filesystem.
When the browser requests for the JS file, the connection completes but the content is not "ungzipped" by the browser and the response headers are missing.
Putting some debug code in the server code I can see that the `AsyncFileResponse` correctly adds the header to the response with the following:
 `addHeader("Content-Encoding", "gzip");`

Any idea why the content is not served correctly?

Thanks

P.S. In the attachments there are the response preview and the request headers from Google Chrome console.
![schermata 2017-01-05 alle 16 09 21](https://cloud.githubusercontent.com/assets/1247078/21685369/9b69dfe4-d361-11e6-9b4c-130c8ea382a7.png)
![schermata 2017-01-05 alle 16 09 07](https://cloud.githubusercontent.com/assets/1247078/21685370/9b6d136c-d361-11e6-9142-ddd7e28537a1.png)

**Comment by gfoiani** [comment]
One thing I noticed is that the size of the file downloaded by the browser is different from the original file size. The original file size is 233 KB, but Chrome shows me that the file size is only 222KB.

Maybe the file is corrupted because the server does not send it completely?
![schermata 2017-01-07 alle 11 03 43](https://cloud.githubusercontent.com/assets/1247078/21740944/33e7126a-d4c9-11e6-9928-52d60f8e06c9.png)

**Comment by me-no-dev** [comment]
I would think so yes. question now is why it happens. are yoiu positive the file on spiffs is good?

**Comment by gfoiani** [comment]
I think the file on spiffs is good, I'm using Sketch Data Upload tool in Arduino IDE and it doesn't give me errors after upload..
If I understood well, when the browser requests for a JS file that has a gzipped version, the server should respond with the same content type in the header adding only content encoding:

`addHeader("Content-Encoding", "gzip");`

Is it right?

**Comment by me-no-dev** [comment]
yes. The server will send the gzipped file with content type of the unzipped version and adding Content-Encoding header for gzip

**Comment by me-no-dev** [comment]
I use primarily gzipped files and do serve files larger than that, so I still wonder what is breaking it

**Comment by gfoiani** [comment]
It's really strange because, if I try to make a direct request to the JS file the file is correctly ungzipped and showed in browser.
So calling the single file the server responds correctly with the correct headers and the content length is correct (227 KB).
My JS file is required by the index.htm file and I'm serving the application in this way:

`server.serveStatic("/", SPIFFS, "/app").setDefaultFile("index.htm");`

All assets are in `app` folder on SPIFFS.
The content length of the JS file required by index.htm seems to be not correct (222 KB) and in Chrome console I get the following error (probably because the file is not completely downloaded):

`96df401f.js:1 Uncaught SyntaxError: Invalid or unexpected token`

Could it be a timeout issue? So the connection is closed before the content is completely downloaded? The request time is more than 4 seconds..

**Comment by gfoiani** [comment]
I tried to increase the timeout to 10 seconds but the result is the same. The request now lasts more than 10 seconds..

I also tried to serve the application locally on my laptop with a PHP server, pointing only to the remote JS file on ESP8266. The application works fine and the single JS file is downloaded correctly.
The problem seems to appear when the file is requested together with other files.
My application uses a quite large amount of memory so I have only 11 KB of free heap on the ESP8266, could it be a problem of low memory available on the device?
If the file is requested individually the memory is enough, while if it is requested together with other assets the requests are parallel and there isn't enough free memory to serve all the assets..

I'm just trying to guess the problem...

**Comment by gfoiani** [comment]
I tried to serve the application using the example ESP_AsyncFSBrowser and the application is served correctly, so the problem is that there is not enough free memory to serve the files. The free heap in the example is 34 KB.

I'm closing the issues because the problem is due to my application code.
