### ISSUE TITLE
Long time operation in request handler

### ISSUE THREAD

**Issue by VNovytskyi** [me-no-dev/ESPAsyncWebServer#1160]
Hi,
I spent a lot of time learning ESPAsyncWebServer API and source code but have not found the answer.
General, my task is: _In a single request send a binary file from the _Advanced REST Client_ to the ESP32 server via HTTP PUT, perform an operation on a file and receive the result of the operation as an HTML response code (200 or 500)._
My task step by step is following:
1. Receive file content on the ESP32 side by `onBody`callback and save it to the FFAT;
2. In `onRequest` callback I need to perform a long-time operation (~60 seconds) on the file;
3. If the operation is successful I need to set HTTP code 200 and send an answer. Otherwise set HTTP code 500.

I have the following test code to reproduce my situation:
```c
#include <WiFi.h>
#include <AsyncTCP.h>
#include <ESPAsyncWebServer.h>
#include "esp_task_wdt.h"

AsyncWebServer server(80);

void long_time_operation(void) {
  Serial.println("Start wait long operation");
  uint32_t start_operation_time = millis();
  while ((millis() - start_operation_time) < 60000) {
    vTaskDelay(1000);
  }
  Serial.println("End wait long operation");
}

void setup() {
  Serial.begin(115200);
  WiFi.mode(WIFI_STA);
  WiFi.begin("**************", "****************");
  if (WiFi.waitForConnectResult() != WL_CONNECTED) {
    Serial.printf("WiFi Failed!\n");
    return;
  }
  Serial.print("IP Address: ");
  Serial.println(WiFi.localIP());

  server.on("/file.bin", 
            HTTP_PUT,
            [&](AsyncWebServerRequest* request_p) {
              esp_task_wdt_delete(NULL);
              long_time_operation();

              Serial.println("Begin send");
              request_p->send(200);
              Serial.println("End send");
            },
            NULL,
            [](AsyncWebServerRequest * request, uint8_t *data, size_t len, size_t index, size_t total) {
              // save file to FFAT
            });

  server.begin();
}

void loop() {
  delay(1000);
}
```
But the problem is in the `request_p->send` function, it's a dead lock. If I set a long time operation duration near 10 seconds all is good. I have the next several ideas on how to fix it but don`t know how to implement them:
1. Save request_p object and call `request_p->send` outside the `onRequest` callback (_How to save request_p and prevent connection closing ?_);
```c
void loop() {
  long_time_operation();
  if (is_long_time_operation_ok()) {
    request_p->send(200);
  } else {
    request_p->send(500);
  }
}
```
2. Use `beginChunkedResponse` and in case of error change the HTML response code (response->setCode does not work);
```c
AsyncWebServerResponse* response_p = request_p->beginChunkedResponse("text/plain", [](uint8_t *buffer, size_t maxLen, size_t alreadySent) {
  response_p->setCode(500); // does not work
  return 0;
});
```
3. Increase server or/and TCP timeout to call `request_p->send` successfully after a long time operation.

**Comment by VNovytskyi** [comment]
Ok, thank you for your answer! I understand your suggestions, they are useful. But in my case, I need the solution with a single request. Because this request does not depend on my side. It performs by an external tool (server) which I can`t influence (
That`s why I am searching for solutions on the ESP32 Web server side. I hope to find some timeout option or something like this to perform the `request_p->send` function after a long wait or call it outside in the `loop` function.

**Comment by zekageri** [comment]
### You could do a deferred request than.

**Check this out:** 

```C
// Create a queue for the requests.
QueueHandle_t longOperationQueue;

void setup(){
    longOperationQueue = xQueueCreate( 10, sizeof( AsyncWebServerRequest* ) );
    serverRoutes(); // setting up async server routes...
}

void serverRoutes(){
  server.on("/file.bin", HTTP_GET, [](AsyncWebServerRequest *request) {
     // Put the request in the queue
      if( xQueueSend( longOperationQueue, ( void * ) &request, ( TickType_t ) 10 ) != pdPASS ){
        request->send(500); // Send internal server error if we did not manage to put the request to the queue.
      }
  });
}

// Consume the requests in the queue one by one in the loop.
void processFileOperationRequests(){
    if( uxQueueMessagesWaiting( longOperationQueue ) ){
        AsyncWebServerRequest* request;
        if( xQueueReceive( longOperationQueue, &( request), ( TickType_t ) 10 ) ){
            // Do things with the request like request->send(200);
        }
    }
}

void loop(){
    processFileOperationRequests();
}
```

**Comment by kxxt** [comment]
> The last thing is how to set up the web server for deferred request or how to increase timeout for specified request.

After some digging, I found that the timeout can be changed in`src/WebServer.cpp`. Just change the number `3` in `setRxTimeout` to whatever value you want and it will work as expected!

https://github.com/me-no-dev/ESPAsyncWebServer/blob/f71e3d427b5be9791a8a2c93cf8079792c3a9a26/src/WebServer.cpp#L41-L51

**Comment by wuspy** [comment]
> > The last thing is how to set up the web server for deferred request or how to increase timeout for specified request.
> 
> After some digging, I found that the timeout can be changed in`src/WebServer.cpp`. Just change the number `3` in `setRxTimeout` to whatever value you want and it will work as expected!
> 
> https://github.com/me-no-dev/ESPAsyncWebServer/blob/f71e3d427b5be9791a8a2c93cf8079792c3a9a26/src/WebServer.cpp#L41-L51

You don't even need to edit WebServer.cpp to do this, you can set the timeout on a per-client basis in the request

```cpp
    server->on("/someurl", HTTP_GET, [&](AsyncWebServerRequest *request) {
        request->client()->setRxTimeout(60000);
        ...
    });
```
