### ISSUE TITLE
Downloading error over 5.6 KB data and Streaming data upto 5.6 KB

### ISSUE THREAD

**Issue by Ritik2k1** [me-no-dev/ESPAsyncWebServer#1165]
Hello everyone, 

I want to download and stream file of spiffs using web server but I'm struggling when it comes to download and stream file over 5.6 KB. 
While using this library here I get the size of maxLen and it is 5.6 KB, i think due to the maxLen size I can't download files over 5.6 KB, and on stream it streams only 5.6 KB of data. So how i download and stream data over  5.6 KB? and how can i change maxLen size? 
Device: M5Core 2

**Comment by r3v1** [comment]
Having the same problem. Do you find any solution?

**Comment by Ritik2k1** [comment]
Not yet.

Regards,
Ritik Rajput

**Comment by cacs200281** [comment]
Same problem here :(

**Comment by r3v1** [comment]
The only workaround I found is to create files smaller than 5kb, in fact about 1kb and name them as `foo_001`, `foo_002`

**Comment by cacs200281** [comment]
I found a video that the guy uses a code with the correction, He told me that the code must be edited to work fine. Unfortunately He didn't say exactly where and what to be edited :(

**Comment by Ritik2k1** [comment]
Could you please share me that video link.

Regards,
Ritik

**Comment by cacs200281** [comment]
> Could you please share me that video link. Regards, Ritik
[Video ](https://www.youtube.com/watch?v=TmV6JAUtrvw) 
and 
[Code](https://github.com/G6EJD/G6EJD-ESP-File-Server)

**Comment by Ritik2k1** [comment]
Will check and let you know.

Regards,
Ritik
