### ISSUE TITLE
AsyncWebServer affecting dual core esp32..

### ISSUE THREAD

**Issue by RiffuDev** [me-no-dev/ESPAsyncWebServer#1166]
I am getting some readings from accelerometer in my core0, and i am trying to download a txt log file from LIttleFS using AsyncWebserver when needed. I can do all these without any problem when im doing everything in the same core. But when i try using core0 for my sensor data purpose the route just buffers and returns no output.
Below if code to download log file as txt:

```
  server.on("/data", HTTP_GET, [](AsyncWebServerRequest *request){
    request->send(LittleFS, "/readings.txt","text/plain");
  });
 
  server.on("/download", HTTP_GET, [](AsyncWebServerRequest *request){
  request->send(LittleFS, "/readings.txt", String(), true);
});
```

This will be the code for getting sensor data:

```
void getSensor(void *pvParameter){  // thhis func runs in core 0
 
 initMPU();  // initializing mpu
 
  while(1){
      mpuLoop();
      vTaskDelay(1);
  }
}
```

**Comment by zekageri** [comment]
The async server runs on a core that is available at boot. There is a chance that it runs on the same core as your function. Since the download using the file system and your reading is using that too, it will delay both.

**Comment by RiffuDev** [comment]
> The async server runs on a core that is available at boot. There is a chance that it runs on the same core as your function. Since the download using the file system and your reading is using that too, it will delay both.

okay, i can see that... any idea how to overcome this??

**Comment by zekageri** [comment]
Hmm.. you can create a semaphore for that specific file and prevent multiple access, or rase a flag when a client wants to download the file and while its downloading, the reader function buffers the data and writes to the file when it has been downloaded. Or buffer the readings anyway and write it in chunks from the beginning. Even with these, you should use LittleFs because its much faster than spiffs

**Comment by zekageri** [comment]
Also the readings can be affected by wifi if you are using adc1 and a lot of other things on core 0. That is the core which is used by other house keeping tasks such us watchdog feeding, task switch managemenet, wifi, bt, etc.
