### ISSUE TITLE
Events header support

### ISSUE THREAD

**Issue by Matheus-Garbelini** [me-no-dev/ESPAsyncWebServer#122]
Hello, i'm having trouble to receive events in my browser console through your javascript example. I'm receiving No 'Access-Control-Allow-Origin' header is present on the requested resource message.
Could we add something before responding events to include this header so i can debug my website locally?

**Comment by me-no-dev** [comment]
it's planned for addition yes :) it was requested for the WebSocket module as well. You can make the change locally if you want to get it going ;)
Just add the header [here](https://github.com/me-no-dev/ESPAsyncWebServer/blob/master/src/AsyncEventSource.cpp#L243) and should be fine

**Comment by Matheus-Garbelini** [comment]
Thank you :)
