### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by davidgraeff** [me-no-dev/ESPAsyncWebServer#126]
At the moment it is not really legal to use this library in a project, even an open source project. Could you decide for a license (GPL, LGPL for usage in other GPL, LGPL projects, or for example MIT or BSD for a less restrictive license) and add a LICENSE file to the project as well as update the source files with the respective license header?

**Comment by me-no-dev** [comment]
https://github.com/me-no-dev/ESPAsyncWebServer/blob/master/src/ESPAsyncWebServer.h#L7-L19

:)
