### ISSUE TITLE
Conflict when using secure client

### ISSUE THREAD

**Issue by AcuarioCat** [me-no-dev/ESPAsyncWebServer#128]
Hi,
I have a project running the AsyncWebServer and a secure Web Client on the same device.
When using a normal non secure client everything works fine and web pages are served up as expected.
When I change to the secure browser the web pages stall, some data is sent, some not. These are the includes I have for the client.

#include "WiFiClientSecure.h"
//#include "WiFiClient.h"
#define SERVERPORT 443
WiFiClientSecure client;
//WiFiClient client;

Can you help?
Thanks

**Comment by me-no-dev** [comment]
```WiFiClientSecure``` itself uses loots of RAM :) coupled with Async you might end up in situation where heap runs out and axTLS is not written to handle such issues.
