### ISSUE TITLE
Sending large amounts of data

### ISSUE THREAD

**Issue by pyrotechnik** [me-no-dev/ESPAsyncWebServer#1302]
Hello,
I'm solving a problem with uploading large amounts of data to a webserver. I have an SD card connected to my EPS32 and I periodically save sensor data to it using sqlite3. So far I tried to build a big json from all the data classically and send that to the server. However, here I am running into a problem with the ESP32 memory. Since the json String variable is growing fast. Next I tried sending single rows of data using the simple Async Event Source Plugin. This would be fine with me reading a database row and sending it immediately, but here the problem is that I exceed the maximum number of Events. So I wanted to ask how best to solve this problem. I will be very glad for any advice.

**Comment by zekageri** [comment]
Is the esp hosting the web?
Is the esp wants to send this data to a real server?
Does the web fetching this data?
Does the esp pushing this data?
