### ISSUE TITLE
Authentication with serveStatic

### ISSUE THREAD

**Issue by mafe** [me-no-dev/ESPAsyncWebServer#132]
I want to use serveStatic with the cache mechanism for a WebApp on SPIFFS.

How can I implement page-authentication?
I tried to do it with the setFilter() method:
```
if (!request->authenticate(http_username, http_passphrase)) //returns always false
```

**Comment by me-no-dev** [comment]
yup :) something not yet done and in plans for getting done :) authentication is not yet supported on serveStatic :(
