### ISSUE TITLE
How to read POST of multiple select

### ISSUE THREAD

**Issue by Mark-81** [me-no-dev/ESPAsyncWebServer#1329]
In my HTML I have a `select` with `multiple` option enabled:

```
<select name="weekday" id="weekday" class="form-select" size="7" multiple aria-label="Weekday">
  <option value="1">Monday</option>
  <option value="2">Tuesday</option>
  <option value="3">Wednesday</option>
  <option value="4">Thursday</option>
  <option value="5">Friday</option>
  <option value="6">Saturday</option>
  <option value="0">Sunday</option>
</select>
```

Here my code to read the POST values:

```
  _server.on("/alarm.html", HTTP_POST, [this](AsyncWebServerRequest *request)
  {
    Serial.println(request->getParam("weekday", true)->value());
    ...
```

It returns only the first item selected. 
How to retrieve the others?

Listing all the parameters I see:

```
POST[weekday]: 6
POST[weekday]: 0
```

Hence the values are correct but are mapped with the same name (as expected).
I just don't understand the right syntax to read them.

**Comment by B4stl3r** [comment]
so you expect multiple values, so an array?
request->getParam()->value() is not an array.. it's a single value ;)
so you have multiple parameters with the same name (as you expect), what did you miss out?

think about using arduinojson and send in your html / js the json object.. works great ;)

**Comment by Mark-81** [comment]
> so you have multiple parameters with the same name (as you expect), what did you miss out?

Since we have multiple parameters with the same name, and `getParam()` is not an array, it returns only one of them. I don't understand the right syntax to read them all.

**Comment by B4stl3r** [comment]
int paramsNr = request->params();
for (int i = 0; i < paramsNr; i++)

;)

**Comment by Mark-81** [comment]
Ok, so my workaround was correct. I was wondering if there is something better than this. Thank!
