### ISSUE TITLE
Send Multi Large PROGMEM data is lost data

### ISSUE THREAD

**Issue by wuwx** [me-no-dev/ESPAsyncWebServer#152]
if i use a page display many big image, about 100k per image, use PROGMEM data, not saved in spiffs.
and i open chrome to visit the html page, i see browser is allways waiting

debug the network traffic, if the image is 100k, content-size header also 100k, but webserver only send 95k to browser.

if i direct visit the image is ok, may by brwoser visit page the create multi connection to ESPAsyncWebServer, then the server is lost data ?
how can i fix it, thanks

i use esp8266/arduino 2.3.0, and ESPAsyncWebServer master, ESPAsyncTCP master

**Comment by dfangboy** [comment]
其实这个致命漏洞就是request->client()->write缺少返回为0时的判断。所以导致了客户端接收时出现丢包的问题。
