### ISSUE TITLE
SSPD

### ISSUE THREAD

**Issue by pit001** [me-no-dev/ESPAsyncWebServer#158]
Hello, thank you for the great async implementation. Is there a way to get the SSDP sample working with the ESPAsyncWebServer ? I got the /description.xml running but not more ? thank you in advice, Peter

**Comment by me-no-dev** [comment]
Check this out :) https://github.com/me-no-dev/esp8266fcgui/blob/master/esp8266fcgui.ino

**Comment by JoanMCD** [comment]
Alternativ solution: #250

**Comment by Lightwell-bg** [comment]
Small library for SSDP https://github.com/Lightwell-bg/ssdpAWS
