### ISSUE TITLE
Asynch ESP8266HTTPUpdateServer

### ISSUE THREAD

**Issue by c-mysec** [me-no-dev/ESPAsyncWebServer#160]
Is there any "official" asynch version of ESP8266HTTPUpdateServer?

I know it is just a matter of replacing ESP8266WebServer with ESPAsyncWebServer. But I think it is better if I go with a standard/official version for future proof coding.

**Comment by c-mysec** [comment]
sorry, just saw that you have an Update class for that.

**Comment by tretyakovsa** [comment]
Is there an example how to do this?
