### ISSUE TITLE
How to use this library with SD?

### ISSUE THREAD

**Issue by rokk0** [me-no-dev/ESPAsyncWebServer#164]
Im trying to make wifi logger with charts and etc. All content and logs must load from SD card, but default Arduino ESP8266 library is very slow and not asynchronous. I found SD example https://gist.github.com/me-no-dev/01d309cd3760737238cec3468b96f117 but it doesn't work (errors about 'sd::' and 'fs::'). Can someone share simple sketch for SD card hosting with ESPAsyncWebServer please?

**Comment by Byzula** [comment]
https://github.com/boblemaire/ESPAsyncSDWebServer

**Comment by nietaki** [comment]
For future archeologists:

Wherever the examples serve files from SPIFFS, using `SD` instead of `SPIFFS` in the example code Just Works (tm)!

**Comment by y3nd** [comment]
> 

No, it doesn't work well out of the box with big files, only under 4096 bytes
