### ISSUE TITLE
Why AsyncWebServer uses so much memory to handle request paramters?

### ISSUE THREAD

**Issue by c-mysec** [me-no-dev/ESPAsyncWebServer#169]
Currently I am replacing ESP8266WebServer by ESPAsyncWebserver and had run out of memory when posting some form data.

After some tests I found that ESPAsyncWebserver is using lots of ram space to handle form data.

To test, I changed the AsyncFSBrowser example sketch to display free heap memory:
1) at the end of setup();
2) at the begining of the onNotFound handler.
And also removed ArduinoOta call from loop();

Here the results (average):
Free heap after setup: 35688
Free heap when requesting http://192.168.1.123/a : 33208
Free heap when requesting http://192.168.1.123/a?a=1 : 33200
Free heap when requesting http://192.168.1.123/a?a=1&b2=&c=3&d=4 : 31976
Free heap when requesting http://192.168.1.123/a?a=1&b2=&c=3&d=4&e=5&f=6&g=8&h=9&i=10&j=11 : 30632

Average usage of 3KB for a querystring of 41 bytes.

I have a page wich sends an matrix of 8x8 checkboxes plus few combos.
It sends this 580 bytes long form:

prg=prg&autoSwitchEnabled=1&=&=&=&=&=&=&=&=&tipos1=1&S1=1&T1=1&Q1=1&V1=1&D1=1&ihr1=10&imn1=18&ial1=10&dhr1=19&dmn1=15&dal1=19&tl1=0&td1=0&tipos2=0&ihr2=0&imn2=0&ial2=0&dhr2=0&dmn2=0&dal2=0&tl2=0&td2=0&tipos3=0&ihr3=0&imn3=0&ial3=0&dhr3=0&dmn3=0&dal3=0&tl3=0&td3=0&tipos4=0&ihr4=0&imn4=0&ial4=0&dhr4=0&dmn4=0&dal4=0&tl4=0&td4=0&tipos5=0&ihr5=0&imn5=0&ial5=0&dhr5=0&dmn5=0&dal5=0&tl5=0&td5=0&tipos6=0&ihr6=0&imn6=0&ial6=0&dhr6=0&dmn6=0&dal6=0&tl6=0&td6=0&tipos7=0&ihr7=0&imn7=0&ial7=0&dhr7=0&dmn7=0&dal7=0&tl7=0&td7=0&tipos8=0&ihr8=0&imn8=0&ial8=0&dhr8=0&dmn8=0&dal8=0&tl8=0&td8=0&=&

And the free heap at the begining of the notfound handler drops to 23224 bytes.

10KB of ram to handle my Forn with 580 characters.

I did not had this issue with the old ESP8266Webserver. Perhaps only because the other library is not async.

The Esp have frequent crashes when submiting the form now because the hadler is async and my sketch performs some criptographic operations in the loop.

Is there something I can do to reduce memory used by the ESPAsyncWebserver?

**Comment by me-no-dev** [comment]
there are very few things that can be done and it will not be dramatic as result either ;) he regular server uses about the same memory also when parsing. Just does it linear and at the end it frees it. For you the query string is 41-500 bytes, but the reality is different :) there are headers and other data also. When you parse a form specifically, it's quite intensive.

**Comment by c-mysec** [comment]
In my tests, I only added form params. Headers remain the same for all requests. But memory usage increase rapidly with new parameters.

**Comment by c-mysec** [comment]
Is there a way to make AsyncWebServer delay request parsing momentarily while I am doing memory intensive processing in the loop? something like server.pause() and server.continue()?
