### ISSUE TITLE
Get raw POST/PUT

### ISSUE THREAD

**Issue by buzzy** [me-no-dev/ESPAsyncWebServer#174]
Sorry, this is not a bug, but I did not know where to ask this.

How do I access the raw post-body/put-body?
I am doing a PUT with raw JSON in the request-body and can't figure out how to access it. Thanks!

**Comment by me-no-dev** [comment]
it should come as data in "onBody" https://github.com/me-no-dev/ESPAsyncWebServer#body-data-handling

**Comment by buzzy** [comment]
Thanks! That did it :)
