### ISSUE TITLE
AJAX requests causing reset of ESP8266

### ISSUE THREAD

**Issue by kdobrev** [me-no-dev/ESPAsyncWebServer#178]
I am trying to execute the following function, but my ESP crashes as soon as I press the button calling the function. It does not seem to enter any server.on();

function send_comand(gsm_number) {
  var xhttp = new XMLHttpRequest;
  xhttp.open("POST", "/", true);
  xhttp.send("action=erasen&gsm1=" + gsm_number);
  // window.location = window.location;
}

**Comment by me-no-dev** [comment]
I see no Arduino/AsyncServer code here? maybe show us that as well?
