### ISSUE TITLE
cannot serve static file

### ISSUE THREAD

**Issue by andig** [me-no-dev/ESPAsyncWebServer#2]
Look at https://github.com/me-no-dev/ESPAsyncWebServer/blob/master/src/WebHandlers.cpp#L28

If init looks like this:

    server.serveStatic("/small2", SPIFFS, "/index-small.html");

The file is not served. I think it's missing:

    else {
     path = _path;
    }

**Comment by me-no-dev** [comment]
it sure is missing! good catch :)
