### ISSUE TITLE
Delay response Json object

### ISSUE THREAD

**Issue by micha1983** [me-no-dev/ESPAsyncWebServer#202]
I Programmed a URL If this URL is called the given Parameters are used to connect to a new wifi. 
One of this Parameters is, ue DHCP yes/no. 

As the response of the called URL i would like to send a json with the ip Adresse given by the dhcp. 
But therefore i have to wait for the wifi Client Feedback. 
How can i Delay the response of the URL request until i Receive the ip of the dhcp. 

Delay is Not Working like written in the documents. 

Thanks
Michael

**Comment by micha1983** [comment]
no not yet. i have#t followed this for a long time. but i'd would still be very nice. so if you will find something, let me please know.

cheers
Michael

**Comment by rjlexx** [comment]
Please, check @hreintke answer regarding schedule_function here:
https://github.com/me-no-dev/ESPAsyncWebServer/issues/383
May be it help you also.
