### ISSUE TITLE
Connect a simple websocket client from another ESP8266?

### ISSUE THREAD

**Issue by cotestatnt** [me-no-dev/ESPAsyncWebServer#206]
I have one ESP8266 working like webserver and i use it in order to sync GPIO status with connected clients (browser).
Now, i need to connect others ESP8266 acting like clients for exchanging data with server.
I saw there is a class named AsyncWebSocketClient, ho can i use it without adding other library?

**Comment by me-no-dev** [comment]
It's not a client is the sense that you can use it to connect to a web socket server :) you need a websocket client lib for that. https://github.com/Links2004/arduinoWebSockets/tree/master/src

**Comment by cotestatnt** [comment]
Ok, i'll do that.
Anyway, thank you for a so useful library!

**Comment by ChangeD20** [comment]
> It's not a client is the sense that you can use it to connect to a web socket server :) you need a websocket client lib for that. https://github.com/Links2004/arduinoWebSockets/tree/master/src

I´ve tried to use the lib you mentioned with no succes.

@me-no-dev - could you please help out here?

https://github.com/me-no-dev/ESPAsyncWebServer/issues/956#issuecomment-799650192
