### ISSUE TITLE
Crashes on low heap due to bug in String implementation in core library

### ISSUE THREAD

**Issue by me21** [me-no-dev/ESPAsyncWebServer#210]
I've noticed some crashes which seem to be caused by [the issue in String implementation in core library](https://github.com/esp8266/Arduino/issues/3555).

Here's the decoded stack trace (unfortunately, line numbers are incorrect, and I don't know how to fix them):
```
Exception Cause: 28  [LoadProhibited: A load referenced a page mapped with an attribute that does not permit loads]

0x4020a96f: strchr at C:\.platformio\packages\framework-arduinoespressif8266\cores\esp8266/libc_replacements.c:342
0x402017a6: String::String(char const*) at C:\.platformio\packages\framework-arduinoespressif8266\cores\esp8266/WString.cpp:720
0x40201bdb: String::indexOf(char) const at C:\.platformio\packages\framework-arduinoespressif8266\cores\esp8266/WString.cpp:720
0x4020742c: AsyncWebServerRequest::_parsePlainPostChar(unsigned char) at C:\Temp\Platformio Projects\autotag/.piolibdeps\ESPAsyncWebServer_ID306\src/WebRequest.cpp:983
0x4021f3b4: ip_output_if at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/ipv4/ip.c:631
0x40207c2b: AsyncWebServerRequest::_onData(void*, unsigned int) at C:\Temp\Platformio Projects\autotag/.piolibdeps\ESPAsyncWebServer_ID306\src/WebRequest.cpp:983
0x4021f3f4: ip_output at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/ipv4/ip.c:817
0x40107394: vPortFree at C:\.platformio\packages\framework-arduinoespressif8266\cores\esp8266/heap.c:18
0x40207ca9: _M_invoke at C:\Temp\Platformio Projects\autotag/.piolibdeps\ESPAsyncWebServer_ID306\src/WebRequest.cpp:983
0x4020a308: AsyncClient::_recv(tcp_pcb*, pbuf*, signed char) at C:\Temp\Platformio Projects\autotag/.piolibdeps\ESPAsyncTCP_ID305\src/ESPAsyncTCP.cpp:650
0x4021cd96: tcp_output at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/tcp_out.c:925
0x4020a35b: AsyncClient::_s_recv(void*, tcp_pcb*, pbuf*, signed char) at C:\Temp\Platformio Projects\autotag/.piolibdeps\ESPAsyncTCP_ID305\src/ESPAsyncTCP.cpp:650
0x40221d1c: tcp_input at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/tcp_in.c:394 (discriminator 1)
0x4021b615: pbuf_alloc at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/pbuf.c:388
0x40220000: espconn_get_packet_info at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/app/espconn.c:1005
0x4021f10d: ip_input at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/ipv4/ip.c:559
0x4010068c: free at C:\.platformio\packages\framework-arduinoespressif8266\cores\esp8266\umm_malloc/umm_malloc.c:1733
0x40222fca: hostap_input at ??:?
0x4021e509: ethernet_input at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/netif/etharp.c:1379
0x40104062: lmacTxFrame at ??:?
0x401047b2: wdt_feed at ??:?
0x40213d9c: ets_timer_handler_isr at ??:?
0x40213dc2: ets_timer_handler_isr at ??:?
0x402172db: system_get_sdk_version at ??:?
0x40000f49: ?? ??:0
0x40000f49: ?? ??:0
```

It seems that `String::changeBuffer` can set current buffer pointer to NULL. That function is called from `String::reserve`, and this one can is called directly from ESPAsyncWebServer code and indirectly by `String::concat` and `operator+`, `operator +=`.

Until the bug is fixed at core libraries, it is possible to catch the error at ESPAsyncWebServer level by checking if string buffer is NULL after string concatenation or string memory reserving.

The bug is more easily triggered in low heap situations, hence the title. But I think that queries that are large enough can deplete the heap memory by themselves, leading to reboot of ESP8266 and denial of service.

**Comment by etiquet** [comment]
Hi, might be related to what I am observing, see issue#200.
For the moment the only way to reduce my lowheap condition issue prb is to follow part of #157, by limiting the number of // tcp connexion. I could'nt write a useful line of code that return with confidence a 5xx error this when the handle got the hand this is too late. Too much load can still crash the ESP. I was somehow convinced that the issue were elsewhere due low level stuff, you might have narrowed it. 
Might be interesting to check across those issues. 
I am not a good programmer but happy to help.
