### ISSUE TITLE
"Respond with content coming from a File containing templates" not working

### ISSUE THREAD

**Issue by UlliBien** [me-no-dev/ESPAsyncWebServer#211]
I tried the example for "**Respond with content coming from a File containing templates**". The callback method "**processor(..)**" is never called.

`request->send(SPIFFS, "/index.htm", String(), false, processor);` initializes a new intance of `AsyncAbstractResponse` class (`AsyncFileResponse` is derived from `AsyncAbstractResponse`). Field `_chunked` is set to true by the constructor. Via some other methods `AsyncAbstractResponse::_ack(..)` is called.

The problem is that `_ack(..)` does not call method `AsyncAbstractResponse::_fillBufferAndProcessTemplates(..) `which calls `_callback(..)` if `_chunked` is set to true. But it should! It calls `_fillBuffer(..)` instead. :-(

**Comment by UlliBien** [comment]
This is a workarround for file "/t.svg":
```
...
  server.on("/t.svg", HTTP_ANY, handleCurrentTemperatureRequest);
...
```
```
void handleCurrentTemperatureRequest(AsyncWebServerRequest * request) {
  String sHTML;
  File PageFile = SPIFFS.open("/t.svg", "r");
  if (PageFile) {
    sHTML = readString(PageFile);
    PageFile.close();
    sHTML.replace("17,5", "20,1");
  }

  request->send(200,"image/svg+xml",sHTML);
}
```
With  `readString` (copied from Stream.cpp but with no yield):
```
// private method to read stream 
String readString(File s) {
  String ret;
  int c = s.read();
  while (c >= 0) {
    ret += (char) c;
    c = s.read();
  }
  return ret;
}
```

**Comment by me21** [comment]
Oops, something got lost during pull request #189. Please check pull request #213, it should fix the bug.
