### ISSUE TITLE
HTTP Persistent Connection and Pipelining

### ISSUE THREAD

**Issue by jeremypoulter** [me-no-dev/ESPAsyncWebServer#222]
Is [HTTP Persistent Connection](https://en.wikipedia.org/wiki/HTTP_persistent_connection) and [HTTP Pipelining](https://en.wikipedia.org/wiki/HTTP_pipelining) supported by ESPAsyncWebServer? If yes, is there an example? If no, where is the best place to start to implement it?

Stepping back a bit this is to help to loading a web page  using a .local (mDNS) host. Currently each resource is taking 2 seconds + to resolve the host name, so I am hoping using pipelining and/or persistent connections will drop down to a single host name resolution.

**Comment by me-no-dev** [comment]
Maybe use WebSocket instead?

**Comment by jeremypoulter** [comment]
This will probably work for some of the API calls, and indeed I have been starting to do this, but I am not sure how practical it is to download CSS, JS and images over WebSockets

**Comment by me-no-dev** [comment]
I don't get why it takes 2s to resolve  .local host?

**Comment by jeremypoulter** [comment]
I assume it is because these are using mDNS to resolve:

![screenshot 2017-09-08 14 51 10](https://user-images.githubusercontent.com/6116992/30214707-4b7d5e2e-94a5-11e7-815d-85362f082757.png)

**Comment by me-no-dev** [comment]
Maybe you can use NBNS on Windows so you can access it only by http://openevse/ :)
See here: https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266NetBIOS/examples/ESP_NBNST/ESP_NBNST.ino#L43

**Comment by jeremypoulter** [comment]
Thanks, will give that a go.

Out of curiosity are you able to comment on the changes needed to support
at least persistent connections?

**Comment by me-no-dev** [comment]
Not really sure TBH. I'm not positive that its a good idea on an mcu either :) you want to clear the memory ASAP and it's easy to have a connection running wild without knowing.
