### ISSUE TITLE
“Connection refused” when send GET-request from ESPAsyncWebServer

### ISSUE THREAD

**Issue by topersober** [me-no-dev/ESPAsyncWebServer#229]
Hello everyone! 
My Congratulations on World Day of the Programmer!!!

I have some TEST function that sends GET-request from one ESP to another.
(Both of them are working on ESPAsyncWebServer)
1) When I enter http://192.168.43.208/led=1 from Google Chrome – all fine 
2) When I use standart ESP8266WebServer on the FIRST ESP and call TEST function - all fine
3) When I use ESPAsyncWebServer and call TEST function before starting ESPAsyncWebServer (before calling server.begin();) - all fine, second ESP responsing 200.
but...
4) When i call TEST function after staring  ESPAsyncWebServer, I get error code (-1)
(if I switch off AsyncWebSocket and AsyncEventSource - problem remains)
SO I think, problem is in ESPAsyncWebServer core
Please Help me...

P.S.
#include <ESP8266HTTPClient.h>
void test() {
  HTTPClient myhttp;
  myhttp.begin("http://192.168.43.208/led=1");
  int myhttpCode = myhttp.GET();
  if(myhttpCode == HTTP_CODE_OK) {
      String myRequest = myhttp.getString();
      Serial.println(myRequest);
  }
  myhttp.end();
}

**Comment by me-no-dev** [comment]
are you calling test inside async callback?

**Comment by topersober** [comment]
Yes.  I tried inside:
1) server.on("/test", HTTP_GET, [](AsyncWebServerRequest * request) {
    test();  
  });

2) void onWsEvent(AsyncWebSocket * server, AsyncWebSocketClient * client, AwsEventType type, void * arg, uint8_t *data, size_t len) {
    test();
}

**Comment by me-no-dev** [comment]
this would not work inside async callback. And in your callbacks you never respond to that request, which is another error. Since HTTPClient uses yield and delay underneath, that will break async and lead to reboot usually.
