### ISSUE TITLE
Pages with similar names

### ISSUE THREAD

**Issue by terryjmyers** [me-no-dev/ESPAsyncWebServer#231]
Found a really minor issue.
If you have multiple pages such as:

	HTTPserver.on("/Config", HTTPConfig);
	HTTPserver.on("/Config/Network", HTTPNetwork);
	HTTPserver.on("/Config/LiveData", HTTPConfigLiveData);
	HTTPserver.on("/Config/Time", HTTPConfigTime);

Then only the /Config page will be returned even if the url is ....Config/Network.  I understand from the documentation that the pages are added in the order that they are instantiated, and this was the reason, but it was still an undesired behavior.  I simply changed the first line to:

	HTTPserver.on("/Config/General", HTTPConfigGeneral);

and renamed my function.  Just thought I'd mention the limitation in case you wanted to correct it.

**Comment by me-no-dev** [comment]
just add ```HTTPserver.on("/Config", HTTPConfig);``` last :)

**Comment by me-no-dev** [comment]
it goes in the order of  addition, so would match to the other ones first :)
