### ISSUE TITLE
Response to a query outside the function

### ISSUE THREAD

**Issue by mcmega** [me-no-dev/ESPAsyncWebServer#248]
Hello!
Help me please.
I'm requesting from a browser /mcu/settings
The server sends a command to the UART

```
server.on("/mcu/settings", HTTP_GET, [](AsyncWebServerRequest *request) {
    uartSendCommand("GET", "settings");
});
```
I want to return UART Data to the browser. The length of the answer is unknown.
How to do it?

**Comment by mcmega** [comment]
Can not create a response outside the function.

**Comment by me-no-dev** [comment]
use chunked response... is this ESP32 or ESP8266? Would not be possible on ESP8266. And you are not responding to the request in your handler above which will lead to the server breaking.

**Comment by mcmega** [comment]
I use ESP8266 (8285).
I want to respond with data that comes from UART, so there is no answer to the query. But I do not know how to do it.

**Comment by mcmega** [comment]
I did everything on WebSocket, but the question is not settled, it would not be bad to have more examples!
