### ISSUE TITLE
Error server.uri() & .streamFile

### ISSUE THREAD

**Issue by mcmega** [me-no-dev/ESPAsyncWebServer#249]
Hello!
Thank you for the wonderful library!

My Arduino write error
'class AsyncWebServer' has no member named 'uri'.
char path[32] = "";
strncat(path, server.uri().c_str(), sizeof(path) - 1 - strlen(path));
and
'class AsyncWebServer' has no member named 'streamFile'
server.streamFile(file, request->hasArg("download") ? "application/octet-stream" : mime(path));

How right write?
Thank you!

**Comment by me-no-dev** [comment]
Check the README :) all is explained there :) you access the request and not the server. And API is a bit different than the regular WebServer
