### ISSUE TITLE
WDT Resets Continually

### ISSUE THREAD

**Issue by wahabkhan1892** [me-no-dev/ESPAsyncWebServer#253]
I am implementing a web server that sends a lot of data to the client once the client connects, and opens the home page (192.168.4.1). Because of the large amount of data, I was getting LmacRxBlk errors when using the normal ESP8266WebServer, so I decided to switch to AsyncWebServer. I took the example as a template and implemented my own responses. Now when I start the device, I can see the web server having successfully started, but then I get a WDT timeout, and the device resets.

Below is a snippet of the server setup code. The device is working in AP mode, and the homepage allows the user to select a WiFi network and connect to it. Once connected, the device switches to STA mode. There is also a DNS server running, which redirects all requests to homepage while the device is in AP mode and not connected to the internet yet.

`ws.onEvent(onWsEvent);
    server.addHandler(&ws);
    
    events.onConnect([](AsyncEventSourceClient *client){
        client->send("hello!",NULL,millis(),1000);
    });

    server.addHandler(&events);
    
    server.on("/networks", HTTP_GET, [](AsyncWebServerRequest *request)
    {
        //show available WiFi networks
    });
    
    server.on("/connect", HTTP_POST, [](AsyncWebServerRequest *request)
    {
        //connect to a WiFi network
    });
        
    server.onNotFound([](AsyncWebServerRequest *request)
    {
        //redirect to homepage
    });
     
    server.onFileUpload([](AsyncWebServerRequest *request, const String& filename, size_t index, uint8_t *data, size_t len, bool final)
    {
        if(!index)
            Serial.printf("UploadStart: %s\n", filename.c_str());
        Serial.printf("%s", (const char*)data);
        if(final)
            Serial.printf("UploadEnd: %s (%u)\n", filename.c_str(), index+len);
    });
  
    server.onRequestBody([](AsyncWebServerRequest *request, uint8_t *data, size_t len, size_t index, size_t total)
    {
        if(!index)
            Serial.printf("BodyStart: %u\n", total);
        Serial.printf("%s", (const char*)data);
        if(index + len == total)
            Serial.printf("BodyEnd: %u\n", total);
    });
    
    server.serveStatic("/", SPIFFS, "/").setDefaultFile("index.htm");
    server.begin();
`

**Comment by JamesNewton** [comment]
I'm curious how you know it's a watchdog reset... I'm getting restarts for reason 2 "Exception", but I am also trying to get away with short delays in my response handlers which is verboten and probably why it's happening to me. I wonder if yours is getting so bogged down that the delay is causing the WDT?
