### ISSUE TITLE
Templating problem

### ISSUE THREAD

**Issue by thedroid** [me-no-dev/ESPAsyncWebServer#254]
There seems to be an issue with the template processor as it does not always replace correctly.  It is 100% reproducible on my system with the test program attached.  Please see the screenshot for the problem.

using 
git ESPAsyncWebServer
git Eps8266 Arduino
NodeMCU .9

[test.zip](https://github.com/me-no-dev/ESPAsyncWebServer/files/1370257/test.zip)
![templates](https://user-images.githubusercontent.com/903065/31365181-26e91628-ad2f-11e7-830e-e001b87df52d.jpg)

**Comment by me21** [comment]
I'll look at it. Meanwhile, it seems there's an alternative template engine in PR #236.

**Comment by me21** [comment]
Try PR #267, it should fix the bug.

**Comment by thedroid** [comment]
Will test and report back.

**Comment by thedroid** [comment]
Will test and report back

**Comment by aharshac** [comment]
@me21 @thedroid The problem still exists.

**Comment by me21** [comment]
@aharshac please give an example. Or did you mean the problem still exists with thedroid's original test.zip?
