### ISSUE TITLE
ESPAsyncWebServer stop working

### ISSUE THREAD

**Issue by rick-bp** [me-no-dev/ESPAsyncWebServer#258]
Hello!

ESPAsyncWebServer stop working after update esp8266/Arduino to 2.4.0-rc2

**Comment by me-no-dev** [comment]
Yeah I heard there is an api change. Is 2.4.0-rc2 merged into Master?

**Comment by rick-bp** [comment]
Sorry, I don't know.

**Comment by rick-bp** [comment]
Thank you for correction!
