### ISSUE TITLE
Error fetching data (Access-Control-Allow-Origin)

### ISSUE THREAD

**Issue by mcmega** [me-no-dev/ESPAsyncWebServer#264]
I request data from the remote module. In the console error: 
Failed to load http://192.168.0.101/icon: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.0.10' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

```
General
Request URL:http://192.168.0.101/icon
Request Method:GET
Status Code:200 OK
Remote Address:192.168.0.101:80
Referrer Policy:no-referrer-when-downgrade

Response Headers
view parsed
HTTP/1.1 200 OK
Content-Length: 699
Content-Type: text/html
Connection: close
Accept-Ranges: none

Request Headers
GET /icon HTTP/1.1
Host: 192.168.0.101
Connection: keep-alive
Origin: http://192.168.0.10
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Accept: */*
Referer: http://192.168.0.10/
Accept-Encoding: gzip, deflate
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4
```
What could it be?

**Comment by me-no-dev** [comment]
You need to add the header :) it is not there by default. Consult the README
