### ISSUE TITLE
Enable SSL for ESPAsyncWebServer on ESP32

### ISSUE THREAD

**Issue by edautz** [me-no-dev/ESPAsyncWebServer#269]
ESPAsyncTCP for ESP8266 in the file ESPAsyncTCP/src/async_config.h SSL can be enabled 
though the setting #define ASYNC_TCP_SSL_ENABLED 1

When using ESP32 by using AsyncTCP library this option is not there. The async_config.h is missing.

Is there a way to enable SSH on the ESP32 when using the ESPAsyncWebServer?

**Comment by me-no-dev** [comment]
Not yet :) I have not looked at Async SSL on ESP32 yet.

**Comment by edautz** [comment]
Thnx. Any idea when this be accomplished? I volunteer as beta tester.
