### ISSUE TITLE
serveStatic("/" ...) results in HTTP 500

### ISSUE THREAD

**Issue by mfalkvidd** [me-no-dev/ESPAsyncWebServer#27]
readme.md says:
```
  // attach filesystem root at URL /fs 
  server.serveStatic("/fs", SPIFFS, "/");
```
I wanted to serve the root uri from /html/ on SPIFFS, so I used
`  server.serveStatic("/", SPIFFS, "/html/");`
but this results in HTTP 500. The following syntax works though:
`  server.serveStatic("", SPIFFS, "/html/");`

**Comment by vitotai** [comment]
I might have the same issue as you.
I solved it by modifying WebHandlers.cpp
String AsyncStaticWebHandler::_getPath(AsyncWebServerRequest *request)

    if (!baserequestUrl.length()) {
      baserequestUrl += "/";
    }

change to 
	
    if (!baserequestUrl.length()) {
    	if( _uri != "/")
      		baserequestUrl += "/";
    }

**Comment by ccoenen** [comment]
If anyone else lands here with SPIFFS / serveStatic and HTTP 500 errors, one thing that was not immediately obvious to me: you have to call `SPIFFS.begin()` before you can server anything successfully.
