### ISSUE TITLE
Please release point version

### ISSUE THREAD

**Issue by andig** [me-no-dev/ESPAsyncWebServer#281]
.. this will allow everybody to use the updated `library.json` files with staging version compatibility.

**THANKS**

**Comment by andig** [comment]
Its kinda unsatisfying when every single issue is closed by the stale bot without any fuether action.

**Comment by me-no-dev** [comment]
but you did not react in the two weeks that the bot notified you for :) the bot is here because there are many old issues. You acting on an issue that the bot has marked, notifies me that this is still relevant and goes to separate inbox.

**Comment by andig** [comment]
I see. Didn‘t realize I could convonce the bot its still relevant. But then- id something as simple as a release didn‘t happen in 2 years- why should it now 😂

**Comment by me-no-dev** [comment]
it's WIP :P not up to release
