### ISSUE TITLE
ESPAsyncWebClient ??

### ISSUE THREAD

**Issue by timpur** [me-no-dev/ESPAsyncWebServer#283]
Wondering if there is already some where an `ESPAsyncWebClient` or should there be ? Mainly to replace the built in `HTTPClient` of `esp8266` but uses the [ESPAsyncTCP](https://github.com/me-no-dev/ESPAsyncTCP). 

Also should the `ESPAsyncWebServer` use this? 

Also this WebClient would also support the `esp32` since there is a [AsyncTCP ](https://github.com/me-no-dev/AsyncTCP) lib for it now thanks to you (@me-no-dev)

**Comment by judge2005** [comment]
https://github.com/judge2005/ESPAsyncHttpClient

**Comment by timpur** [comment]
@me-no-dev any plans on this?

**Comment by timpur** [comment]
Thinking of create a replacement for https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h but using asyncTCP lib
