### ISSUE TITLE
Does not work together with SD.h include on ESP8266

### ISSUE THREAD

**Issue by kuzmanzs** [me-no-dev/ESPAsyncWebServer#291]
IF SD.h was included it does not compile.

**Comment by me-no-dev** [comment]
yup :) that is not an issue with this lib though ;) it's an issue with FS and SD classes on ESP8266

**Comment by Misiu** [comment]
@me-no-dev I know this is old issue but I'm wondering where I should create issue for it.
I'm quite new to ESP stuff and I made me crazy when my project stop compiling after I tried to add SD card support.
Should I create ticket for this in https://github.com/esp8266/Arduino repo?

**Comment by penfold42** [comment]
Yes
