### ISSUE TITLE
JSON Plain Post - Preload body for small post requests

### ISSUE THREAD

**Issue by timpur** [me-no-dev/ESPAsyncWebServer#295]
Wondering if its possible preload the entire body for small post request for sizes under say 1k ? instead of using on body handler?

**Comment by me-no-dev** [comment]
That is just a case of different possibilities. While it is implementable, I do not think that it's a good idea :) Better to have it work the same for all cases

**Comment by timpur** [comment]
Could it be something you enable when registering your call back function ?
