### ISSUE TITLE
Need to prevent concurrent file uploads

### ISSUE THREAD

**Issue by emard** [me-no-dev/ESPAsyncWebServer#306]
How to reject the second concurrent upload if one is already uploading?
In my application it's very easy to click "upload" twice and mess up the thing.

**Comment by CelliesProjects** [comment]
Disable the button while uploading?

**Comment by emard** [comment]
I did that and it works for single use.
although the button is disabled concurrent
upload will still be possible

**Comment by CelliesProjects** [comment]
Some example code?

**Comment by emard** [comment]
No example needed, open same web page from 2 windows,
start upload, while in one window the button will be disabled,
the other winow will show active button you can click on
and screw up
