### ISSUE TITLE
HTTPRequest to response time

### ISSUE THREAD

**Issue by cruanyes** [me-no-dev/ESPAsyncWebServer#309]
I've made one web server on a Adafruit ESP32 Feather that has one application that handle several servos.
The web page contains some sliders that using javascript sends HTTPRequest to the server and waits the response, the problem is that the HTTPRequest to get response it takes 380ms. which is a long time and servos don't move smooth.
Is there any way the get the respons faster?
Thanks

**Comment by Pablo2048** [comment]
Try websocket - IMHO its way faster because of persistent connection established between server and client.

**Comment by cruanyes** [comment]
I've tried websocket and works fine, thank you for your help
