### ISSUE TITLE
Hash dependency required in PlatformIO 

### ISSUE THREAD

**Issue by kylegordon** [me-no-dev/ESPAsyncWebServer#312]
I think Hash needs to be declared as a dependency in http://platformio.org/lib/show/306/ESP%20Async%20WebServer as https://github.com/euphi/Homie_BareMinimum fails to build if you remove 'Hash' from the platformio.ini file.

```Compiling .pioenvs/esp01/lib124/ESP Async WebServer_ID306/AsyncEventSource.o
Compiling .pioenvs/esp01/lib124/ESP Async WebServer_ID306/AsyncWebSocket.o
Compiling .pioenvs/esp01/lib124/ESP Async WebServer_ID306/SPIFFSEditor.o
.piolibdeps/ESP Async WebServer_ID306/src/AsyncWebSocket.cpp:40:18: fatal error: Hash.h: No such file or directory
```

**Comment by kimklai** [comment]
I found the problem. LDF failed to list correct library dep graph by default mode (chain mode). 
You should set 'lib_ldf_mode = deep+' to let LDF search all missing dep libraries. Or add "Hash" manually in lib_dep in case of LDF deep+ takes too long.

**Comment by andig** [comment]
@me-no-dev it would still be nice if `Hash` could be listed as dependency inside `library.json`?
