### ISSUE TITLE
Not building on current versions.

### ISSUE THREAD

**Issue by vindolin** [me-no-dev/ESPAsyncWebServer#317]
After setting everything up from scratch following the installation instructions,
I get this error when trying to compile a blank project:
```
Compiling .pioenvs/esp32dev/lib37d/ESP Async WebServer/AsyncWebSocket.o
Archiving .pioenvs/esp32dev/libFrameworkArduino.a
In file included from .piolibdeps/ESP Async WebServer/src/AsyncWebSocket.h:30:0,
from .piolibdeps/ESP Async WebServer/src/AsyncWebSocket.cpp:22:
.piolibdeps/ESP Async WebServer/src/ESPAsyncWebServer.h:27:16: fatal error: FS.h: No such file or directory
```

**Comment by theborax** [comment]
Did you solve this issue @vindolin ? I've also just set up a brand new project and run into this issue...

**Comment by vindolin** [comment]
Yes I solved it, but I really have no clue what I did to make it work, I switched to Arduino, tried some things and came back to platform.io some days later and it just worked.

**Comment by vindolin** [comment]
The only thing I did, was replacing tools/sdk/lib/libspiffs.a with the one from commit 70d0d4648766, but I don't think that's related.
See: https://github.com/me-no-dev/arduino-esp32fs-plugin/issues/6#issuecomment-362695983

**Comment by theborax** [comment]
Think I figured it out. First I didn't include anything in my main file, but once I included FS.h things built. So building a "clean" main.cpp (or whatever one wants to call it) without any imports for i.e. FS.h wont work.

**Comment by tomap** [comment]
Same for me. It did not work with the default main.cpp
I had to add 
```
#include <FS.h>
#include <WiFi.h>
```

**Comment by NicHub** [comment]
Same for me too. You could update the [Installation/Using PlatformIO chapter](https://github.com/me-no-dev/ESPAsyncWebServer?utm_source=platformio&utm_medium=piohome#using-platformio).

    // Minimal main.cpp
    #include <Arduino.h>
    #include <FS.h>
    #include <WiFi.h>
    void setup() {}
    void loop() {}
