### ISSUE TITLE
ESP32: md5.h: No such file or directory

### ISSUE THREAD

**Issue by probonopd** [me-no-dev/ESPAsyncWebServer#326]
Getting

```
ESP32: ESPAsyncWebServer/src/WebAuthentication.cpp:23:17: fatal error: md5.h: No such file or directory
```

when trying to compile on ESP32.

Reference:
https://github.com/probonopd/WirelessPrinting/issues/29

**Comment by argo69** [comment]
Hello, 
I have the same error message "md5.h: no such file or directory" when trying to compile on ESP32.
"blink" sketch compile and works ok on the board ...
An idea ?

**Comment by argo69** [comment]
of course i've checked the file is present on the correct directory...

**Comment by probonopd** [comment]
@stale go away

**Comment by me-no-dev** [comment]
@probonopd this library get's tested against Arduino and PIO on Linux, Windows and Mac. There are no dependency issues. This is not an issue in this library.

**Comment by probonopd** [comment]
OK thanks @me-no-dev, this is actually a usable information (other than the Stale bot just closing stuff).

**Comment by me-no-dev** [comment]
stale bot closed it because nobody responded for 2 weeks after it labeled the message ;) see the post it left.
