### ISSUE TITLE
On chrome, streaming temperature over websocket fails with error 1006 after a while

### ISSUE THREAD

**Issue by aguaviva** [me-no-dev/ESPAsyncWebServer#331]
This is from the Sousvide project (https://github.com/aguaviva/SousVide)

I am including a wireshark capture of when things go wrong, here is also an screenshot:

![2018-03-03-213027_1366x744_scrot](https://user-images.githubusercontent.com/5200915/36938994-4b557e6c-1f2a-11e8-98fa-04369987682a.png)

You can repro the issue without any hardware, just clone the repo and in main.cpp substitute these lines:

    static double Input;
    temperatureGetReadingSecurity(10, &Input);

with

    static double Input=10;

thats' it.

**Comment by aguaviva** [comment]
the latest development version solves this issue, I'd be interesting to understand what was causing that, it might be related to issue #332 (https://github.com/me-no-dev/ESPAsyncWebServer/issues/332)

**Comment by aguaviva** [comment]
The issue is still happening, it just takes longer to occur. 

Is there anything else I could do to help debug this issue?  I'd appreciate some guidance.

**Comment by aguaviva** [comment]
@espressif guys, I'd appreciate some guidance on how to fix this, I am sure I am not the only one trying to use sockets to stream data...

**Comment by aguaviva** [comment]
shame

**Comment by RamonHartmann** [comment]
same problem
