### ISSUE TITLE
Fix JSON Content-Type

### ISSUE THREAD

**Issue by polandj** [me-no-dev/ESPAsyncWebServer#339]
The library uses text/json as the content-type for JSON.  However, the most common content-type used is application/json.

AsyncJson.h:      _contentType = "text/json";
SPIFFSEditor.cpp:      request->send(200, "text/json", output);
WebResponses.cpp:  else if (path.endsWith(".json")) _contentType = "text/json";

**Comment by atanisoft** [comment]
this looks to be the same as https://github.com/me-no-dev/ESPAsyncWebServer/pull/311

**Comment by polandj** [comment]
Duplicate
