### ISSUE TITLE
DefaultHeaders for all http requests?

### ISSUE THREAD

**Issue by dphans** [me-no-dev/ESPAsyncWebServer#340]
How can I send default headers for all http requests?

I'm using ESPAsyncWebServer to make an API routing, testing on local browser call to device "API".
But it required need to set header from response like "Access-Control-Allow-Origin: *".
Current, each response, I create a response from request (inside `<ESPAsyncWebServer instance>.on()`). But I think, do this way is very redundancy. So any idea for me to set default headers for all requests?

I found inside library has a class named `DefaultHeaders`, is it available? I not found this in documents.

Sorry, this is not issue of library, just my problem, you are the best!

**Comment by penfold42** [comment]
Seriously ?

https://github.com/me-no-dev/ESPAsyncWebServer/blob/master/README.md#adding-default-headers

**Comment by Pablo2048** [comment]
Read the README.md especially section https://github.com/me-no-dev/ESPAsyncWebServer#adding-default-headers ... I'm using this for CORS:
  DefaultHeaders::Instance().addHeader("Access-Control-Allow-Origin", "*");
  DefaultHeaders::Instance().addHeader("Access-Control-Allow-Headers", "content-type");
BTW don't forget to add proper reaction for OPTIONS to your notfound handler.

**Comment by dphans** [comment]
OMG this is my fault, sorry. I close this issue now.
Many thanks @Pablo2048 @penfold42

**Comment by penfold42** [comment]
*grin* in your defence, the doco is a bit long and easy to miss
