### ISSUE TITLE
Keep the connection open

### ISSUE THREAD

**Issue by maxdd** [me-no-dev/ESPAsyncWebServer#347]
Say that i have the following

```
server.on("/open", HTTP_GET, [](AsyncWebServerRequest *request){
     request->send(xxx, "text/plain", "Opening");
     dostuff();
     //wait/yield/delay();
     if(a)
          request->send(xxx, "text/plain", "A executed");
     else
          request->send(xxx, "text/plain", "A not executed");
     // close connection
}
```

is there a way to keep the connection open so that one can wait/delay/yield until a variable become true?

**Comment by sebaretamozo** [comment]
Hello, reading other post I see this one is related to your post but inversely.

[https://github.com/me-no-dev/ESPAsyncWebServer/issues/199](https://github.com/me-no-dev/ESPAsyncWebServer/issues/199)

You can use ".onRequestBody" function to do what you want.
