### ISSUE TITLE
WiFi.SoftAP() : Connection refused

### ISSUE THREAD

**Issue by psykokwak-com** [me-no-dev/ESPAsyncWebServer#353]
Hello,
Following this code (for ESP32), if the WiFi STA connection failed, it fallbacks to AP mode.
But the server returns "connection refused". (TCP connection refused).

` void networkWiFiInitialize()
{
  WiFi.mode(WIFI_STA);
  WiFi.begin(_networkESSID, _networkESSIDPwd);
  WiFi.setAutoConnect(true);
  WiFi.setAutoReconnect(true);
  while (WiFi.waitForConnectResult() != WL_CONNECTED)
  {
    // Act as an AP if no existing AP connexion is made
    IPAddress apIP(192, 168, 1, 1);
    IPAddress apNetMsk(255, 255, 255, 0);

    WiFi.mode(WIFI_AP);
    WiFi.softAPConfig(apIP, apIP, apNetMsk);
    WiFi.softAP("MyAP");
  }`

If I remove the WiFi station part of the code to directly starting as AP mode, it works : 
` void networkWiFiInitialize()
{
  //WiFi.mode(WIFI_STA);
  //WiFi.begin(_networkESSID, _networkESSIDPwd);
  //WiFi.setAutoConnect(true);
  //WiFi.setAutoReconnect(true);
  //while (WiFi.waitForConnectResult() != WL_CONNECTED)
  {
    // Act as an AP if no existing AP connexion is made
    IPAddress apIP(192, 168, 1, 1);
    IPAddress apNetMsk(255, 255, 255, 0);

  
    //WiFi.mode(WIFI_AP);
    WiFi.softAPConfig(apIP, apIP, apNetMsk);
    WiFi.softAP("Sentinel OTA Upgrade");
  }
}`

**Comment by tarzan115** [comment]
this is not right place for your question. but I think you need this https://github.com/tzapu/WiFiManager

**Comment by debsahu** [comment]
@tarzan115 WiFiManager is not compatible with ESPAsyncWebServer, recommend users to look at [AsyncWiFiManager](https://github.com/alanswx/ESPAsyncWiFiManager).

**Comment by psykokwak-com** [comment]
Ok. I have to use WIFI_AP_STA instead of WIFI_AP in WiFi.mode.
