### ISSUE TITLE
sample not work in esp32--help--ESP_AsyncFSBrowser.ino

### ISSUE THREAD

**Issue by lyalove** [me-no-dev/ESPAsyncWebServer#358]
hello! now found you sample ino file do not work in esp32 mode. just work in esp8266
can you write a sample  for esp32? thks
https://github.com/me-no-dev/ESPAsyncWebServer/blob/master/examples/ESP_AsyncFSBrowser/ESP_AsyncFSBrowser.ino

**Comment by lyalove** [comment]
and i found sample  in esp8266   , not include a  h file,  is  #include <ESP8266mDNS.h>

**Comment by malbrook** [comment]
The file requires some minor changes to work with latest version of Arduino ESP32. (May2018)
[ESP32_AsyncBrowser.zip](https://github.com/me-no-dev/ESPAsyncWebServer/files/2084240/ESP32_AsyncBrowser.zip)

**Comment by lyalove** [comment]
thks very much!
