### ISSUE TITLE
Memory leak only with Android Chrome browser

### ISSUE THREAD

**Issue by sebaretamozo** [me-no-dev/ESPAsyncWebServer#360]
Hello, I have a memory leak only with Google Chrome for Android. With Google Chrome for PC there is no problem. It seems that each Android browser request consumes a little RAM and finally crash the ESP8266.

I recorded this video demonstrating the problem
[https://www.youtube.com/watch?v=QU-K5y4_gXY](https://www.youtube.com/watch?v=QU-K5y4_gXY)

Here is the code. I have tried to reduce it to a minimum.

```
#include <ESP8266WiFi.h>
#include <ESPAsyncWebServer.h>

const char* ssid = "*******";
const char* password = "********";

AsyncWebServer httpServer(80);

void setup(void){
  Serial.begin(115200);
  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);

  while(WiFi.waitForConnectResult() != WL_CONNECTED){
    WiFi.begin(ssid, password);
    //Serial.println("WiFi failed, retrying.");
  }

  httpServer.on ( "/heap", HTTP_GET, [](AsyncWebServerRequest *request){ request->send( 200, "text/plain", String(ESP.getFreeHeap()));});
  httpServer.begin();

}

void loop(void){ 
}
```

@me-no-dev 
Thanks in advance

**Comment by sebaretamozo** [comment]
I think this is not a memory leak, rather resources are not released.

When I connect directly with Hercules in port 80, the connection is closed after a timeout of 3 seconds if I do not send data. But if I send data the ESPAsyncTCP library does not close the connection and the resources are never released. However, the Sync library does release the connection in both cases.

I am still researching the ESPAsyncTCP library, I have not been able to solve the problem yet.

**Comment by tinamore** [comment]
Hi,
I have same problem.
