### ISSUE TITLE
No webpage with SPIFFS

### ISSUE THREAD

**Issue by axoulc** [me-no-dev/ESPAsyncWebServer#362]
Hello,
I upload my html file in SPIFFS mem in "www" folder and I can see this file with the help of SPIFFS functions.
This html file in also in a PROGMEM variable only for test.
`request->send(200, "text/html", HTML);` This line work great !
`request->send(SPIFFS, "/www/index.htm", "text/html");` But nothing with this line even if it is the same HTML code. The page still loading.
ESP32 return no log about.
[Whole code](https://github.com/axoulc/Logger/blob/master/main/wifi.cpp)

If someone can help me.
Thanks in advance
Axel

**Comment by drschlaumeier** [comment]
SPIFFS.begin() ???

**Comment by axoulc** [comment]
Hi, check wifi.cpp and I init spiffs before read in. Le 18 mai 2018 11:03, drschlaumeier <notifications@github.com> a écrit :SPIFFS.begin() ???

**Comment by drschlaumeier** [comment]
ahh, sorry...
I was using request->send(SPIFFS, "/jquery.min.js.gz"); to read from SPIFFS but ESP32 is crashing #361 .

Did you check if file exists?
if (SPIFFS.exists("/jquery.min.js"))  ...
