### ISSUE TITLE
Feature request:  serveStatic with callback

### ISSUE THREAD

**Issue by ABH10** [me-no-dev/ESPAsyncWebServer#363]
I have a large file in SPIFFS that is often updated. I want to set a flag when the file is being downloaded through ESPAsyncWebServer in order to detect when it is not safe to update the file. In my experience it is not safe to update the file while it is read through another file descriptor in SPIFFS.
I can't figure out how to do this.
I use server.serveStatic("/", SPIFFS, "/"); which is convenient because it serves any file name in SPIFFS, but it has no callback function.
If I define a specific server for the file in question, then I can define a callback function where I can set/reset the new flag that I want. However, then I am facing the problem that the filename is not known at compile time and the server needs "const *char" filename input. Not even the rewrite function can be used, as it also requires "const *char" filename input.

**Comment by dpitts** [comment]
Maybe you can cast the known file name in memory at runtime to (const *char)
