### ISSUE TITLE
Specifying Template Processor callback question

### ISSUE THREAD

**Issue by smacyas** [me-no-dev/ESPAsyncWebServer#369]
I have static test.html file (fragment):

<div class="container">				
	<h2 align='center'></h2>
	<table border='1'>
		<tbody>
		<tr>
			<td align='center'>Name</td>
			<td align='center'>Value</td>
		</tr>
		<tr>
			<td>%NAME1%</td>
			<td>%VALUE1%</td>
		</tr>
.....
		<tr>
			<td>%NAME50%</td>
			<td>%VALUE50%</td>
		</tr>

</div>

I want to put my values instead %NAME1%-%NAME50% and %VALUE1%-%VALUE50%.

My construction does not work:
setup()
{
....
server.serveStatic("/test.html", SPIFFS, "/test.html").setTemplateProcessor(processor);
}

String processor(const String& var)
{
  if(var == "NAME1") return F("My name1");
  if(var == "NAME2") return F("My name2");
....
  if(var == "NAME50") return F("My name50");
if(var == "VALUE1") return F("Value 1");
if(var == "VALUE2") return F("Value 2");
....
if(var == "VALUE50") return F("Value 50");
  
  return String();
}

Where is a mistake?

**Comment by me21** [comment]
Just a thought: if your test.html file is stored gzipped in SPIFFS, template processor is silently turned off.
