### ISSUE TITLE
Example --Controlling a pin

### ISSUE THREAD

**Issue by nkuzito** [me-no-dev/ESPAsyncWebServer#375]
I would like the webserver to run a specific method if a specific url is accessed. For the sake of discussion, suppose I want to turn on an LED when the `/turn_on` path is accessed. 

`server.on("/turn_on_led", HTTP_POST, [](AsyncWebServerRequest *request){
    request->send(200);
  }, TurnOnLed);
`
And that my TurnOnLed function is defined as follows:

```
void TurnOnLed()
{
    digitalWrite(RED_LED_PIN, HIGH);
}
```
But unfortunately this approach does not even compile. How can I solve this?

**Comment by Pablo2048** [comment]
probably this way?:
`server.on("/turn_on_led", HTTP_POST, [](AsyncWebServerRequest *request){ TurnOnLed(); request->send(200);});`
