### ISSUE TITLE
HTTPS or TLS / SSL support ?

### ISSUE THREAD

**Issue by JacoFourie** [me-no-dev/ESPAsyncWebServer#377]
This is more a question.
Does the server support HTTPS ?

**Comment by arihantdaga** [comment]
Yes it does.. 
Although examples are not written properly but you can look into code and see functions like beginSecure()

**Comment by bbasil2012** [comment]
And what about examples ?

**Comment by me-no-dev** [comment]
HTTPS is only for ESP8266 for now, and I do not recommend using it, because it limits the server to one concurrent connection and causes heap to drop dramatically...

**Comment by me21** [comment]
Are there any plans for supporting HTTPS on ESP32?

**Comment by kamil2234** [comment]
I join to this question

**Comment by me21** [comment]
There's an implementation of HTTPS server for ESP32: https://github.com/fhessel/esp32_https_server
Unfortunately, it does not support neither templates nor HTML forms.

**Comment by s00500** [comment]
Any update on this ?
