### ISSUE TITLE
ESP32 .onBody does not fire

### ISSUE THREAD

**Issue by telliottosceola** [me-no-dev/ESPAsyncWebServer#381]
I'll try to put together a stripped down version of the code to repeat my problem but before I do has anyone gotten the .onBody handler for server to fire?  It does not appear to ever work for me.  It's the end of the day but I will post example code to replicate in the morning.

**Comment by salcedo** [comment]
@telliottosceola were you able to figure out what's happening here? WeMoS D1 Mini ESP8266 has the same issue.
