### ISSUE TITLE
Get rid of urldecode

### ISSUE THREAD

**Issue by andig** [me-no-dev/ESPAsyncWebServer#39]
With https://github.com/esp8266/Arduino/commit/35fd2ccd52de7d6a8076ad2eea05bf87a804e6d1 it should be possible to use the static function of the sync web server?

**Comment by me-no-dev** [comment]
I don't think it's a good idea to hook to the regular server at all :) why should we do it for one method? If the method was exposed like digitalRead directly from the framework, then yes, but no when it's on another web server (that might get replaced anyway)

**Comment by andig** [comment]
It just got exposed so likely wont go away soon. But you're right. Would it make sense though to add en urlencode which people would very likely need?

**Comment by me-no-dev** [comment]
If you ask me, urlEncode/Decode should get exposed like the rest of the low level functions of arduino and be used by all equally :) but yeah, we will need it for when I start on the AsyncHTTP/WS Client

**Comment by andig** [comment]
:+1: much appreciated. Closing for now.
