### ISSUE TITLE
'AcSSlFileHandler' has not been declared

### ISSUE THREAD

**Issue by squonk11** [me-no-dev/ESPAsyncWebServer#401]
I am trying to activate SSL on the ESPAsyncWebServer. For this I set ASYNC_TCP_SSL_ENABLED=1. After that I get 
`/msys32/opt/devel/AsyncWebServer/components/AsyncWebServer/ESPAsyncWebServer.h:398:27: error: 'AcSSlFileHandler' has not been declared
     void onSslFileRequest(AcSSlFileHandler cb, void* arg);`
I can not find the referenced function "AcSSlFileHandler" - neither in the sources of ESPAsyncWebServer nor in the sources of AsyncTCP. Do you have a hint for me?

P.S.: I need to add that I am using ESP32 and so I included "AsyncTCP" instead of ESPAsyncTCP. The sources of ESPAsyncTCP include a definition of the function AcSSlFileHandler whereas AsyncTCP doesn't.

**Comment by me21** [comment]
ESPAsyncWebServer doesn't support HTTPS on ESP32 (yet).

**Comment by ViniP8** [comment]
Any news about the HTTPS support on ESP32?

**Comment by me21** [comment]
Please keep it open until it's resolved or decided that it won't be fixed.
