### ISSUE TITLE
Logout without using request->requestAuthentication();

### ISSUE THREAD

**Issue by cfmjk** [me-no-dev/ESPAsyncWebServer#403]
Is there an option to log out an auth user without asking for new login?
e.g. click on sign out -> get a login out page "you are successfully logged out... button sign in"

**Comment by gjt211** [comment]
I would be interested in this too.

**Comment by rtek1000** [comment]
Works well with ESP32 [requestAuthentication()] with the hyperlink inside the HTML code:

`<a href="javascript:window.location=window.location.href.replace(/:\/\//, '://log:out@');">Logout</a>`

Ref.: https://stackoverflow.com/questions/233507/how-to-log-out-user-from-web-site-using-basic-authentication
