### ISSUE TITLE
class AsyncWebServer' has no member named 'setAuthentication'

### ISSUE THREAD

**Issue by michelep** [me-no-dev/ESPAsyncWebServer#413]
As titled, i got an error while using setAuthentication on "server" :

AsyncWebServer server(80);
[....]
 server.serveStatic("/", SPIFFS, "/").setDefaultFile("index.html").setTemplateProcessor(templateProcessor);
  
  // If present, set authentication
  if(strlen(config.www_username) > 0) {
    server.setAuthentication(config.www_username, config.www_password);
  }

error: 'class AsyncWebServer' has no member named 'setAuthentication'
     server.setAuthentication(config.www_username, config.www_password);

**Comment by GeorgeFlorian** [comment]
Hello !
Did you manage to fix it ?

**Comment by Uinden** [comment]
Solution is here https://github.com/me-no-dev/ESPAsyncWebServer/issues/991#issuecomment-1434751178
