### ISSUE TITLE
send response 

### ISSUE THREAD

**Issue by sprokkie** [me-no-dev/ESPAsyncWebServer#426]
Hi,

i am strugling to send a response asfter a http post command.
the post command works fine, if i post relay/toggle the relay toggles.

now i want the actual status of that relay send as the response back to the sender of the post command.
tried a lot but could not find the right way.

response = digitalRead(relayPin)

server.on("/relay/toggle", HTTP_POST, [](AsyncWebServerRequest *request){
   digitalWrite(relayPin, !digitalRead(relayPin));
   request->send(200, "text/plain","{\"relay\": \"on\"}");

this is the code i have now that works only the repsonse is always teh relay is on 
where its says on there should be the status of the relaypin

**Comment by CelliesProjects** [comment]
This is how I would do it:
````
server.on("/relay/toggle", HTTP_POST, [](AsyncWebServerRequest *request)
{
  AsyncResponseStream *response;
  response = request->beginResponseStream( "text/plain" );
  bool newState = !digitalRead(relayPin);
  digitalWrite(relayPin, newState);
  response->printf( "{\"relay\" : \"%s\"}", newState ? "on" : "off" );
  request->send( response );
});
````
