### ISSUE TITLE
Problem with ESP32 reboot 

### ISSUE THREAD

**Issue by spencer1979** [me-no-dev/ESPAsyncWebServer#427]
How can i fix this esp32 reboot 

CORRUPT HEAP: Bad head at 0x3ffbdc18. Expected 0xabba1234 got 0x3ffbdd1c
assertion "head != NULL" failed: file "/Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/heap/multi_heap_poisoning.c", line 205, function: multi_heap_free
abort() was called at PC 0x400e2bd3 on core 0

Backtrace: 0x4008ffb0:0x3ffb69d0 0x400901b3:0x3ffb69f0 0x400e2bd3:0x3ffb6a10 0x4008fc7d:0x3ffb6a40 0x4008500e:0x3ffb6a60 0x400871d5:0x3ffb6a80 0x4000bec7:0x3ffb6aa0 0x401031f6:0x3ffb6ac0 0x401032be:0x3ffb6ae0 0x4012f11d:0x3ffb6b00 0x400ffdb5:0x3ffb6b20

Rebooting...
ets Jun  8 2016 00:22:57

**Comment by me21** [comment]
Please decode the stack trace.
