### ISSUE TITLE
ESP32 - Bind error:67 Ethernet wiznet5500 

### ISSUE THREAD

**Issue by johnnytolengo** [me-no-dev/ESPAsyncWebServer#428]
Hi, I have an issue to make it work with ethernet Module W5500 using Ethernet2.h arduino library.
My board is a ESP32 conected via SPI to the W5500. By the way the W5500 is fully working and connected to my network.

With wifi connection everything work.
The error I am getting:
[AsyncTCP.cpp:1107] begin(): bind error: 67

I really don't know what that "67" means.
Any idea?
Regards.

**Comment by liamcharmer** [comment]
@johnnytolengo did you ever get this working at all?
