### ISSUE TITLE
Stop / Start question

### ISSUE THREAD

**Issue by MartinDavidWaller** [me-no-dev/ESPAsyncWebServer#433]
Hi,

I have a project where I want to use the ESP32 as an access point and have the user enter Wi-Fi connection details via some HTML pages served up using your server. Once I have these details I plan to close the access point and connect directly to the users Wi-Fi where again I'd like to server up different HTML files.

I was wondering what is the best way of stopping / restarting the server while changing operating modes?

Many thanks

Martin

**Comment by StarsoftAnalysis** [comment]
I've done something similar, and didn't need to restart the server when switching the WiFi between STA and AP modes.

[The documentation](https://github.com/me-no-dev/ESPAsyncWebServer#using-filters) shows how to serve different pages in the different modes.

**Comment by MartinDavidWaller** [comment]
Excellent new. Many thanks for commenting.
