### ISSUE TITLE
ESP32 WiFi.setSleep(false)

### ISSUE THREAD

**Issue by apreb** [me-no-dev/ESPAsyncWebServer#437]
Hi, just a quick question

I've tested mostly all webserver examples, sync and async and i coudn't get any example working reasonably at first attempt. It seem that in STA wifi goes to sleep and hangs incoming connections and this is simply not acceptable if the objective is to run a server on the esp32.

setting WiFi.setSleep(false) solves this.

On the other hand, i find strange that there is no mention of this behavior here, is there any other way i am missing to work with webserver on the esp32 and leave the sleeping features as default?

**Comment by tve** [comment]
I haven't seen the problems you describe. Have you tried a different access point?

**Comment by apreb** [comment]
You are absolutely correct, i've tried your suggestion and been testing esp32 against different routers. I've found that this happens only using a linksys EA3500/openwrt. It works flawless with very fast RTT when i setSleep(false) but is gets lots of dropped and delayed packets when not.

The other 2 routers work fine either way, with a noticeable RTT increase when setSleeep is true, from 7-9ms to 40-70ms. This proves that there's nothing wrong with webserver implementation and specifically with this great library.

**Comment by tve** [comment]
Good! (Or no good for that linksys...) The sleep stuff relies on Wifi "Power Save Mode" which usually is found in the form of a "DTIM interval" setting. You may want to look whether that's disabled. A typical value is to set DTIM=3, and yes, you would expect longer latencies because the esp32 turns the radio off between beacons.

**Comment by apreb** [comment]
root@OpenWrt-EA3500:~# iw wlan0 get power_save
Power save: off

root@OpenWrt-EA3500:~# iw wlan0 set power_save on
command failed: Not supported (-95)

No hope for this router.

**Comment by mcuadros** [comment]
I am experiencing similar problems with a ESP32 and in my case a EA6300, what is driving me crazy. 
https://github.com/espressif/arduino-esp32/issues/3157
