### ISSUE TITLE
Websocket - Random client disconnects

### ISSUE THREAD

**Issue by sammyt291** [me-no-dev/ESPAsyncWebServer#442]
Hello,

I am loving the functionality of this library as a whole and making quite a few projects with it currently.

However im having clients randomly disconnect and im unsure why,
When capturing this event with wireshark I see the ESP32 running the socket server sends the client a TCP packet with the fin flag set.
This happens at a random time, generally over 300+ seconds.

Am i missing some sort of max connection time flag/function?

**Comment by tve** [comment]
Does the esp32's LwIP have an idle connection time-out like the esp8266?
Maybe posting the actual wireshark capture would help diagnose the issue?
