### ISSUE TITLE
A simple clarification

### ISSUE THREAD

**Issue by mm108** [me-no-dev/ESPAsyncWebServer#448]
Thanks for the wonderful library - it's something I have started using everywhere where I need a web server. I have a tiny doubt because the documentation mentions something about "compatibility" but "compatibility" to/with what? That wasn't really explained. 

I am trying to look for the existence of a header in a HTTP request and read it's value if it is available. I came across the below 2 snippets to just do that. 

What does "//get specific header by name (**_Compatibility_**)" mean in the 2nd method?
```
//get specific header by name
if(request->hasHeader("MyHeader")){
  AsyncWebHeader* h = request->getHeader("MyHeader");
  Serial.printf("MyHeader: %s\n", h->value().c_str());
}

//get specific header by name (Compatibility)
if(request->hasHeader("MyHeader")){
  Serial.printf("MyHeader: %s\n", request->header("MyHeader").c_str());
}
```

Both seem to work fine but I am rolling out a production sample and thought I'd clarify. All my devices are ESP32 ( doesn't need to have any compatibility with ESP8266 ). Is one of these better than the other?

And thanks once again for the excellent library. The documentation is comprehensive too but I am sometimes I get a little paranoid about using a function or a feature that I am not clear about.

**Comment by fdistorted** [comment]
If you look into the library code you can see that `header(String name)` method uses `getHeader(String name)` inside and returns value of `SharedEmptyString` variable if there is no header with this name.
```
const String& AsyncWebServerRequest::header(const char* name) const {
  AsyncWebHeader* h = getHeader(String(name));
  return h ? h->value() : SharedEmptyString;
}
```
