### ISSUE TITLE
Ethernet enc28j60 Support

### ISSUE THREAD

**Issue by vslinuxdotnet** [me-no-dev/ESPAsyncWebServer#454]
Hi,
This is not a issue, its possible a feature.
I try to use a enc28j60 module, but the ESPAsyncWebServer don't bind on that interface, is possible to change the bind IP from WI-FI to the one of the Ethernet module ? 
Thank you.

**Comment by liamcharmer** [comment]
@vslinuxdotnet Did you ever get this to work or have a chance to find another library that supports it?
