### ISSUE TITLE
When using OTA Update @ ESP32

### ISSUE THREAD

**Issue by ledsi** [me-no-dev/ESPAsyncWebServer#455]
Hi, today i rewrote one of my ESP8266 projects to use with ESP32.
After a few complications and errors its just working fine and the update was less pain then i thought.

But... i had to skip my OTA Update because it came up with an error.
Is there any other way to use OTA on ESP32?
My sketch ist just working fine on ESP8266 and the update progress is the same like here in code examples.

I get these errors:
```
error: 'Update' was not declared in this scope
Update.runAsync(true);
error: 'class EspClass' has no member named 'getFreeSketchSpace'
```
  
  
sketch demo:
```
server.on("/update", HTTP_POST, [](AsyncWebServerRequest *request){
// Config
	Config& config = Config::getInstance();
	// update
	config.shouldReboot = !Update.hasError();
	AsyncWebServerResponse *response = request->beginResponse(200, "text/plain", config.shouldReboot?"OK":"FAIL");
		response->addHeader("Connection", "close");
		request->send(response);
	},[](AsyncWebServerRequest *request, String filename, size_t index, uint8_t *data, size_t len, bool final){

	// !index
	if(!index){
		Serial.printf("Update Start: %s\n", filename.c_str());
		Update.runAsync(true);
		if(!Update.begin((ESP.getFreeSketchSpace() - 0x1000) & 0xFFFFF000)){
			Update.printError(Serial);
		}
	}

	// error
	if(!Update.hasError()){
		if(Update.write(data, len) != len){
			Update.printError(Serial);
		}
	}

	// final
	if(final){
		if(Update.end(true)){
			Serial.printf("Update Success: %uB\n", index+len);
		} else {
			Update.printError(Serial);
		}
	}
	
});
```

**Comment by atanisoft** [comment]
or even: https://github.com/espressif/arduino-esp32/blob/master/libraries/ArduinoOTA/examples/OTAWebUpdater/OTAWebUpdater.ino#L138

which does what you are trying to do...

**Comment by lbernstone** [comment]
You can just remark the offending lines, which are ESP8266 specific.  ESP32 is natively async.

**Comment by ledsi** [comment]
Thanks for your reply.

Now i just got it work, removing the lines
`Update.runAsync(true);`
and 
`(ESP.getFreeSketchSpace() - 0x1000) & 0xFFFFF000)`

But i think, without checking free sketch space it might crash if my file is to big or?

**Comment by zuqualla** [comment]
> You aren't including the Update module in your code and with the ESP32 there is need to pass parameters to Update.begin(), you can see an example here that will work with a few tweaks for ESPAsync: https://github.com/espressif/arduino-esp32/blob/master/libraries/WebServer/examples/WebUpdate/WebUpdate.ino

Did you make a typo and  mean there is **no** need to pass arguments? cause the exemple you refer to has no arguments for  Update.begin() ...?

**Comment by atanisoft** [comment]
@zuqualla most likely yes
