### ISSUE TITLE
[Question] Serving large, runtime generated, JSON to client

### ISSUE THREAD

**Issue by Menion2k** [me-no-dev/ESPAsyncWebServer#456]
Hello
I have a problem in figuring out the best way to send back to the client a big, **runtime** generated, JSON to the connected client.
Before using AsyncWebServer, I was using ESP8266Webserver.
With this library the problem had a very simple solution, it was enough to set contentLength to unknown, start the response with send_P and then loop with sendContentP with just the data fragments and end with a black line.
I am aware that in AsyncWebServer, this can replicated with Chunked Response, but I don't know how fit it with the fact that the JSON is runtime generated.
Chunked Response relay on index parameter to point to the next data fragment. This works ok if the data to be sent is stored somewhere (PROGMEN, or something else) but doesn't work in a simple way when the data is runtime generated.
Example, suppose that I want to send this JSON (in the example it is small just for the sack of simplicity)

```
[
    {
        "CH": "1",
        "PWM": "40"
    },
    {
        "CH": "2",
        "PWM": "20"
    }
]
``` 

Suppose that with a state machine I want to send&forget the JSON in these chunks:

fragment 1
`[
`    
fragment 2
```
    {
        "CH": "1",
        "PWM": "40"
    },

```
fragment 3
```
    {
        "CH": "2",
        "PWM": "20"
    }

```
fragment 4
`]
`

You can see that if I use chunked response any time I get into the chunk callback with just the indication of index (meaning how much data has been already sent) it gets crazy to understand where in the fragment state machine I was....
Is there any simpler solution I cannot see?
Thanks, bye

**Comment by fdistorted** [comment]
Did you tried to do something like this:
```
    AsyncResponseStream *response = request->beginResponseStream("application/json");
   
    response->print("[");


    request->send(response);
```
