### ISSUE TITLE
Add in Arduino Library Manager

### ISSUE THREAD

**Issue by ayushsharma82** [me-no-dev/ESPAsyncWebServer#468]
Hi,
Please create a release in github so that arduino library manager can pickup the library in it's Database. It's essential for setting up Travis CI for repositories where ESPAsyncWebServer is a dependency. In Travis CI dependencies are installed by calling arduino library manager shell script.

Reference: https://github.com/arduino/Arduino/blob/master/build/shared/manpage.adoc

**Comment by per1234** [comment]
There is a new incarnation of the request at https://github.com/me-no-dev/ESPAsyncWebServer/issues/1433
