### ISSUE TITLE
how to send multiple PROGMEM chars in one response

### ISSUE THREAD

**Issue by mamama1** [me-no-dev/ESPAsyncWebServer#473]
Hi

I'd rather write one fat js client and do everything via websockets but for that, I'll first have to learn that stuff (i will, eventually).

For now, I have to get this finished and reuse some old code, where I was sending multiple const char BLAH[xyz] PROGMEM variables and some buffers with dynamic content in one response to the client.

like:
```
Webserver.sendContent_P(html_top);
Webserver.sendContent_P(html_config1);
Webserver.sendContent(jsBuf);
Webserver.sendContent_P(html_jsConfig);
Webserver.sendContent_P(html_bottom);
```

How can I do that with ESPAsyncWebServer?
I tried it with:
```
response->printf_P(html_top);
response->printf_P(html_config1);
response->print(jsBuf);
response->printf_P(html_jsConfig);
response->printf_P(html_bottom);
```

and it works but your manual says not to use this method if going above 4k (i have about 6k here). the info about the 4k comes from the json response part but that uses the request->beginResponseStream function as well, so I think this will apply to printf-ing as well.

one way i can imagine would be to send the response using callbacks and using the index to tell in which of the PROGMEM variables I am currently in but that seems kind of dirty to me.

any suggestions, apart from doing this the proper way using a JS client and websockets?

Thanks!

**Comment by MarkusNaeher** [comment]
Hi

I just had the same problem, and found the solution here:
[Serving large, runtime generated, JSON to client](https://github.com/me-no-dev/ESPAsyncWebServer/issues/456). Adapted to your question, it should look like:

    AsyncResponseStream *response = request->beginResponseStream("application/json");
   
    response->print(html_top);
    response->print(html_config1);
    response->print(jsBuf);
    response->print(html_jsConfig);
    response->print(html_bottom);

    request->send(response);
