### ISSUE TITLE
last five travis checks crashed

### ISSUE THREAD

**Issue by wkraft-fablabka** [me-no-dev/ESPAsyncWebServer#481]
After my pull-request resulted in a travis failure, I checked the results and found, that the last 5 travis checks crashed not because of broken code, but because travis seems to have a problem:

Pull Requests #474, #478, #446, #462, #465 have all the same errors:
```
The command "/sbin/start-stop-daemon ... exited with 2
/sbin/start-stop-daemon: unable to stat /usr/bin/Xvfb (No such file or directory)
```
Does anybody know, whats going on here?

**Comment by baggior** [comment]
I've fixed in my pull request #491

Waiting for @me-no-dev to merge
