### ISSUE TITLE
Need an example of TCP Client + WiFiManager(@tzapu)

### ISSUE THREAD

**Issue by ahmadmn** [me-no-dev/ESPAsyncWebServer#49]
Hi
Thanks for your fastest ESP lib.
I'm new in ESP8266 and need a TCP Client example with Async capability same as your server example:
https://gist.github.com/me-no-dev/116e417ea6a3bbc98b08

if you have an example, can I mix WiFiManager(@tzapu) with it?

**Comment by alanswx** [comment]
Here is a first version of this - it needs some work still:
https://github.com/alanswx/ESPAsyncWiFiManager
Also it should have a non-modal mode.

**Comment by ahmadmn** [comment]
Thanks Alan,
I am testing it,
Regards.

**Comment by gnkarn** [comment]
could you please comment if wifi manager works with this version on asyncmode? , thank you

**Comment by Juntendo11** [comment]
I used it to upload the data from MPU6050 to asynch web server and worked like a charm cheers!
