### ISSUE TITLE
Automatic Connection to IP and run index.html from SPIFFS

### ISSUE THREAD

**Issue by williamesp2015** [me-no-dev/ESPAsyncWebServer#496]
I am Interested to load index.html once AP started on ESP32 without typing IP like Airports once you connect to SSID phone redirected top a webpage (not like Autoconnect to WifiManager). mDNS is not supported by all the browser so it would be convenient to have an AsyncWebserver with Automatic loader.

**Comment by GeorgeFlorian** [comment]
I would love a solution to this.

**Comment by williamesp2015** [comment]
I found Captive Portal but without connection to the Internet is able to redirects to a page or IP
