### ISSUE TITLE
Question:  How to make an OTA firmware update , using your ASYNC libraries ( not via arduino IDE) ?

### ISSUE THREAD

**Issue by gnkarn** [me-no-dev/ESPAsyncWebServer#497]
for ESP8266 . i was looking for an example on how to insert firmware OTA update , as part of the rest of  the code  , using your async version and an async web server to interact by using a simple web page served by the Esp ( not using arduino IDE), but couldn't find an example , all i found were with the non async libraries or using the arduino IDE .

Appreciate , if you have a link of an example at hand .

thanks

**Comment by lbernstone** [comment]
Written for ESP32, but should work on ESP8266 (may need minor change to begin command).  https://github.com/lbernstone/asyncUpdate

**Comment by dushyantahuja** [comment]
+lbernstone - love your functions - unfortunately, I'm running into a small issue - can you please check. 

https://github.com/lbernstone/asyncUpdate/issues/3

> Written for ESP32, but should work on ESP8266 (may need minor change to begin command). https://github.com/lbernstone/asyncUpdate

**Comment by chess-levin** [comment]
Could anyone provide a working example how to integrate OTA with an Upload HTML-form on an AsyncWebServer ?

**Comment by HHavendano** [comment]
> Escrito para ESP32, pero debería funcionar en ESP8266 (puede necesitar un cambio menor para comenzar el comando). https://github.com/lbernstone/asyncUpdate

Hi, i tried the code ,and it's working. but i wonder if i can change the HTML ("void handleUpdate"). i don´t wanna create the HTML on the code. i wanna add an existing website where it will work the same.
