### ISSUE TITLE
is this project still mantained?

### ISSUE THREAD

**Issue by baggior** [me-no-dev/ESPAsyncWebServer#498]

**Comment by baggior** [comment]
no pull requests merge .. no fix commits

**Comment by GeorgeFlorian** [comment]
Doesn't seem like it.

**Comment by baggior** [comment]
how to continue this library development then?
Is there a way on Github to follow and take the ownership?

**Comment by GeorgeFlorian** [comment]
> how to continue this library development then?
> Is there a way on Github to follow and take the ownership?

Don't ask me ! @me-no-dev is a great dev, I really think that he has no time to look after this library. And that's too bad, because it's a great library and I rely heavily on it.
