### ISSUE TITLE
Can I handle `ERR_ADDRESS_UNREACHABLE` ?

### ISSUE THREAD

**Issue by GeorgeFlorian** [me-no-dev/ESPAsyncWebServer#515]
Hello @me-no-dev  !

Can I handle `ERR_ADDRESS_UNREACHABLE` ?

The server becomes unreachable sometimes, without crashing the ESP, meaning that `void loop()` works.
When that happens the only option I have is to press on EN button to reset the ESP.

**I am not asking how to prevent this, I am asking if there's a method of handling that.**

Thank you !

**Comment by me-no-dev** [comment]
ESP32? I've been thinking of adding a watchdog to the server thread... why not.... that is AsyncTCP thing though. Not web :)
