### ISSUE TITLE
How to parse json ?

### ISSUE THREAD

**Issue by kbssa** [me-no-dev/ESPAsyncWebServer#517]
I am trying to parse json with the code below, but always get deserializeJson() failed: InvalidInput.

```cpp
	server.on("/post", HTTP_POST, [](AsyncWebServerRequest *request) {
		//nothing and dont remove it
	}, NULL, [](AsyncWebServerRequest *request, uint8_t *data, size_t len, size_t index, size_t total) {
		StaticJsonDocument<200> root;
		//JsonObject& root = jsonBuffer.parseObject((const char*)data);

		DeserializationError error = deserializeJson(root,(const char*)data);

		if (error) {
			Serial.print(F("deserializeJson() failed: "));
			Serial.println(error.c_str());
			request->send(404, "text/plain", "ERROR");
		}
		else {
			
			if (root.containsKey("tipo")) {
				Serial.println("teste");
			}
			if (root.containsKey("nomeWiFi")) {
				Serial.println("teste2");
			}
			request->send(200, "text/plain", "OK");
		}

	});
```

I am sending {tipo:master,nomewifi:redeteste}

Sorry about my poor english.

**Comment by me-no-dev** [comment]
data on it's own is not a string. it's an array of bytes and as such is not terminated by 0. I will guess that the serialiser overflows the packet (you did not pass length to the function so it will not know where to stop). You either need to copy the data to a new buffer that is at least a byte larger than the data and add a 0 at the end, or use method that allows you to specify length of the input data.
