### ISSUE TITLE
ESP32 reset on ChunkedResponse

### ISSUE THREAD

**Issue by barbiani** [me-no-dev/ESPAsyncWebServer#522]
Hello everybody,
I am running the async webserver on a m5 stack core. Making it stream data to chrome (for now it is only a test).

What I do is to make it stream the send buffer like it is always fully filled. It crashes when I cancel the download in chrome.

I am not sure about what to do. Is someone else seeing the same?

```
  server.on("/", HTTP_GET, [](AsyncWebServerRequest * request) {
    String len = String("");
    Serial.print("HTTP / request");
    if (request->hasArg("start")) {
      len = request->arg("start");
      Serial.print("Arg len found = ");
      Serial.println(len);
    }
    AsyncWebServerResponse *response =
      request->beginChunkedResponse("text/plain", [](uint8_t *buffer, size_t maxLen, size_t index) -> size_t {
      return My.Read(buffer, maxLen);
    });
    response->addHeader("Server", "ESP Async Web Server");
    request->send(response);
  });


int My::Read(uint8_t *buffer, size_t maxLen)
{
return (maxLen);
}
```

> 04:50:58.940 -> M5Stack initializing...OK
> 04:50:59.835 -> AP IP address: 192.168.4.1
> 04:51:00.155 -> Card Mount Failed
> 04:51:59.947 -> HTTP / requestArg len found = 6
> 04:52:09.448 -> assertion "head != NULL" failed: file "/Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/heap/multi_heap_poisoning.c", line 214, function: multi_heap_free
> 04:52:09.448 -> 
> 04:52:09.448 -> Backtrace: 0x4008ca20:0x3ffb3d80 0x4008cc51:0x3ffb3da0 0x400ef7cb:0x3ffb3dc0 0x4008c695:0x3ffb3df0 0x400850c2:0x3ffb3e10 0x4008648d:0x3ffb3e30 0x4000bec7:0x3ffb3e50 0x401097c7:0x3ffb3e70 0x40109827:0x3ffb3e90 0x4010986f:0x3ffb3eb0 0x4010bf62:0x3ffb3ed0 0x4010bfca:0x3ffb3ef0 0x400d6aed:0x3ffb3f10 0x40108d28:0x3ffb3f30 0x400889bd:0x3ffb3f60
> 04:52:09.448 -> 
> 04:52:09.448 -> Rebooting...
> 04:52:09.482 -> ets Jun  8 2016 00:22:57
> 04:52:09.482 -> 
> 04:52:09.482 -> rst:0xc (SW_CPU_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
> 04:52:09.482 -> configsip: 0, SPIWP:0xee
> 04:52:09.482 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> 04:52:09.482 -> mode:DIO, clock div:1
> 04:52:09.482 -> load:0x3fff0018,len:4
> 04:52:09.482 -> load:0x3fff001c,len:1100
> 04:52:09.482 -> load:0x40078000,len:9232
> 04:52:09.482 -> load:0x40080400,len:6400
> 04:52:09.482 -> entry 0x400806a8
> 04:52:09.805 -> M5Stack initializing...OK
> 04:52:10.596 -> AP IP address: 192.168.4.1
> 04:52:10.876 -> Card Mount Failed

**Comment by me-no-dev** [comment]
please update both the web server and AsyncTCP and try again. Fix has been added yesterday :)
