### ISSUE TITLE
AsyncWebserver and Captive Portal for ESP32

### ISSUE THREAD

**Issue by williamesp2015** [me-no-dev/ESPAsyncWebServer#525]
I would be grateful if this example add for ESP32 to have captive portal similar to this example
https://github.com/espressif/arduino-esp32/blob/master/libraries/DNSServer/examples/CaptivePortal/CaptivePortal.ino****

So far captive portal works if Internet is not connected but in most of cases using phone or PC is connected to Internet and it is cumbersome for user to follow our instructions. 
We need to simply run welcome HTML once connect to AP with no hassle.

Thank you

**Comment by me-no-dev** [comment]
like this one? https://github.com/me-no-dev/ESPAsyncWebServer/blob/master/examples/CaptivePortal/CaptivePortal.ino :)
