### ISSUE TITLE
What can I do with this ? [W][AsyncTCP.cpp:902] _poll(): rx timeout 4

### ISSUE THREAD

**Issue by GeorgeFlorian** [me-no-dev/ESPAsyncWebServer#534]
Hello !

Following the new updates and commits made by @me-no-dev I've updated all of my projects to include the newest version of this library.

I can see some improvements. 
What I can also see is the following warning `[W][AsyncTCP.cpp:902] _poll(): rx timeout 4` whenever the server slows down.

I also get another warning when the server isn't responding: `[W][AsyncTCP.cpp:882] _poll(): pcb is NULL`

I don't really understand what these do, but it seems it keeps the server from crashing.

Can I get some explanation regarding the warnings ? Thank you !

**Comment by me-no-dev** [comment]
I have found that some computers/browsers seem to cause LwIP to emit a new connect event, but the connection is never actually completed. The warning you get is a result of the AsyncTCP timing out waiting this connection to happen and is clearing it up.

**Comment by GeorgeFlorian** [comment]
> I have found that some computers/browsers seem to cause LwIP to emit a new connect event, but the connection is never actually completed. The warning you get is a result of the AsyncTCP timing out waiting this connection to happen and is clearing it up.

Great ! Thanks !

**Comment by GeorgeFlorian** [comment]
What about: `[W][AsyncTCP.cpp:882] _poll(): pcb is NULL` ?

**Comment by me-no-dev** [comment]
it is there temporarily to show places where the heap would have been corrupted before

**Comment by GeorgeFlorian** [comment]
> it is there temporarily to show places where the heap would have been corrupted before

Ok. Great ! I get a lot of those. And in return, the server isn't crashing.

**Comment by me-no-dev** [comment]
that is the point :) I will remove the debug later on, but for now it's a good indication of what is going on.

**Comment by virat92** [comment]
i am getting same warning [W][AsyncTCP.cpp:913] _poll(): rx timeout 4 
after getting this warnings my Webserver Disconnect with browser especially when i update my firmware from browser(chrome ). and i have to restart my ESP manually.
can you please tell me the solution
