### ISSUE TITLE
Problems with .on() handler subsystem serving from SPIFFS 

### ISSUE THREAD

**Issue by jake-code** [me-no-dev/ESPAsyncWebServer#549]
Hello, I have been working with the ESP8266 for some time and started out using the default ESPWebServer. I already also built a server using ESPAsyncTCP and have (I think) a fair understanding of sync vs. async.
Now I started to convert one of my existing and tested ESPWebServer projects (been running almost a year non-stop unless I reboot it myself) to ESPAsyncWebServer. This project serves content from SPIFFS, which includes html, css and javascript files.
The changes involved in the code conversion to use ESPAsyncWebServer are (or should be) pretty straightforward so this (I believe) is not the issue.
What is happening is that the ESPAsyncWebServer seems to have some internal problem as, depending on how the SPIFFS files are served it either:

- works (if using or .serveStatic with .setCacheControlmax-age=xx)
- does not work and eventually crashes the ESP8266 (if using .serveStatic but without .setCacheControl(max-age=xx)
- always crashes the ESP8266 (if using .on("url", "HTTP_GET", "handlerFunction")

This is always using the same files and content in SPIFFS and I have used online validators (just to be sure) to verify all HTML, CSS and JS content.

Below I have posted the different calls I have tested (I believe they should all work, please tell me if I am wrong)

WORKS ->  webServer.serveStatic("/", SPIFFS, "/").setDefaultFile("index.html").setCacheControl("max-age=600");
DOES NOT WORK ->  webServer.serveStatic("/", SPIFFS, "/").setDefaultFile("index.html");
DOES NOT WORK (see handleRoot code below) ->  webServer.on("/", HTTP_GET, handleRoot);  

WORKS ->  webServer.serveStatic("/dashboard.html", SPIFFS, "/dashboard.html").setCacheControl("max-age=600");
  
 CATCHALL handler, invoked if specific route handler not defined  (see handleWebRequests code below) -> webServer.onNotFound(handleWebRequests); 

Handler code...

TRIED two versions her, neither works. Does not load all files and crashes ESP.
 void handleRoot(AsyncWebServerRequest *request)
{
  Serial.println("Sending index.html...");

// VERSION 1 this way...
  File fp=SPIFFS.open("/index.html", "r");
  request->send(fp, "/index.html", "text/html");
  fp.close();

// VERSION 2 this way...
 request->send(SPIFFS, "/index.html", "text/html");
}

void handleWebRequests(AsyncWebServerRequest *request)
{
  bool download=false;
  String path=request->url();
  String dataType = String("text/plain");

  Serial.printf("Requested path is: %s\r\n",path.c_str());

  if(path.endsWith("/"))
  {
    path += "index.html";
    dataType="text/html";
  }
  if(path.endsWith(".txt")) dataType = "text/plain";
  else if(path.endsWith(".html")) dataType = "text/html";
  else if(path.endsWith(".htm")) dataType = "text/html";
  else if(path.endsWith(".css")) dataType = "text/css";
  else if(path.endsWith(".js")) dataType = "application/javascript";
  else if(path.endsWith(".png")) dataType = "image/png";
  else if(path.endsWith(".gif")) dataType = "image/gif";
  else if(path.endsWith(".jpg")) dataType = "image/jpeg";
  else if(path.endsWith(".ico")) dataType = "image/x-icon";
  else if(path.endsWith(".xml")) dataType = "text/xml";
  else if(path.endsWith(".pdf")) dataType = "application/pdf";
  else if(path.endsWith(".zip")) dataType = "application/zip";

  if (request->hasArg("download"))
  {
    dataType = "application/octet-stream";
    Serial.println("Download requested");
    download=true;
  }

  if (SPIFFS.exists(path))
  {
    SERIAL.printf("Sending %s, as %s\r\n",path.c_str(),dataType.c_str());
    request->send(SPIFFS, path, dataType, download);
    SERIAL.printf("Sent %s, as %s\r\n",path.c_str(),dataType.c_str());
  }
  else
  {
    String message = "File Not Detected\n\n";
    message += "URI: ";
    message += request->url();
    message += "\nMethod: ";
    message += (request->method() == HTTP_GET)?"GET":"POST";
    message += "\nArguments: ";
    message += request->args();
    message += "\n";
    for (uint8_t i=0; i<request->args(); i++)
    {
      message += " NAME:"+request->argName(i) + "\n VALUE:" + request->arg(i) + "\n";
    }
    request->send(404, "text/plain", message);
    Serial.println(message);
  }
}

Am I doing something wrong or is there really an issue in the library code? My understanding is that I should be able to use any of the calls as indicated above .serveStatic is supposed to be just a "quicker" convenience relative to the standard .on("url", HTTP_GET, handlerFunction()) version.

**Comment by zekageri** [comment]
This is interesting. I'am using it like this:

```
server.on("/jquery-3.3.1.js", HTTP_GET, [](AsyncWebServerRequest* request) {
        AsyncWebServerResponse* response = request->beginResponse(SPIFFS, "/jquery.js.gz", "text/javascript");
        response->addHeader("Content-Encoding", "gzip");
        request->send(response);
    });
```

I have just one problem with it. All my webpages are working this way, (all my files are all compressed to hell, compressed css, js and html files to a compressed one html file wich is gzipped). If iam opening the pages from desktop it is fine, works as espected. But if iam opening the pages from mobile (android) ESP crashes with tcp error. Probably corrupt heap. 

What error do you see on your monitor?Do you have verbose debug mode?

**Comment by Saur0o0n** [comment]
I'm not sure if it helps, but on esp32 I'm using static definitions a lot - and they work
```
// Set default file for programs to index.html - because webserver was programmed by some Windows @%$$# :/
server.serveStatic("/programs/", SPIFFS, "/programs/").setDefaultFile("index.html");
// Serve some static data
server.serveStatic("/icons/", SPIFFS, "/icons/");
server.serveStatic("/js/", SPIFFS, "/js/");
server.serveStatic("/css/", SPIFFS, "/css/");
server.serveStatic("/log/", SPIFFS, "/log/");
server.serveStatic("/favicon.ico", SPIFFS, "/icons/heat.png");
```

**Comment by DmitryBorisenko33** [comment]
[same problem](https://github.com/me-no-dev/ESPAsyncWebServer/issues/637)

**Comment by jake-code** [comment]
Still have the problem but haven't been able to work on it for a while because of other work issues

**Comment by gnalbandian** [comment]
I have a similar problem.
My files are uncompressed yet, and no minimized.
The content of the web page rarely fully downloads. And if it does, there are some garbles in some files.
I believe this issues is related with how the library handles multiple request.
I have my <script> tags at the en of the body of my index.html. When the browser reaches that point it triggers multiple requests to the ESP so as to get the scripts content. There is when everything hungs.
If a remove one script, or shorten the lenght of another, everything goes fine.
How can we solve this?
Is there any way in which we can handle this requests to deliver its content one at a time and not all together?

**Comment by Pablo2048** [comment]
Because of maximum open TCP sockets limitation you have only two option IMHO - concatenate javascripts into one big file (and gzip it) or write your own javascript lazyloader.
