### ISSUE TITLE
Reference to a pointer before checking if it is null

### ISSUE THREAD

**Issue by alf45tar** [me-no-dev/ESPAsyncWebServer#552]
https://github.com/me-no-dev/ESPAsyncWebServer/blob/69865879b4871a86e20e146a9e60db6a545ed2b1/src/WebRequest.cpp#L604

**Comment by philbowles** [comment]
What on earth are you talking about?

**Comment by alf45tar** [comment]
603  char * name = (char*) malloc(n+1);
604  name[n] = 0; 

malloc on line 603 can return a null pointer and then line 604 has an unpredicteable effect.

I think you should use something similar to line 629 if (name) { ... }
