### ISSUE TITLE
[QUESTION] How to serve any files from SPIFFS or SD_MMC?

### ISSUE THREAD

**Issue by nullpoint-dev** [me-no-dev/ESPAsyncWebServer#557]
Yes I can request specific files using this: `request->send(SD_MMC, "/wow.png", "image/png");`
But how can I request any file without making multiple `request->send();`
Is it ok to do this? `request->send(SD_MMC, request->url(), "application/octet-stream");`

**Comment by atanisoft** [comment]
you should look at serveStatic() which can serve files directly from the FS without you needing to specify individual files.
