### ISSUE TITLE
Does specifying content length improve loading time ?

### ISSUE THREAD

**Issue by GeorgeFlorian** [me-no-dev/ESPAsyncWebServer#564]
Hello !

I am curious to know if using: 

```
server.on("/home", HTTP_GET, [](AsyncWebServerRequest* request){
AsyncWebServerResponse *response = request->beginResponse(SPIFFS, "/index.html", "text/html", false, processor);
          File file = SPIFFS.open("/index.html");
          response->addHeader("Content-Length", (String) file.size ());
          request->send(response);
          file.close();
      });
```

instead of: 
```
server.on("/home", HTTP_GET, [](AsyncWebServerRequest* request){
equest->send(SPIFFS, "/index.html", "text/html", false, processor);
});
```

would change anything ?

Right now my pages are quite `heavy` and they take a good 5+ seconds to load, which feels like an eternity.

**Comment by philbowles** [comment]
Short answer: No. The whole point of a lib like AsyncWebserver is that it correctly prepares and sends all those headers for you. Let it do its thing.

If you want to speed up the loading, trim down your web page or minify it etc. Fix the disease, not the appearance of the symptoms.
