### ISSUE TITLE
Web authentication

### ISSUE THREAD

**Issue by amiilto** [me-no-dev/ESPAsyncWebServer#573]
With the WebServer.h library, we can use 

`server.on("/", [](){

    if(!server.authenticate(www_username, www_password))

      return server.requestAuthentication();

    server.send(200, "text/html", serverIndex);

  });`

to create an authentication window on the browser. Is it possible to do something similar with the Async web server?

**Comment by lbernstone** [comment]
https://www.google.com/search?q=espasyncwebserver+authentication

**Comment by philbowles** [comment]
If you want digest auth the code is exactly the same. If you want basic auth - beware, I just raised a bug issue on it
