### ISSUE TITLE
Bug in basic authentication

### ISSUE THREAD

**Issue by philbowles** [me-no-dev/ESPAsyncWebServer#575]
Hardware: all
Firmware: all

IF basic authentication is chosen over digest method in `requestAuthentication` it fails and user is unable to log into browser even though correct credentials are entered.

This is due to a bug in the following code in /WebAuthentication.cpp:
```cpp
bool checkBasicAuthentication(const char * hash, const char * username, const char * password){
  if(username == NULL || password == NULL || hash == NULL)
    return false;

  size_t toencodeLen = strlen(username)+strlen(password)+1;
  size_t encodedLen = base64_encode_expected_len(toencodeLen);
  if(strlen(hash) != encodedLen)
    return false;
...
```
using the example of "admin:admin" whose b64 encoding is YWRtaW46YWRtaW4= we see that it is 16 characters long.

`base64_encode_expected_len` returns the length of the _buffer_ (_not_ the length of the hash!) required to contain a given encoding thus includes and extra trailing byte for the '\0' 

From ...\cores\esp8266\libb64\cencode.h:
```cpp
#define base64_encode_expected_len(n) \
       (base64_encode_expected_len_nonewlines(n) + ((n / ((BASE64_CHARS_PER_LINE * 3) / 4)) + 1))
```

Thus when given "admin:admin" it returns 17, being the (correct) 16 for the hash +1 for the trailing byte.

Hence in the common-sense length check in checkBasicAuthentication above, the line:
`  if(strlen(hash) != encodedLen)` _always_ fails for correct values of username / password.

Changing it to `  if(strlen(hash) != encodedLen - 1)` _always_ succeeds for correct values of username / password.

MCVE:

```cpp
#include <ESP8266WiFi.h>
#include <ESPAsyncWebServer.h>

const char* ssid = "XXXXXXXX";
const char* password = "XXXXXXXX";

AsyncWebServer server(80);

bool _webAuth(AsyncWebServerRequest *request){
    if(!request->authenticate("admin","admin",NULL,false)) {
      request->requestAuthentication(NULL,false); // force basic auth
      return false;
    }
    return true;
}

void setup(void) {
  Serial.begin(74880);
  WiFi.begin(ssid, password);
  WiFi.waitForConnectResult();

  server.on("/",HTTP_GET,[](AsyncWebServerRequest *request){ 
    if(!_webAuth(request)) return;
    request->send(200,"text/plain","hello admin");
  });  
  
  server.begin();
 
}

void loop(void) {}
```

**Comment by Saur0o0n** [comment]
Basic auth works for me "as is" in AsyncWebServer - checked for few different passwords with your "_webAuth" function.
