### ISSUE TITLE
server public and acceessed from everywhere

### ISSUE THREAD

**Issue by ChristosPalisidis** [me-no-dev/ESPAsyncWebServer#593]
Hello,
I create a server giving the oportunity to user to select the wifi connection he prefers. Then, i want to have access to this server but not only from the local network but with a public ip.
Is this possible?I can have both local and public IP's,but can port forwarding be done remotely with no access to the router?
Thank you!

**Comment by zekageri** [comment]
I think the only solution is when you port forwarding your router. It is kind of safe if you have a good router and a good dns provider. Your router is only forwarding the specific IP adress that you define in it. 
Or you could implement husarnet or something like this.

[https://www.hackster.io/donowak/esp32-to-esp32-communication-over-the-internet-9799df](url)
