### ISSUE TITLE
HTTPS with ESP32

### ISSUE THREAD

**Issue by ViniP8** [me-no-dev/ESPAsyncWebServer#597]
Hi!!

I used this library to develop an Access Control System, and now i'm planning to implement HTTPS to improve security(encryption) for file exchange and webpages (after login). 

Is there any "beginSecure()" method for ESP32, or another easy way of doing this without other webserver libraries?

Thank you all for this awesome project!!

**Comment by Bmooij** [comment]
Currently ESPAsyncWebServer on the ESP32 doesn't support HTTPS.
Because the dependency [AsyncTCP](https://github.com/me-no-dev/AsyncTCP) hasn't support for HTTPS (yet)
