### ISSUE TITLE
Standalone AsyncWebSocketClient

### ISSUE THREAD

**Issue by elC0mpa** [me-no-dev/ESPAsyncWebServer#600]
Hello, I just made an AsynWebSocketServer sketch and tested it with a websocketclient. The point is that now i would like to develop an AsynWebSocketClient sketch to improve performance. My problem is that i have been trying but i couldn't find a way to do it. Is it possible to do this with your library? Or i can only do this for a websocketserver? Thanks for your time

**Comment by me-no-dev** [comment]
it is possible. you need to use the underlying AsyncTCP library to make that client. There might already be some work on it on the web :)
