### ISSUE TITLE
AsyncJson Error

### ISSUE THREAD

**Issue by SpectralBolt** [me-no-dev/ESPAsyncWebServer#602]
This is the error that I get when I try to compile the code. I'm using ArduinoJson V6. According to the code compatibility is filtered to V5 and V6, so I'm not sure why I'm getting this error.

![image](https://user-images.githubusercontent.com/37422018/65536752-a2a49a80-dec9-11e9-8e14-739e751c1151.png)

Thanks

**Comment by atanisoft** [comment]
https://github.com/me-no-dev/ESPAsyncWebServer/pull/539

**Comment by SpectralBolt** [comment]
Thanks I didn't see that thread.
