### ISSUE TITLE
serveStatic with gzip just broke, error 500?

### ISSUE THREAD

**Issue by maxdd** [me-no-dev/ESPAsyncWebServer#612]
In an old version (probably first half of september) everything was running fine with

server.serveStatic("/", SPIFFS, "/").setDefaultFile("index.html.gz");

now it doesnt work anymore.

If i type http://url.local/ the index.html.gz gets downloaded
I've also tried server.serveStatic("/", SPIFFS, "/index.html.gz");

If i load the normal html file and use
server.serveStatic("/", SPIFFS, "/").setDefaultFile("index.html");

the page is loaded

**Comment by zekageri** [comment]
Oh, in this case try to use gzipped files like that:

```
server.on("/", HTTP_GET, [](AsyncWebServerRequest *request) {
/** GZIPPED CONTENT ***/
    AsyncWebServerResponse* response = request->beginResponse(SPIFFS, "/Index.html.gz", "text/html");
    response->addHeader("Content-Encoding", "gzip");
    request->send(response);
  });
```
