### ISSUE TITLE
how to convert output of request->getParam("paramname")->value() from string to int

### ISSUE THREAD

**Issue by rishabhrpg** [me-no-dev/ESPAsyncWebServer#618]
I have  been struggling to convert the output of request->getParam("mode")->value(); to integer 
I have tried request->getParam("mode")->value()->toInt(); that causes runtime exceptions and also tried (int) convertions that produce compile time errors, I had to open up an issue as I didn't found any docs on data type conversions.

**Comment by aliyehia92** [comment]
Try putting things on separate lines sometimes this works for me for some reason. 
For example you can do something like:
```
String val = request->getParam("mode")->value();
int int_val = val.toInt();
```
