### ISSUE TITLE
Basic Auth. Different behaviour ESP32 vs. ESP8266

### ISSUE THREAD

**Issue by rickbear** [me-no-dev/ESPAsyncWebServer#632]
I am having an issue with basic auth on ESP8266.

 I've used code for ESP32 handling basic auth:
`if (!request->authenticate(http_username, http_password))
	return request->requestAuthentication();`
Sending a request to the ESP32 like:
user:pass@192.168.1.2
works quite fine testing with postman. It also rejects when user and pass are wrong or not present.

But when using the exact same code for ESP8266 I get a "401 Unauthorized". User and Password are correct. I've tried a lot of different approaches until I was out of options and just fiddled with postman setting to use Digest Auth in postman instead of Basic Auth and suddenly it works!!
It seems like
`if (!request->authenticate(http_username, http_password))
	return request->requestAuthentication();`
defaults to Basic Auth on ESP32 and defaults to Digest Auth on ESP8266. How come?
And how do I force Basic Auth on ESP8266?

**Comment by mexusbg** [comment]
I have the same issue!
