### ISSUE TITLE
AsyncCallbackWebHandler support request for variables in URI

### ISSUE THREAD

**Issue by BlueAndi** [me-no-dev/ESPAsyncWebServer#633]
The webserver of the arduino-esp32 framework supports variables in the URI, e.g.
```
srv.on("/rest/api/v1/display/slot/{}/text", slotText);
```
The registered request handler will received the ```{}``` as an argument.

It would be good to have the same support in the ESPAsyncWebServer as well.

**Comment by Bmooij** [comment]
The AsyncWebserver has already support for variables in the URI.

Check the docs [here](https://github.com/me-no-dev/ESPAsyncWebServer/blob/master/README.md#path-variable)  and for examples [here](https://github.com/me-no-dev/ESPAsyncWebServer/blob/master/examples/regex_patterns/regex_patterns.ino)

**Comment by BlueAndi** [comment]
Introduced in the last version, yes, I saw it. The drawback is the necessary space for regex. Would it be possible without regex as alternative?

**Comment by Bmooij** [comment]
@me-no-dev I would like to add support for this function, without making a mess of it. Can you please give me feedback on my plan?

I would like to proposes an `Uri` object for the uri. 

The usage of the `Uri` object would be as follows:

a static uri
```cpp
srv.on("/a/static/uri", callback);
srv.on(Uri("/an/other/static/uri"), callback);
```

a regex uri
```cpp
srv.on(UriRegex("^\\/an\\/regex\\/uri\\/[0-9]+$"), callback);
```

a bracket uri
```cpp
srv.on(UriBrackets("/an/uri/with/{}/backets"), callback);
```

The `Uri` class will look someting like this:
```cpp
class Uri {
    public:
          virtual bool canHandle(AsyncWebServerRequest *request);
    
    protected:
          void _addPathParam(AsyncWebServerRequest *request, const char* param);
}
```


This implementation will also get rid of the `ASYNCWEBSERVER_REGEX` flag.
By importing `uri/UriRegex.h` automatically 'regex' will be included.

**Comment by BlueAndi** [comment]
@me-no-dev Your answer is missing. Solution would be available, see previous comments.

**Comment by BlueAndi** [comment]
ping ;-)

**Comment by BlueAndi** [comment]
@me-no-dev Please comment.

**Comment by RomeHein** [comment]
This is too bad, because this feature is really missing. atm it's quite difficult to make a restful api. I was looking at the `addRewrite` function, but told myself that it should be included in the library without having to write painful parser or set build flags for regex.

**Comment by BlueAndi** [comment]
Last try, before I give up.
