### ISSUE TITLE
How determine exact size of file sent by curl for updating remote firmware after esp32

### ISSUE THREAD

**Issue by r2d2r01** [me-no-dev/ESPAsyncWebServer#636]
Hi, i work with ESPAsyncWebServer/esp32.
When I launch curl with firmware file size=**1928400** bytes to upload, debug of AsyncWebServerRequest tells traces below. 
My problem is file size provided if **1928605** and it's mandatory to indicates automat the exact size not the length of request. How obtain  this value ? Exist no header or param or args ... 
A solution, read entire file to determine exact size and resend file (oups).
Thank's
Frederic

Start updating: URL=/update File=fw.bin ### ### Size=1928605 bytes Type=multipart/form-data
POST http://192.168.0.150/update
_CONTENT_TYPE: multipart/form-data
_CONTENT_LENGTH: **1928605**
_HEADER[Host]: 192.168.0.150
_HEADER[User-Agent]: curl/7.61.0
_HEADER[Accept]: */*
_HEADER[Content-Length]: 1928605
_HEADER[Content-Type]: multipart/form-data; boundary=------------------------6cd1d40b553e1c7d
_HEADER[Expect]: 100-continue
ARG nb=0

Arch:
------
Linux server.curl ->(wifi) ->  esp32(update firmware)-> (serial) -> automat

**Comment by me-no-dev** [comment]
basically, unless you send that as a parameter to the post, there is no way to know. That POST might contain more than one file and so on.
