### ISSUE TITLE
WebSocket - unidirectional communication causes crash / reproducible always

### ISSUE THREAD

**Issue by fightingdreamer** [me-no-dev/ESPAsyncWebServer#641]
Unidirectional communication causes crash.

Steps to build:
- use [onEvent example](https://github.com/me-no-dev/ESPAsyncWebServer#async-websocket-event)
- remove all `client->text()` and `client->binary()`
- build and upload to esp8266

Steps to reproduce:
- connect to esp8266 ws server
- start sending messages in a fast loop, message size does not matter
- server crash after receiving up to 100 messages

Additional info:
- free heap is stable
- adding 1ms delay between messages (sender side) sometimes causes WS_EVT_ERROR with arg 2240
- adding 10ms delay prevents crash

Some hints where to search for possible causes in ESPAsyncWebServer code base?

**Comment by forkineye** [comment]
Do you have the exception decoder? https://github.com/me-no-dev/EspExceptionDecoder
