### ISSUE TITLE
How to POST username and password 

### ISSUE THREAD

**Issue by williamesp2015** [me-no-dev/ESPAsyncWebServer#643]
After connect to the company SSID and STA password, I am trying to submit username and account password by ESP32 using either Asyncwebserve or http.begin("https://hotspot.mycompany.com/login");
The website doing MD5 encoding using dologin function. I can simply use Internet Explorer to open my account using: 
http://hotspot.mycompany.com/login?username=MINE&password=626273A3b4c688a22bb
How I can simply parse this url?

**Comment by sfranzyshen** [comment]
stale bot is not useful ... it degrades development ... please eliminate this feature from this repository ...

**Comment by sfranzyshen** [comment]
stale bot is not useful ... it degrades development ... please eliminate this feature from this repository ...
