### ISSUE TITLE
Enabling regex causes crash and bootloop

### ISSUE THREAD

**Issue by teemue** [me-no-dev/ESPAsyncWebServer#648]
Using PlatformIO and latest ESPAsyncWebServer. 
Accessing http://ip/hello works but if I access /sensor, ESP crashes and bootloops.

  ```
server.on("/hello", HTTP_GET, [](AsyncWebServerRequest *request) {
    Serial.println("hello");
    request->send(200, "text / plain", "Other URL");
  });

  server.on("^\\/sensor\\/([0-9]+)$", HTTP_GET, [](AsyncWebServerRequest *request) {
    String sensorId = request->pathArg(0);
  });
```

platform.ini:
```
[env:esp01]
platform = espressif8266
board = esp01_1m
framework = arduino
build_flags = 
  -DASYNCWEBSERVER_REGEX
```

**Comment by Bmooij** [comment]
Does it still crash when you add an response to the sensors request?

```
server.on("^\\/sensor\\/([0-9]+)$", HTTP_GET, [](AsyncWebServerRequest *request) {
  String sensorId = request->pathArg(0);
  request->send(200, "text / plain", "sensor: " + sensorId);
});
```

**Comment by teemue** [comment]
It crashes. Here's the full code:
```
#include <ESP8266WiFi.h>
#include <DNSServer.h>
#include <ESPAsyncWebServer.h>
#include <ESPAsyncWiFiManager.h>

AsyncWebServer server(80);
DNSServer dns;
#define HOST_NAME "ESP"

void setup()
{
  Serial.begin(115200,SERIAL_8N1,SERIAL_TX_ONLY);
  AsyncWiFiManager wifiManager(&server, &dns);
  if (!wifiManager.autoConnect())
  {
    ESP.reset();
    delay(1000);
  }

  String hostNameWifi = HOST_NAME;
  hostNameWifi.concat(".local");
  WiFi.hostname(hostNameWifi);

  server.on("/hello", HTTP_GET, [](AsyncWebServerRequest *request) {
    Serial.println("hello");
    request->send(200, "text / plain", "Other URL");
  });

  server.on("^\\/sensor\\/([0-9]+)$", HTTP_GET, [](AsyncWebServerRequest *request) {
    String sensorId = request->pathArg(0);
    request->send(200, "text / plain", "sensor: " + sensorId);
  });

  server.begin();
}

void loop()
{
}
```

**Comment by teemue** [comment]
I tried also without WifiManager (only ESP8266WiFi and  ESPAsyncWebServer included), no effect.

**Comment by niklasdoerfler** [comment]
I can observe the same behaviour. Is there already a solution to the problem?

**Comment by Bmooij** [comment]
There is an issue with regex and the esp8266. 
See: 
https://github.com/esp8266/Arduino/issues/6198 
https://github.com/esp8266/Arduino/issues/6952

There is no fix for now. When I have some time, I will rewrite the regex part and create an new pull request

**Comment by kjyv** [comment]
still an issue, so should be reopened

**Comment by phil31** [comment]
Hello users, 

2023, same problem !
build_flags = 
	-DCORE_DEBUG_LEVEL=5
	; -DASYNCWEBSERVER_REGEX=1

enable the DASYNCWEBSERVER_REGEX flag, then crash on requests !

any suggestion to use regex in url please ?
2023-03-29 : example "regex_patterns.ino" is not working !

thanks

**Comment by flier268** [comment]
still an issue, so should be reopened
