### ISSUE TITLE
Websocket message queue handling

### ISSUE THREAD

**Issue by WonderWhyWilli** [me-no-dev/ESPAsyncWebServer#655]
Hey all,

I have a question on how the websocket server on the ESP32 handels the message queue.

Websocket messages take 3 transmissions to complete a request/receive:
1. Client sends a request
2. Server sends a response and ACK the request
3. Client ACK the response

For testing I send 50 messages per second to the ESP32 per websocket with an ping of 50ms.
I see the messages coming from my webbrowser to the ESP32 with 20ms intervalls (1. transmission), but responding (2. transmission) takes 50ms, so the message queue overflows and messages get deleted.
=> I think the message queue can only send the next message when the ACK of the last message for the same client is received.

Is this a bottleneck of the websocket message queue or of the TCP Stack implementation of the ESP32?
Can it be circumvented?

Thank you very much in advance!

Regards,
WonderWhyWilli

**Comment by sfranzyshen** [comment]
stale bot is not useful ... it degrades development ... please eliminate this feature from this repository ...
