### ISSUE TITLE
Callback context on ESP32?

### ISSUE THREAD

**Issue by ashley-schaeffer** [me-no-dev/ESPAsyncWebServer#657]
I'm running ESPAsyncWebServer on ESP32, with AsyncTCP obviously.
I don't create any FreeRTOS tasks myself so I only have the Arduino loop() checking for some flags. Those flags are set from inside callbacks I passed to the ESPAsyncWebServer and AsyncTCP libraries.

However I only recently took a closer look at the source of the AsyncTCP library and realized a new task is created for calling the user supplied callbacks. Am I right in thinking that I should synchronize access between any variables accessed by both the loop() function and the callbacks (both in ESPAsyncWebServer and AsyncTCP) to prevent possible race conditions?

I'm asking because I haven't really seen this mentioned explicitly somewhere. I'm guessing it's only an "issue" on the ESP32?

**Comment by BlueAndi** [comment]
Yes, you are right. The loop() is running in a task with prio 1 and the ESPAsyncWebserver is running in a separste task with prio 3. This means you have to consider concurreny access.

**Comment by me21** [comment]
...unless variable access is atomic, that is, variable type is primitive (i.e. book, uint32) and both tasks use the same CPU core, if I understand correctly

**Comment by mamama1** [comment]
hi,

this is kinda blowing my mind atm. could someone please be so kind and provide a simple example which demonstrates this issue? I might currently experience it but I'm not sure.

Thanks!
