### ISSUE TITLE
[Partially solved] Chunked Response Callback fails to be called randomly when sending large amount of data.

### ISSUE THREAD

**Issue by umartechboy** [me-no-dev/ESPAsyncWebServer#658]
I have a data file on the SPIFFS which I decode and send over a GET request. The data is decoded and expands almost 10 times in size during the process. So, a file of 40KB size is sent as a stream around 400KB long. 

AsyncWebServerResponse *response = request->beginChunkedResponse("text/html", [](uint8_t *buffer, size_t maxLen, size_t index) -> size_t { return SEND_MY_DATA_CHUNK(maxLen);
}

I read data from file in packets of 18 bytes, imposed by my encoding scheme. Each packet of 18 bytes is decoded (mostly number to string  conversions) to make up to ~180 bytes. Initially, I was writing only these decoded bytes to the lambada callback buffer (the rest of the buffer goes un-occupied). It worked perfectly, except the data rate was miserably low (obviously), around 0.1Mbps.

Then I changed my fill up scheme to use the complete buffer each time my lambada callback is called. So I fill up the buffer up to its maximum capacity (maxLen) and return the bytes written. It works as expected except the call back isn't called sometimes. Also, the ESP watchdog triggers, resting the IC.

Here are some more observations:
1. The issue doesn't occur in the beginning of the file
2. It always occurs after sending 10-14KB of the total data.
3. The maxLen the callback allows me decreases (from the usual 4-6KB) in a couple of iterations to 10-200 bytes; goes up by 1-2KB, never reaching the usual 4-6KB ever.
4. It does work some times if i use too much Serial.print for debugging the issue.
5. Out of the attempts it succeeds, the data rate after all the overheads stays around 0.9-1Mbps.

SOLUTION.
Since the issue started when i tried to fill up the complete buffer. So, I used a middle approach. Even when the buffer allows me more than 4KB, I never fill it up more than 2K and it starts working again. I have also tried with 1K and 3K thresholds as well. 1KB gives me the same 0.1Mbps rate without the watchdog issue ever and 3K craches just like the uncapped case.

**Comment by sfranzyshen** [comment]
stale bot is not useful ... it degrades development ... please eliminate this feature from this repository ...
