### ISSUE TITLE
Streaming a file using its handle

### ISSUE THREAD

**Issue by bot1131357** [me-no-dev/ESPAsyncWebServer#659]
I want to stream files from an SD card. 

Is there a method like `size_t WebServer::streamFile(T &file, const String& contentType)` in the arduino-esp32 library where I could specify the file handle (of type `File` using SdFat 1.1.0 library)? 

Currently I make do with `void AsyncWebServerRequest::sendChunked(const String& contentType, AwsResponseFiller callback, AwsTemplateProcessor templateCallback)`, but there is a lot of manual wrangling of the data buffer, and also global variables. 

```
volatile String logFileName;
volatile bool isLogDownloading{ false };
size_t loadFile(uint8_t* buffer, size_t maxLen, size_t index)
{
	int sz = 0;

	// first call
	if (0 == index)
	{
		isLogDownloading = true;
		// start reading a file
		sz = readToBuffer(logFileName.c_str(), (char*)buffer, maxLen);
	}
	else
	{
		// continues reading, and returns -1 at EOL
		sz = readToBuffer(nullptr, (char*)buffer, maxLen); 
	}
	return (sz > 0) ? sz : 0;
}

void getFile(AsyncWebServerRequest* req)
{
	if (isLogDownloading)
	{
		// return  503, "Server busy. Try again later."
		return;
	}

	// specify filename
	fileName = req->arg("file");

	// specify cleanup when disconnected
	req->onDisconnect([]() {
		isLogDownloading = false;
		});
	AsyncWebServerResponse* res = req->beginChunkedResponse(contenttype[HTML_T],
		[](uint8_t* buffer, size_t maxLen, size_t index) {
			return loadFile(buffer, maxLen, index);
		});	
	res->addHeader("content-disposition", "attachment; filename=\"" + fileName + "\"");
	req->send(res);	
}
```

I'm not sure if this is the best approach. Is there a better method? Any suggestions or pointers would be much appreciated.

**Comment by bot1131357** [comment]
Update: okay... not working so well as it crashes from time to time...

**Comment by Voha888** [comment]
Hello. Does this code work? I used the beta version of SdFat and experimented with downloading large files. It’s best to use a streaming file `(WebServer::streamFile)` , but without handling or callback it has a lot of problems

**Comment by bot1131357** [comment]
I am still looking for more elegant workarounds - as this code is unnecessarily complicated. I'd appreciate some pointers. Anyone?

**Comment by Voha888** [comment]
I will probably use the last example from this topic.: https://github.com/me-no-dev/ESPAsyncWebServer/issues/124

**Comment by Voha888** [comment]
@bot1131357 In your example, does the browser know about the file size?

**Comment by bot1131357** [comment]
@Voha888 sorry didn't see your posts until now. 

Yes, the code does work - but it's something I've hacked up and honestly I don't think that's the best way to implement file download from SD card. 

Also, the example code does not mention file size, but you can change that with `addHeader()` method.

**Comment by bot1131357** [comment]
Personally I would really like to see an ESPAsyncWebServer equivalent of WebServer::streamFile(), so that I can write this:
```
File anyfile = getFileHandle(); // SPIFFS, SDFAT, or any library that implements File interface
req->streamFile(anyfile , "application/zip");
```
Though at this point, I'm just not sure how to approach this...

**Comment by bot1131357** [comment]
Personally I would really like to see an ESPAsyncWebServer equivalent of WebServer::streamFile(), so that I can write this:
```
File anyfile = getFileHandle(); // SPIFFS, SDFAT, or any library that implements File interface
req->streamFile(anyfile , "application/zip");
```
Though at this point, I'm just not sure how to approach this...

**Comment by Voha888** [comment]
I looked at the source of this function, it seemed to me that there it is not difficult to rewrite its work under SdFs (SdFat)

**Comment by bot1131357** [comment]
> I looked at the source of this function, it seemed to me that there it is not difficult to rewrite its work under SdFs (SdFat)

Would you consider doing a pull request?
