### ISSUE TITLE
send_P for unint8_t data should be send?

### ISSUE THREAD

**Issue by penfold42** [me-no-dev/ESPAsyncWebServer#66]
void send_P(int code, String contentType, const uint8_t * content, size_t len);

Should we drop the _P ?

**Comment by me-no-dev** [comment]
no, because this method reads the data from flash and not from memory ;) even though it says const uint8_t * it actually refers to flash (progmem) saved data.

**Comment by penfold42** [comment]
Ok thanks !

Is there a send that will read uint8 from ram ?

I'm building a bitmap on the fly and need to return it.

The printf sample gets close but the NULs will break it

**Comment by ClaudioHutte** [comment]
May this help? https://github.com/me-no-dev/ESPAsyncWebServer#respond-with-content-using-a-callback
