### ISSUE TITLE
Webserver stops working after a few requests

### ISSUE THREAD

**Issue by ViniP8** [me-no-dev/ESPAsyncWebServer#662]
Hi!

From time to time, the server slows down, freezes for a few seconds, or completely stops working until reboot. 

Enabling verbose mode at serial monitor, some warnings show up before the problem happens (not all of them at the same time, sometimes only one of these happens):

`[W][AsyncTCP.cpp:893] _poll(): pcb is NULL`
`[W][AsyncTCP.cpp:913] _poll(): rx timeout 4`
`[W][AsyncTCP.cpp:906] _poll(): ack timeout 4` 

Is there any way to **check** if the webserver has freezed and **restart** only the webserver (without fully rebooting the ESP)?

**Comment by AthusVieira** [comment]
This problem is happening to me as well. One or two connected clients seem to work good, however three or more clients will make the ESP32 reboot. Can this library really handle multiple clients?
