### ISSUE TITLE
Cheat sheet for converting from standard esp web server library. 

### ISSUE THREAD

**Issue by mmiscool** [me-no-dev/ESPAsyncWebServer#67]
I am trying to convert a rather large project from the standard esp web server library to this one.

I was kind of hoping there might be a list of equivalent functions one to the other to make porting easier. 

Things like server->arg("name") in the esp web server library and what there equivalent is in this one.

**Comment by me-no-dev** [comment]
check the readme ;) it has everything documented. Main difference is that those functions are attached to the request object in the callbacks and not on the server. So instead of server.arg("blah") you have request->arg("blah") and so on

**Comment by ClaudioHutte** [comment]
Hello mmiscool, just out of curiosity, why do you move from the standard web server library?
