### ISSUE TITLE
server.removeHandler(new SPIFFSEditor(_username,_password));

### ISSUE THREAD

**Issue by g4m3r-87** [me-no-dev/ESPAsyncWebServer#670]
Hello.

I am using the following code:
```
server.addHandler(new SPIFFSEditor(_username,_password));
server.begin();
```
Everything works well. When calling the HTPP: //ESP_IP/edit page, a login and password are requested.

In the process, I want to change _username, _password. 

I tried to do (with a new username and password):
server.addHandler (new SPIFFSEditor (_username, _password));

However, this does not work.

Next, I tried to do this:
```
server.removeHandler(new SPIFFSEditor(_username,_password));
_username=new_username;
_password=new_password;
server.addHandler (new SPIFFSEditor (_username, _password));
```
That didn't work either.

Please help. How can I change the username and password to access the edit page in the process without restarting ESP8266?

**Comment by BlueAndi** [comment]
You are calling removeHandler() with a new instance of SPIFFSEditor. This won't work. You have to store the added handler (you get it as return value of addHandler) and use this as argument for the removeHandler.

**Comment by g4m3r-87** [comment]
Hello!

I tried like this:

```
   auto handler = server.addHandler(new SPIFFSEditor(_username,_password));
   server.removeHandler(&handler);

 _username=new_username;
 _password=new_password;
 auto handler = server.addHandler (new SPIFFSEditor (_username, _password));
```

does not work

**Comment by BlueAndi** [comment]
Now you copied the handler. ;-)

This should work:
```
AsyncWebHandler* handler = &server.addHandler(new SPIFFSEditor(_username, _password));
server.removeHandler(handler);
```

**Comment by g4m3r-87** [comment]
Thank you!
