### ISSUE TITLE
supporting wild cards in requests

### ISSUE THREAD

**Issue by WattsC-90** [me-no-dev/ESPAsyncWebServer#678]
Is it possible for request patterns to support wildcards? the more files that I add to the project I feel it would be easier to support `/js/*.js` style request pattern and handle which file is actually requested using a `switch case` statement in the method instead.

It does occur to me while writing this, that it may cause extra overhead and may be recommended to do this another way (or to just have every single file listed!).

Any guidance is much appreciated

**Comment by solopix** [comment]
You can use a single command like

    server.serveStatic("/favicon.ico", SPIFFS, "/favicon.ico").setCacheControl("max-age=31536000");
    server.serveStatic("/js/", SPIFFS, "/js/").setCacheControl("max-age=31536000");

or without cache

    server.serveStatic("/favicon.ico", SPIFFS, "/favicon.ico");
    server.serveStatic("/js/", SPIFFS, "/js/");

**Comment by WattsC-90** [comment]
I have been looking at these as you have mentioned it. i dont understand how it works though, do the files get compiled into the application? Do i have to include the files some other way in the final application?

**Comment by BlueAndi** [comment]
The files must be in the SPIFFS filesystem.
If you are using platformio: https://docs.platformio.org/en/latest/platforms/espressif32.html#uploading-files-to-file-system-spiffs
