### ISSUE TITLE
Error compiling return-type false

### ISSUE THREAD

**Issue by valbuz** [me-no-dev/ESPAsyncWebServer#679]
by compiling it ends with the error:

`control reaches end of non-void function [-Werror=return-type]`

what does it mean?

thanks for help
pat

**Comment by solopix** [comment]
let's see the whole function ...

**Comment by valbuz** [comment]
thanks for reply.
yes, i look at it, but for me.....sorry.
i hope get help here.

**Comment by Pablo2048** [comment]
Without seeing exactly the place where the error pops up we are unable to help more than generic response: you forget ```return <something>;``` somewhere in your code, or you have forget to change function return parameter to ```void```.

**Comment by valbuz** [comment]
Hi.
the error is in this function:

`//-------------------------------------------------------------------------------
/*  
 *  ValidateNTP validates the incoming NTP data. 
 *  Stores the incoming data when correct.
 *  Returns false when something is wrong.
 */
//-------------------------------------------------------------------------------
bool ValidateNTP(AsyncWebServerRequest *request){
  int paramsNr = request->params();
  if(paramsNr == 3){
    
    AsyncWebParameter* p = request->getParam(0);
    NTPstring = p->value();

    p = request->getParam(1);
    String NTPData = p->value();
    gmtOffset_hour = NTPData.toFloat();

    p = request->getParam(2);
    NTPData = p->value();
    daylightOffset_hour = NTPData.toFloat();
  }
 else {
    return false;
  } 
}`

the return is given.

**Comment by Pablo2048** [comment]
No, it is not given! Better way is to use ```bool retval = false;```, before the last ```}``` put ```return retval;```, remove ```else{...``` and put ```retval = true;``` after ```dayightOffset_hour = NTPData.toFloat();```.

**Comment by valbuz** [comment]
now, only 1 error

`Error compiling for board ESP32 Dev Module.`

no link of the corresponding code...

i try another Notebook and install all again....here it work's compiling! 
no idea what happens here.....

thanks!
