### ISSUE TITLE
SPIFFS Server with Authentication ESP8266

### ISSUE THREAD

**Issue by wilkerman265** [me-no-dev/ESPAsyncWebServer#693]
Hello to everyone, im new programming with the ESP8266 (NodeMCU) and im working in a page which can read data from different sensors (DS18B20 and DHT22) and serving it to a web server, all works good by so far, but I need a basic auth so not everyone can access to the page. 

I´ve readyng the ESPAsyncWebServer info and it look like it has a command which it will help me, but I cannot make it work, it enters the page without auth. 

My code part which Im trying to put the auth looks like this 
```
// Print ESP8266 Local IP Address
  Serial.println(WiFi.localIP());
  // Route for root / web page
  server.on("/", HTTP_GET, [](AsyncWebServerRequest *request){
    request->send(SPIFFS, "/index.html", String(), false, processor);
  });
```

**Comment by IoTThinks** [comment]
Check the homepage and search for "authentication".

There is a link to authenticate for static file.

**Comment by wilkerman265** [comment]
I solved my problem editing the  WebAuthentication.cpp like described in this post 
[](https://github.com/me-no-dev/ESPAsyncWebServer/issues/667)
