### ISSUE TITLE
Form validation class?

### ISSUE THREAD

**Issue by nardev** [me-no-dev/ESPAsyncWebServer#701]
As there is more and more http rest style of communication, it's pretty logical to have a class for basic validations in C++.

I tried to find something, but no luck so far. It's ok to implement it from time to time, copy/paste some functions but it would be much better maintained and probably safer if there was an opensource class, openly maintained, where bugs could be tracked and fixed.

**Did i miss something like that already?**

For example, i would like to be to easily validate:

- ip address
- url
- integer range
- length
- email
- containing numbers and letters
- number/string from an existing array 

and, maybe someone else have more ideas.

**Any thoughts?**

**Comment by Pablo2048** [comment]
Hi, you can use html5 validators in your html/js code. I think that validating form input at the server side of web application is depreceated - in case of wrong input there is big overhead to bring everything back to the client and highlight errors IMHO.

**Comment by nardev** [comment]
Well, if you don't have web interface but a rest API? Or if you decide to
send json formated config file with a lot of data via POST?

**Comment by Pablo2048** [comment]
If you do so this way, you have to write separate library for doing this. It has nothing to do with the ESPAsyncWebServer library.

**Comment by nardev** [comment]
Well, you are right of course. But where else can i initiate such conversation? Isn't this the perfect place :)

**Comment by Pablo2048** [comment]
:-) I suggest to try esp8266.com , or reddit, or... I did an quick search for "parameter validation library c++" and found this https://www.learncpp.com/cpp-tutorial/185-stream-states-and-input-validation/ so it seems like regex implementation is the best way to do it :D

**Comment by nardev** [comment]
mmm i think that you didn't understand my point... sorry

**Comment by Pablo2048** [comment]
Oh, so sorry...
