### ISSUE TITLE
serveStatic ends in a restart

### ISSUE THREAD

**Issue by Nexus1212** [me-no-dev/ESPAsyncWebServer#703]
Hello,
if the esp32 served files for a website with the function  serveStatic() it ends in a restart.

Could you show me please a exampel, how to serve the files for a website?

My Code (Website needs a index.html, bootstrap and to images files:

```
  server.serveStatic("/index.html", SPIFFS, "/index.html");
  server.serveStatic("/bootstrap.min.css", SPIFFS, "/bootstrap.min.css.gz");
  server.serveStatic("/log_ws.png", SPIFFS, "/log_ws.png");
  server.serveStatic("/gh.png", SPIFFS, "/gh.png");
```

Error Log:

```
[W][AsyncTCP.cpp:949] _poll(): pcb is NULL
[W][AsyncTCP.cpp:949] _poll(): pcb is NULL
E (350611) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (350611) task_wdt:  - async_tcp (CPU 0/1)
E (350611) task_wdt: Tasks currently running:
E (350611) task_wdt: CPU 0: Tmr Svc
E (350611) task_wdt: CPU 1: IDLE1
E (350611) task_wdt: Aborting.
abort() was called at PC 0x400e84b7 on core 0
```

Is there a more simple and stable way?

EDIT:
I find out another way:

```
  server.onNotFound([](AsyncWebServerRequest *request) {
    request->send(SPIFFS, request->url());
  });
```
But sometimes the esp does also a restart after calling the website. I do not why what the problem is.

Log:

```
E (56189) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (56189) task_wdt:  - async_tcp (CPU 0/1)
E (56189) task_wdt: Tasks currently running:
E (56189) task_wdt: CPU 0: Tmr Svc
E (56189) task_wdt: CPU 1: IDLE1
E (56189) task_wdt: Aborting.
abort() was called at PC 0x400e777f on core 0
```

Could be the reason if more than 1 file is requested via SPIFF at the same time the esp becomes a deadlock and the watchdog restart it? 

Best regards
Nexus

**Comment by BlueAndi** [comment]
The task observation via watchdog is active and looks like the task needs to much time.
Try to disable it and pin task to core 1.
```
CONFIG_ASYNC_TCP_RUNNING_CORE 1
CONFIG_ASYNC_TCP_USE_WDT 0
```
This must be configured before you include the headers or e.g. in the platformio.ini
