### ISSUE TITLE
AsyncWebServer over ethernet

### ISSUE THREAD

**Issue by cecco** [me-no-dev/ESPAsyncWebServer#709]
Hi, 
I'm trying to use this library on a ESP32 WROOM with a Wiz W5500 connected via SPI.
If i don't initialize the WiFi part i got a runtime assertion error. I can get it work over ethernet, it's configured (ping working) but no response (tcp port 80 is not open over ethernet address, only over wifi is open).

Can I use this library without WiFi but only via ethernet?

Thank You.

**Comment by ivoh95** [comment]
I believe this is the same issue ive been having. 

https://github.com/espressif/arduino-esp32/issues/3580


I think we are waiting on this
https://github.com/espressif/arduino-esp32/pull/3607#issuecomment-576285941

**Comment by k-zhai** [comment]
Any updates on this?

**Comment by CircuitSetup** [comment]
@cecco or @ivoh95 did you ever figure out a solution to this?

**Comment by CurtRod** [comment]
the same here... Is there any update?

**Comment by ranelolesk** [comment]
Hello all! Does anyone have an update?

**Comment by ArminPP** [comment]
Hello, 
I would also like to ask for a solution ...

**Comment by CurtRod** [comment]
Will this give a chance to get Ethernet working with AsyncWebServer:
https://github.com/espressif/esp-idf/commit/1e905acacfa96c5c98f8f1656f27b3c4317b7c57

**Comment by ZanzyTHEbar** [comment]
Any update on this?

**Comment by liamcharmer** [comment]
@me-no-dev any thing that can be done for ethernet ?
