### ISSUE TITLE
Request callback being called with 4736 bytes of stack used ... even in simple_server.ino example!

### ISSUE THREAD

**Issue by nsbawden** [me-no-dev/ESPAsyncWebServer#716]
Trying to use stack allocated string builders with about 1K of data my memory kept getting corrupted. I found that ESPAsyncWebServer is using up nearly all of the 8266 stack (only 384 bytes left assuming default 5K stack) before it calls the request callback for page building. This is true even in the simple_server.ino example when serving the one line home page.

IMHO this could be the root cause of many of the random crashes reported in other issues.

I am using the simple method below to determine stack use. This severe limitation is leaving very very little room for request callbacks to do anything useful on the stack, and even less if they call out to other functions which also may use the stack.

```
char * stack_start;

void showStack(const char *location = "0") {
  char stack;
  Serial.printf("stack size @%s = %d\n", location, stack_start - &stack);
}

void setup() {
    char stack;
    stack_start = &stack;
...

```

Thanks!

**Comment by ArchWITS** [comment]
@nsbawden I've had similar issues, and was starting to look at this when I found your post.... having taken this further I have found out the following:
1. There are TWO stacks on the ESP ... One is the OS System Stack and the other is the "cont" (don't know what this stands for) Stack which is 4k and used by the user program (variables initiated from setup() or loop())  
2. The thing about the ESPAsyncWebServer and underlying ESPAsyncTCP is that it uses the SYSTEM stack as the callbacks are **called from the OS**, not from within loop() ... so the stack used is the **OS stack**. So your checking algorithm is flawed in that it is taking the start of the stack from the user stack.... and then comparing this to the OS Stack address that is actually used by ESPAsyncWebServer callbacks. Note that this would be true for callbacks from other operating system calls like os_timer functions. 
3. I cannot find anywhere that tells me how much system stack there is, but what I did find out is that, from ESP core 2.4.2 onwards it was decided that the user program stack could hijack 4kb of the OS stack as "its not used as much after a boot" (see https://github.com/esp8266/Arduino/issues/5148#issuecomment-424329183) ... 
So what I think they are doing is reserving 4kb of OS stack at program start time .... this explains why you are seeing stack size of 4.6k ish ... its actually the 4k of user stack and about 600 bytes of OS stack (used by ESPAsyncWebServer) on top of that.
4. What we DONT know is the overall size of the OS stack ... and hence if we are actually blowing this - I am not convinced this is the case.... especially as we appear to be only using 600 bytes.
5. This comment link above also mentions that you can prevent the re-use of the OS stack by calling **disable_extra4k_at_link_time();** This apparently needs to be called from from setup(). This will notionally free up the OS stack to have another 4k.... and the user program stack will be in other memory area usually used for heap instead.
5. During my travels I found quite a lot comments volunteering the opinion that programmers should not be doing any lengthy and complex things in the OS 'space' (i.e. within OS initiated call backs) but instead should use these to record state changes which should then be processed within the normal loop() cycle.... this seems to conflict with the intended design of  ESPAsyncWebServer and ESPAsyncTCP.

Based on all of this I am wondering if I should be using ESPAsyncWebServer! The thing is its darn useful as it has built in SPIFFS and template handling which dont appear to be readily available elsewhere ... and it's Asynchornous!
I think i'll try the disable_extra4k_at_link_time() and see how I get on.
