### ISSUE TITLE
esp8266 web server ( reading the content of web server )

### ISSUE THREAD

**Issue by mostafa-khedrawy** [me-no-dev/ESPAsyncWebServer#72]
I make web server on my esp8266 all i want is to read the content of this web server 
i make my web server with this line of code and send to it some html and javascript 
this line of HTML code i send with wifi module <div id = \"dir\">stop</div> 
now I need to read the content of my web page and see what in this div I am noob with this module :D

**Comment by me-no-dev** [comment]
I do not even understand what you are saying or asking? There is an example in the lib
