### ISSUE TITLE
Compiling fails with build_unflags -fno-rtti to enable dynamic_cast in my code

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [me-no-dev/ESPAsyncWebServer#732]
Hi,

I'm in the need for dynamic_cast in my code now and that is not possible, as platformio keeps adding `-fno-rtti` as a build flag by default.

This disables any runtime type informations and therefore dynamic_cast is not allowed.

When I change that (by adding it as a build_unflags), the webserver stops compiling for no reason:

```
Linking .pio/build/testbench/firmware.elf
.pio/build/testbench/libc29/libESP Async WebServer_ID306.a(WebServer.cpp.o):(.literal._ZNSt8__detail8_ScannerIcEC5EPKcS3_NSt15regex_constants18syntax_option_typeESt6locale[std::__detail::_Scanner<char>::_Scanner(char const*, char const*, std::regex_constants::syntax_option_type, std::locale)]+0x24): undefined reference to `typeinfo for std::ctype<char>'
.pio/build/testbench/libc29/libESP Async WebServer_ID306.a(WebServer.cpp.o):(.literal._ZNSt8__detail8_ScannerIcEC5EPKcS3_NSt15regex_constants18syntax_option_typeESt6locale[std::__detail::_Scanner<char>::_Scanner(char const*, char const*, std::regex_constants::syntax_option_type, std::locale)]+0x28): undefined reference to `typeinfo for std::locale::facet'
collect2: error: ld returned 1 exit status
```

**Comment by philbowles** [comment]
"platformio keeps adding -fno-rtti as a build flag by default." Arduino IDE does the same and they both do it for a very good reason: the code / data pulled in by the RTTI susbsytem are simply too big and unmanageable for a tiny MCU like e.g. ESP8266.

Also, that error is useless without seeing the code that caused it...

Finally,  I am 99.9% convinced there is probably and easier / better / faster way of doing what you are trying to do with the dynamic_cast. Why not post the code / question in stackoverflow as this is a purely C++ question not related to this lib in any way.

**Comment by 0xFEEDC0DE64** [comment]
yeah I created a base class with lots of virtual methods named like:
* X *asX()
* Y *asY()

and they are all implemented with `return nullptr` except for class X, where it returns `this` instead. hacky workaround for dynamic_cast on my microcontroller, works like a charm, so the ticket can be closed.
