### ISSUE TITLE
std::regex broken in the current arduino/gcc4.8

### ISSUE THREAD

**Issue by BbIKTOP** [me-no-dev/ESPAsyncWebServer#744]
Since [std::regex is broken in 4.8](https://community.platformio.org/t/arduino-8266-not-working-with-pio-4-3-1/13033/15), and this lib uses it, it's not possible to use regex for url matching. Is it possible to replace it with some other regex instead? [Here's the first one I've found](https://www.arduinolibraries.info/libraries/regexp) but it's not too difficult to port other. What do you think about it?

**Comment by SBKila** [comment]
Is there a workaround to make ESPAsyncWebServer running well with regex ?
