### ISSUE TITLE
Typo in example to use regex

### ISSUE THREAD

**Issue by gduprey** [me-no-dev/ESPAsyncWebServer#754]
In the main page documentation on enabling the regex processing, the current docs say to add this line to platform.local.txt

compiler.cpp.extra_flags=-DDASYNCWEBSERVER_REGEX

Unfortunatly, it has an extra D in the start.  I didn't pay attention and spent 2 hours trying to find out why regex didn't work (I should have looked closer).  Of course, it should be 

compiler.cpp.extra_flags=-DASYNCWEBSERVER_REGEX

And that does work

**Comment by alnez** [comment]
Thank you very much gduprey. I also lost a lot of time, until I found your help. The code example should be updated.
