### ISSUE TITLE
Cannot convert 'WebRequestMethod' to 'httpd_method_t {aka http_method}' in initialization

### ISSUE THREAD

**Issue by felixgem** [me-no-dev/ESPAsyncWebServer#758]
I have put together two working codes and now the arduino ide does not want to compile them. The following error message is displayed:

sketch_apr24a:122:3: error: cannot convert 'WebRequestMethod' to 'httpd_method_t {aka http_method}' in initialization
exit status 1
cannot convert 'WebRequestMethod' to 'httpd_method_t {aka http_method}' in initialization

**Comment by philbowles** [comment]
How can anyone eanswer this without seeing the code that cause the error?

Also, how is your (unseen) code "working codes" when it doesn't compile? Failing to compile is pretty much the best definiton of *not* working.

Show us the code with the error!

**Comment by dnzunal** [comment]
waiting solution, i have same error
