### ISSUE TITLE
WEBSERVER_H clashes with my local file

### ISSUE THREAD

**Issue by kokangit** [me-no-dev/ESPAsyncWebServer#760]
In ESPAsyncWebServer.h there is this:
`#ifndef WEBSERVER_H` to avoid redefining HTTP methods from ESP8266WebServer.h I guess.
But it should be ESP8266WEBSERVER_H.
Since I have a webserver.h file in my project it clashes with the above.

**Comment by pranjal-joshi** [comment]
I resolved this issue by adding `#define WEBSERVER_H` before including the files
