### ISSUE TITLE
[How to] Use Arduino variables with PROGMEM R"rawliteral(

### ISSUE THREAD

**Issue by pranjal-joshi** [me-no-dev/ESPAsyncWebServer#776]
Hello,

I have a big HTML page which is declared as below:
```
const char saved_ok_html[] PROGMEM = R"rawliteral( 
// some big HTML code here // 
)rawliteral";
```
Here, I want put values of some of the variables declared globally into the webpage while sending.
Something like this
```
R"rawliteral( // Some HTML // )rawliteral + myTemperatureVariable + R"rawliteral( // Some HTML // )rawliteral"
```

**How to do this so that variable data will be added to the webpage in real time?
Keep in mind that I want to keep the HTML page on PROGMEM!**

**Comment by pranjal-joshi** [comment]
@me-no-dev Gentle reminder, I am eagerly waiting for solution.

**Comment by atanisoft** [comment]
@pranjal-joshi Guess you didn't look in the readme: https://github.com/me-no-dev/ESPAsyncWebServer#send-large-webpage-from-progmem-containing-templates

**Comment by pranjal-joshi** [comment]
@atanisoft Thanks for pointing me towards the solution! I got this working with a processor.
Closing this now as the issue is resolved!

**Comment by floriangerbaud** [comment]
@pranjal-joshi then how did you find the issue ?

**Comment by moiHocArduino** [comment]
hi **Pranjal-joshi**, can you please tell me how to do it. thank you very much.
i have read through "readme" but haven't found a way to solve this problem.

**Comment by kalex3000** [comment]
use  %Text% inside  R"rawliteral( 

and outside 
a function
String processor(const String& var){
  if(var == "Text"){  
    String includeText=""; 
   // code to do it 
    return includeText;
  }
return String();
}
