### ISSUE TITLE
OTA with AsyncWebServer

### ISSUE THREAD

**Issue by nvecchio1** [me-no-dev/ESPAsyncWebServer#779]
Hi,
is it possibile update my firmware on esp32 on wifi with this library?
If yes, how can i?
Let me know please.

**Comment by lorol** [comment]
Yes you can. 
See the the official OTA example that comes with Arduino IDE for ESP8266 and ESP32:
File->Examples->ArduinoOTA->BasicOTA

**Comment by nvecchio1** [comment]
Sorry, i want to update my firmware over wifi with http request.
Is it possible with this library?
I saw that with a normal webServer it si possible, but with asyncWebServer?

**Comment by dushyantahuja** [comment]
yes - you can use this https://github.com/ayushsharma82/AsyncElegantOTA

**Comment by markus-fischbacher** [comment]
There is an example available here: https://github.com/me-no-dev/ESPAsyncWebServer#setting-up-the-server

**Comment by dpetican** [comment]
> There is an example available here: https://github.com/me-no-dev/ESPAsyncWebServer#setting-up-the-server

This example only works on the ESP8266.  I've been using it for years on an RSP8266.  The ESP class is not defined on the latest ESP32 Arduino framework and/or IDF.  Which is not helpful.  In fact although ESPAsyncWebserver has been very good for me I've found upgrading my project to the ESP32 has been difficult.  Especially if using the SdFat library to make an SD webserver.  AsyncElegantOTA is a possible solution for me, but the creakiness of this project has me concerned going forward.
