### ISSUE TITLE
method was DELETE so how will hasParam("x", true) ever evaluate to true?

### ISSUE THREAD

**Issue by themindfactory** [me-no-dev/ESPAsyncWebServer#78]
in SPIFFSEditor.cpp I see where the method is equal to DELETE, then it qualifies the paramters and checks for "path", which it used hasParam("path", true), but by using the true your saying it was a POST? so how is a DELETE ever going to be a POST and evaluate true?

Thanks!

RichardS

**Comment by me-no-dev** [comment]
those assumptions come from long time ago when we were writing the ESP8266 regular server. I have not checked specifications to separate which method is what (cuz they are either GET-like or POST-like) since POST can parse GET just fine :) maybe DELETE is GET-like, if that is what you mean
