### ISSUE TITLE
send to client

### ISSUE THREAD

**Issue by jimhoranjr** [me-no-dev/ESPAsyncWebServer#781]
After a server.on request has been responded to, via request->send  is there a way to send more text to the client after other code has been executed. 
Thanks
Jim

**Comment by markus-fischbacher** [comment]
What do you want to do exactly?

There are at least two possibilities:
1. Use Ajax to request further data initiated by the client
2. Implement WebSocket to push data to the client

**Comment by jimhoranjr** [comment]
I saw a library to use a webpage as a serial monitor. My knowledge of  HTML
is fairly rudimentary and I thought I could learn some more trying to replicate it. 
Your options are  what I had run across so far. I just wanted to make sure I wasn't
missing something easier. 
    I've seen sketches using Ajax to automatically update a webpage using both 
the webserver.h library and your library. It appears to me that the differences 
in the sketches are that with the webserver.h library  some code in the loop is 
necessary  to keep rechecking the client. With the ESPAsyncWebServer.h
library this isn't necessary. Am understanding this correctly?

Thanks for your work.
