### ISSUE TITLE
Serving static files with authentication and user defined realm

### ISSUE THREAD

**Issue by mafe** [me-no-dev/ESPAsyncWebServer#788]
Hi,

I asked this some time before, but did not get a reply.
Could you additionally to user,pass add a variable for overriding default realm asyncesp or is there another way to achieve this?

```
server
    .serveStatic("/", SPIFFS, "/www/")
    .setDefaultFile("default.html")
    .setAuthentication("user", "pass", "myrealm");
```

**Comment by flightlead404** [comment]
I'd like to get an answer to this as well.  How do you specify real for digest auth?

**Comment by ockernuts** [comment]
I have the same question, can you support realm here ?
