### ISSUE TITLE
ESPAsyncWebServer as a client.

### ISSUE THREAD

**Issue by gsaikiran29** [me-no-dev/ESPAsyncWebServer#791]
Hello, Need help.
First of all I am new to esp32. I want to send jpg image file to http server. I have own server.
I am using esp32 cam and want to take a snap, store in spiffs and  send to server. Is that possible with this library? is there any example code to do?

**Comment by BlueAndi** [comment]
The lib only supports the server side. But the base is AsyncTcp for exp32, which could be used for implementing a client.
A rough example is here:
https://github.com/me-no-dev/ESPAsyncTCP/issues/18#issuecomment-240777516
