### ISSUE TITLE
(NOT AN ISSUE) General information about ESPAsyncWebServer

### ISSUE THREAD

**Issue by gonzabrusco** [me-no-dev/ESPAsyncWebServer#797]
Hello. I've been using ESPAsyncWebServer and works fantastically. Really great work. 

But now I was wondering If I should make the switch to IDF enviroment (without Arduino Core on top) to have a better control of everything in the background. 

I was wondering, does alternatives similar to ESPAsyncWebServer exists on plain IDF? 

And this next question is not related to the previous one. As I've been reading, Arduino core is running always on 1 core. When I use this library, does it run on one core only too? 

Sorry for the dumb questions. I´m still trying to decide if going IDF to have more control is worth the effort. The arduino libraries are so useful. And this library is an example of this. IDF seems so rough compared. 

Thanks!
Gonzalo

**Comment by lorol** [comment]
:) just use both until you decide. and close the case.
BTW, IDF can have Arduino as component and you can still use its libraries and run .ino sketches - a bit heavy and tricky way.
(and you can close the issue)
