### ISSUE TITLE
ESP32 support for SSL?

### ISSUE THREAD

**Issue by cgreening** [me-no-dev/ESPAsyncWebServer#803]
I've searched through the closed issues and can't work out if this is supported or not.

Trying to build with 

```
#define ASYNC_TCP_SSL_ENABLED true
```

Results in the following error:

```
error: 'AcSSlFileHandler' has not been declared
```

Are there any plans to add support for ESP32? I'm happy to help contribute if someone can point me in the right direction.

**Comment by zekageri** [comment]
It would be awesome. I'am following.

**Comment by BlueAndi** [comment]
See https://github.com/me-no-dev/AsyncTCP/pull/90
