### ISSUE TITLE
C API (for ESP-IDF)

### ISSUE THREAD

**Issue by septatrix** [me-no-dev/ESPAsyncWebServer#809]
I would like the addition of a pure C API to be able to use this library from ESP-IDF. Currently this is only possible when using C++ everywhere which is sometimes not feasible.

**Comment by septatrix** [comment]
@me-no-dev any thoughts?

**Comment by mcmega** [comment]
Yes, I'm +++++.
Cool library and fast!
It would be great to add it to ESP-IDF.

**Comment by septatrix** [comment]
The new ESP-IDF v4.2 (currently in beta) actually has official support for basic websocket functionality. For my use case this will most likely be sufficient but for other people it might still be a nice addition
