### ISSUE TITLE
wss / SSL / secure websockets support

### ISSUE THREAD

**Issue by standarddeviant** [me-no-dev/ESPAsyncWebServer#831]
Does ESPAsyncWebServer support secure web sockets on ESP32?

I have a project that currently uses this library: https://github.com/Links2004/arduinoWebSockets , but that library explicitly does not support secure web sockets. On the README, it states `wss / SSL is not possible`. It seems like there are no ESP32 web socket libraries that support wss on the server side.

**Comment by szape76** [comment]
We like wss / SSL support for esp32 👍
