### ISSUE TITLE
Server requests cause lags in stepper motor motion

### ISSUE THREAD

**Issue by denismiiix** [me-no-dev/ESPAsyncWebServer#833]
If the arduino controls a stepper motor and a client contacts the server (for example, loading a page), micropauses occur in the movement of the motor - the motor works in jerks.

Question.
Can I instruct the server to stand in pause or not process requests while the stepper motor control loop is running?

**Comment by lorol** [comment]
The server is intended to serve ... but you can try with server.end() then server.begin(). But this will not help unless you want the server only while stepper motor is not running at all. Don't think you can get a solution this way ...

**Comment by SnowMB** [comment]
In default setting the webserver and arduino application code are running on the same core (core 1). You can move the webserver to core 0 with this compiler flag:

```
-D CONFIG_ASYNC_TCP_RUNNING_CORE=0
```

But be sure to read about how to share data safely between threads if you do this or you can run into very hard to debug bugs.

**Comment by lorol** [comment]
@SnowMB 
Marc, do you have any example project w/ webserver at core 0 and a shared data to a loop running on core 1?
Appreciated.
