### ISSUE TITLE
cannot open source file \"ESPAsyncTCP.h\" (dependency of \"ESPAsyncWebServer.h\")" on visual studio code

### ISSUE THREAD

**Issue by Mikegyver** [me-no-dev/ESPAsyncWebServer#839]
hi @me-no-dev i'm encountered your library problem on visual studio code. FYI, i'm using arduino extension on vscode.

i have already set the library path for microsoft c/c++ extension, kindly refer the image below

![image](https://user-images.githubusercontent.com/16514357/91658119-fc114280-eaf8-11ea-9724-b96b075da736.png)

even in the c_cpp_properties.json i did include the library path as in below screenshot.

![image](https://user-images.githubusercontent.com/16514357/91658145-37137600-eaf9-11ea-9e46-82c063acb2e6.png)

all others library are working just fine except for your library like ArduinoJson, MQTTClient, AsyncMqttClient, DebounceInput, ssd1306 & ss_oled. hope image below can u clear picture.

![image](https://user-images.githubusercontent.com/16514357/91658193-aee1a080-eaf9-11ea-83a0-9998cbd04673.png)

looking forward for the bug fix regarding this issue. best regards.

**Comment by lorol** [comment]
Please see: https://github.com/me-no-dev/ESPAsyncWebServer/#using-platformio
and post your platformio.ini
