### ISSUE TITLE
Arduino IDE isn't recognizing ESPASyncWebServer

### ISSUE THREAD

**Issue by josetomas** [me-no-dev/ESPAsyncWebServer#848]
### Hardware:
Adafruit feather ESP32 WROOM - 32
IDE: Platformio
Upload Speed: 115200
Computer OS: Windows
Core Installation version: No idea, as it came from fabric
Flash frequency: 40 MHz

### Description:
The Arduino IDE isn't recognizing the ESPAsyncWebServer.h.

### Sketch:  
Same problem with every sketch. 

### Debug Messages:
```
C:\Users\corne\OneDrive\Documentos\Arduino\libraries\ESPAsyncWebServer-master\src/ESPAsyncWebServer.h:33:22: fatal error: AsyncTCP.h: No such file or directory
compilation terminated.
exit status 1
Error compilando para la tarjeta Adafruit ESP32 Feather.
```

**Comment by lorol** [comment]
You said Arduino IDE, then PlatformIO?
These are different setups.
It looks like you don’t have the library installed.
See README.md instruction or Arduino how to add libraries and their dependencies.
