### ISSUE TITLE
authentication when socket connecting

### ISSUE THREAD

**Issue by m2sarmadi** [me-no-dev/ESPAsyncWebServer#858]
hi everybody
I want authentication to be done when the client connecting to the socket.
like this in client side:
`webSocket.sendMessage(payload,username,password);`

and this in server side :
check username and password and if they matched to "user1" and "pass1" , connect client to the socket is done.

**Comment by lorol** [comment]
See in [this fork](https://github.com/lorol/ESPAsyncWebServer) there is one ws authentication solution
