### ISSUE TITLE
esp8266 is reset,when socket messages arrive one after another

### ISSUE THREAD

**Issue by m2sarmadi** [me-no-dev/ESPAsyncWebServer#864]
Hi everyone
I wrote a function that when a socket message arrives, edits are made to a file(in SPIFFS).
If the socket messages arrive at a distance of, say, one second, everything is done correctly, but if they arrive at a short distance of, say, 300 milliseconds, the board resets(ets Jan  8 2013,rst cause:2, boot mode:(3,6)).
where is the problem from?
Is it possible to fill the buffer for socket messages?

**Comment by mark-hahn** [comment]
Are you doing the file edits in the event callback?  This is a no-no.  You should not do lengthy things in callbacks.  Set some kind of flag and do the edits in the main loop.

**Comment by m2sarmadi** [comment]
thanks
