### ISSUE TITLE
serveStatic(): "ERR_CONTENT_LENGTH_MISMATCH 200" and very long request times

### ISSUE THREAD

**Issue by Tymec** [me-no-dev/ESPAsyncWebServer#865]
Everything works fine with this library, except for two things:
- the first is that each GET/POST request takes from 2 to 10 seconds to respond and sometimes even times out, which I'm not sure why.
![image](https://user-images.githubusercontent.com/2727109/96386904-c0146880-119e-11eb-9d3b-eccee678e555.png)
![image](https://user-images.githubusercontent.com/2727109/96386913-d7535600-119e-11eb-835c-f1fb4b33e0bf.png)

- the one I'm more concerned about is that when serving a 9KB html file to a client, the data just fails and stops after sending a few hundred bytes to the client.

This is the line I use to serve the html file: `this->server->serveStatic("/", SPIFFS, "/").setDefaultFile("index.html").setCacheControl("max-age=xxx");`
![image](https://user-images.githubusercontent.com/2727109/96386838-2a78d900-119e-11eb-9646-272af982bf57.png)
![image](https://user-images.githubusercontent.com/2727109/96386840-31075080-119e-11eb-8c77-68f9db2f4f2c.png)

The actual file `index.html` is supposed to be 9KB and it works perfectly fine if I try to print it out to the Serial Output.
The css and js files are served from a CDN, so the only file that has to be served would be the html file I'd assume.

**Comment by guestisp** [comment]
Same issue here. any idea?
