### ISSUE TITLE
LinkedList Destructor

### ISSUE THREAD

**Issue by yngndrw** [me-no-dev/ESPAsyncWebServer#866]
My C++ is a little rusty, but shouldn't the [LinkedList destructor](https://github.com/me-no-dev/ESPAsyncWebServer/blob/master/src/StringArray.h#L65) call the [free() method](https://github.com/me-no-dev/ESPAsyncWebServer/blob/master/src/StringArray.h#L161-L171) as it has allocated memory using new?

Also as an aside, it would be nice if:
1) It was defined within its own file rather than being bundled with `StringArray`
2) `#include <functional>` was included so that it could be used on its own
3) The `onRemove` constructor parameter defaulted to `nullptr` as it's optional

**Comment by ul-gh** [comment]
Hi, I also stumbled on the file name, and the rest seems to be to the point.

This is worth a pull-request, if you ask me. 

I would also change the free() method name to make it obvious that it is not the standard library function.

Also in this direction, the PR from #747 could be considered, too (but please don't use "stringarray" as a designation for a linked list namespace. Maybe more appropriate: "async_containers" if the file is named accordingly.
