### ISSUE TITLE
[Question] How to upload large files (i.e. 500kB) to SPIFFS?

### ISSUE THREAD

**Issue by FrankBoesing** [me-no-dev/ESPAsyncWebServer#868]
Hi, 
is there an example (or mybe some code elsewhere)?

Any hint appreciated.

**Comment by lorol** [comment]
https://github.com/me-no-dev/ESPAsyncWebServer/tree/master/examples/ESP_AsyncFSBrowser
Once you build and flash FW and data to esp, go with your browser to http://<esp device IP>/edit and use the web editor to upload / download.
I tested on esp8266 and esp32, both were able to upload download 500kb file.
Note, my repo and examples are modified and I used LittleFS not SPIFFS for test, if the master / default ones here don't work for you, please report.

**Comment by FrankBoesing** [comment]
Thank you!
