### ISSUE TITLE
How to increase the size of the payload onRequestBody?

### ISSUE THREAD

**Issue by Bomexxuk** [me-no-dev/ESPAsyncWebServer#873]
I was trying to send a long json string through, but I have soon realized that it's not possible because of the size of the payload (data) is uint8_t and I need at least uint16_t to send such a string. Because of the size, the request splits into two. I have tried to make a string from the two bodies. Sometimes it works sometimes it doesn't, it puts strange marks between the string eg(⸮ @⸮D⸮?⸮⸮⸮) Is there a way to increase the size of the payload?

Any suggestions?
  
      void handleUrlSetImpact(){
     
      server.onRequestBody([](AsyncWebServerRequest * request, uint8_t *data, size_t len, size_t index, size_t total) {
    
      Serial.println("Running");
   
      if (request->url() == "/impact") {
      
      Serial.println("Size of data is:\t"); Serial.println(len);
      Serial.println("Contains data of:\t"); Serial.println((const char*)data);
    
      String item; 
      item += (const char*)data;

      if(item != NULL && item.charAt(0) == '{'){
        variable = item;
        Serial.println("DATA IS if:\t" + variable);
        
      }else if(item != NULL && item.charAt(0) != '{'){
        
        variable += item;
        Serial.println("DATA IS else if:\t" + variable);
        setImpact(variable, request);
      }     
    }}); }

**Comment by BlueAndi** [comment]
BTW you expect that data is terminated, but it is not, thats why the data type is uint8_t and not char. This may cause the strange characters.
