### ISSUE TITLE
'class UpdaterClass' has no member named 'runAsync'

### ISSUE THREAD

**Issue by druizoses** [me-no-dev/ESPAsyncWebServer#88]
Hi,
I'm trying to compile the Setting up the server example (https://github.com/me-no-dev/ESPAsyncWebServer/#setting-up-the-server) to update my firmware using OTA.

When I compile the example, Arduino IDE throws this error:
_'class UpdaterClass' has no member named 'runAsync'_

Could anyone help me to fix this error?

Thanks in advance,
David.

UPDATE: Ok, My mistake. The problem was that I was trying to compile with an oldest version of Arduino/ESP8266. 
Then, I updated the library to the version 2.3 (using the Board Manager of Arduino IDE) and now it works.

**Comment by virat92** [comment]
Hi, Thank you me-no-dev for your wonderful libraries.
i am using esp32 devkitc  
have an issue in firmware update 
there is no runAsync member in Update class , is there any other way to do it ?


Thank you 
Virat
