### ISSUE TITLE
[Question] Post route callback: routeHandler({...}).then({...}) 

### ISSUE THREAD

**Issue by hitech95** [me-no-dev/ESPAsyncWebServer#881]
I have a situation where I have to reboot the ESP via a rest API.
IF I reboot the board the ressponse from the server is never delivered and the request goes to timeout.
What I would like to do is:
Process the request return a response to the browser, and then reboot the board by calling a callback function.

**Comment by zekageri** [comment]
You could just set a flag, return the response and if that flag is 1 handle it in the loop.
