### ISSUE TITLE
How to terminate file upload if the file is too large

### ISSUE THREAD

**Issue by ismal** [me-no-dev/ESPAsyncWebServer#897]
I am successfully using ESP32 and file upload in a way
`server.on("/home", HTTP_POST, [](AsyncWebServerRequest *request) { request->send(200);}, handleUpload);
`
with 'handleUpload' which can also be found here on github and everything works nicely.

```
void handleUpload(AsyncWebServerRequest *request, String filename, size_t index, uint8_t *data, size_t len, bool final)
{
  if (!index)
  {
    Serial.printf("Uploading: %-32s ", filename.c_str());
    request->_tempFile = SPIFFS.open("/" + filename, "w"); 
  }
  if(len) {
    request->_tempFile.write(data, len);
  }
  if(final){
    Serial.printf("%u B\n", index + len);
    request->_tempFile.close();
  }
}
```

The problem is with uploading large files, that do not fit the available free space on ESP32 flash. 
**How to properly terminate the upload if I detect that the file is not going to fit?**  
This must be something that one could easily find online, and of interest to any implementation that has a file upload capability, but I have not managed to find it. 

I can find the filesize that is going to be uploaded and the size of the empty space like this
```
size_t size = request->contentLength();
int tBytes = SPIFFS.totalBytes(); 
int uBytes = SPIFFS.usedBytes();
size_t freespace = tBytes - uBytes;
```

but how to get out of that 'handleUpload;' which runs anyway multiple times for all the small chunks of data that are passed from the request. 

Thanks!

**Comment by Fimiksator** [comment]
I think this is not resolved yet. Any new features ?
