### ISSUE TITLE
Serve files with .gz extension to IOS ( Iphone )

### ISSUE THREAD

**Issue by zekageri** [me-no-dev/ESPAsyncWebServer#898]
**I'm serving my files like this:**

```
server.on("/index.html", HTTP_GET, [](AsyncWebServerRequest *request) {
    AsyncWebServerResponse* response = request->beginResponse(LITTLEFS, "/index.html.gz", "text/html");
    response->addHeader("Content-Encoding", "gzip");
    request->send(response);
});
```

_It is working an all operating systems except Iphones. Iphone tries to download the index.html instead of serving it.
If i delete the .gz from the file name it is working properly, but i don't want to delete it in every file alwys if i modify and zip some of them._ 
**Any workaround on this?**

**Comment by ismal** [comment]
The workaround is to rename those .gz into something that IOS will not understand. So I am serving .js.gz as .jsgz and it works well exactly in a way that you described above. In your case you can try to use "LITTLEFS, "/index.htmlgz",

**Comment by zekageri** [comment]
Yeah i'm currently serving the files without the .gz in the filename. 
When i zipping the files i always delete the " .gz " from the end of the file names (for safari). 
But it is really frustrating.

**Comment by lorol** [comment]
Unfortunately, you have to cope with this, 
Depends of how you prepare the gzipped files, you can use a script / batch file etc to compress then rename it before upload as you wish.

**Comment by zekageri** [comment]
Oh nice. I didn't thought about a batch script. I will investigate it.
Thank you!

**Comment by ismal** [comment]
another simple script for renaming can look like this:
for f in *.html.gz; do     mv -- "$f" "${f%.html.gz}.html"; done

**Comment by zekageri** [comment]
Thank you all! I will close this issue and open it on some Apple forum!
