### ISSUE TITLE
no matching function for call to 'esp8266webserver: :ESP8266WebServerTemp1ate<WiFiServer>: :on(const char [19], HTTPMethod, setup(): :_lambdal) ' candidates are:

### ISSUE THREAD

**Issue by MisiekDP** [me-no-dev/ESPAsyncWebServer#902]
Hey, I have a problem with this library. Today I wanted to program an project with getting URL with parameters but all the time I got an errors. I use a PlatformioIO too.
There are errors:

![image](https://user-images.githubusercontent.com/22171619/102283507-d76b9a00-3f32-11eb-8983-024753bab7cc.png)

![image](https://user-images.githubusercontent.com/22171619/102283555-f407d200-3f32-11eb-8bae-8a0b45708094.png)

![image](https://user-images.githubusercontent.com/22171619/102283609-0b46bf80-3f33-11eb-91f7-0134e961c318.png)

![image](https://user-images.githubusercontent.com/22171619/102283773-56f96900-3f33-11eb-979a-afc6a282d347.png)

```
#include <Arduino.h>

#include <ESP8266WiFi.h>
#include <ESP8266HTTPClient.h>
#include <ESP8266WebServer.h>
#include <Adafruit_Sensor.h>
#include <DHT.h>
#include <ESPAsyncTCP.h>
#include <ESP8266WiFi.h>
// #include <AsyncTCP.h>
#include <ESPAsyncWebServer.h>

// Pins GPIO
int ledRed = 0;
int ledYellow = 2;
int buttonRed = 5;
int buttonYellow = 16;
DHT dht(4, DHT11);

// WiFi config
IPAddress ip(10, 6, 0, 120);        // Static IP adress
IPAddress gateway(10, 6, 0, 5);     // Gateway
IPAddress subnet(255, 255, 0, 0);   // IP maska
ESP8266WebServer server(80);        // Server port

...

void setup() {
  Serial.begin(9600);

 ...

  // Starting the server and assigning actions
  server.on("/", websiteLoad);
  server.on("/w1t", websiteLed1Toggle);
  server.on("/w2t", websiteLed2Toggle);
  server.on("/sendResponseIfESP8266Works", sendResponseIfESP8266Works);
  server.on("/sendData", sendData);
  server.on("/led1toggle", led1toggle);
  server.on("/led2toggle", led2toggle);
  // server.on("/seek_bar_led2_pwm", seekBarLed2PWM);
  // respond to GET requests on URL /heap


  server.on("/seek_bar_led2_pwm", HTTP_GET, [](AsyncWebServerRequest *request) {
    AsyncWebParameter* p = request->getParam(0);
    Serial.print("Param name: ");
    Serial.println(p->name());
    Serial.print("Param value: ");
    Serial.println(p->value());
    Serial.println("------");

    // server.send(200);
    request->send(200, "text/plain", "message received");
  });

  server.begin();
}

void loop() {
  // Waiting for client connecting
  server.handleClient();
...
}
```

**Comment by egrekov** [comment]
@MisiekDP `#define WEBSERVER_H`, will solve the compilation problem, but if you use constants like `HTTP_POST`, `HTTP_PUT`, 
then they will not work properly. [issue904](https://github.com/me-no-dev/ESPAsyncWebServer/issues/904)
```c++
#define WEBSERVER_H
#include "ESPAsyncWebServer.h"
```

**Comment by MisiekDP** [comment]
> @MisiekDP `#define WEBSERVER_H`, will solve the compilation problem, but if you use constants like `HTTP_POST`, `HTTP_PUT`,
> then they will not work properly. [issue904](https://github.com/me-no-dev/ESPAsyncWebServer/issues/904)
> 
> ```c++
> #define WEBSERVER_H
> #include "ESPAsyncWebServer.h"
> ```

Ok, thanks for reply :D But now I can't test it :/

**Comment by wiseda51** [comment]
Just starting to use AsyncWebServer and  browsing through issues... You are crossing classes between old ESP8266WebServer (synchronous server run in loop) and AsyncWebServer (new ESP32/ESP8266 async webserver).  So get rid of ESP8266WebServer.h and change your object to AsyncWebServer server(80);.
