### ISSUE TITLE
I can't make Captive Portal Work Properly

### ISSUE THREAD

**Issue by Nathan-ma** [me-no-dev/ESPAsyncWebServer#907]
I was following the Captive Portal example and it works great!

But I can only access what is inside the handler, all the methods based on server.on gets inaccessible.

![image](https://user-images.githubusercontent.com/11060905/102690956-b8e1f900-41e7-11eb-8cf3-def61327c80b.png)

How can I work with Handlers and captive portal and yet have all the server.on functions working?

**Comment by BlueAndi** [comment]
Register the CaptiveRequestHandler after registering stuff with on() and try again.

**Comment by Nathan-ma** [comment]
Thanks, will try

**Comment by Nathan-ma** [comment]
> Register the CaptiveRequestHandler after registering stuff with on() and try again.

BlueAndi! 

it is working now, Thanks!

All I need to figure out is how to redirect to the index page since request->redirect("/") doesn't seem to be working, but i can figure this out!
