### ISSUE TITLE
Streaming video from ESP32-CAM via websocket

### ISSUE THREAD

**Issue by nlac** [me-no-dev/ESPAsyncWebServer#908]
Hello,
first i say a big thank you for this awesome library, absolutely must have. 
What i'm recently curious about, is the optimal way to broadcast a jpeg stream via websocket connection from ESP32-CAM.

Currently I'm doing the below what is basically working.
After opening a ws connection,
1. from the browser, sending a triggering message to ESP32
2. on that triggering message, ESP32 takes a photo and sends it as a binary to the browser
3. the browser receives it, displays it and after a short timeout, goto 1.

I'm aware and tried that [gist](https://gist.github.com/me-no-dev/d34fba51a8f059ac559bf62002e61aa3) manages jpeg stream fine via http request, but what is the (or is there any) proper way streaming to a client via websocket connection?

**Comment by hyansuper** [comment]
Hi, have you found your solution?
