### ISSUE TITLE
I cannot use process function

### ISSUE THREAD

**Issue by oguzkaganyaglioglu** [me-no-dev/ESPAsyncWebServer#911]
When I compile the code I get this error. What am I doing wrong? How can I fix it?

25:67 is the bold word "**this**"

> src\ServerManager.cpp: In lambda function:
src\ServerManager.cpp:25:67: error: 'this' was not captured for this lambda function
         request->send(LittleFS, "/status.html", String(), false, [**this**](const String &var) -> String { return statusProcessor(var); });

*** [.pio\build\nodemcuv2\src\ServerManager.cpp.o] Error 1

in .cpp file
```
void MyServerManager::init()
{
    if (!LittleFS.begin())
    {
        Serial.println("Something went wrong while begin LittleFS");
    }

    server->on("/", HTTP_GET, [](AsyncWebServerRequest *request) {
        request->send(LittleFS, "/status.html", String(), false, [this](const String &var) -> String { return statusProcessor(var); });
    });
    server->begin();
}

String MyServerManager::statusProcessor(const String &var)
{
    if (var == "NETWORK_NAME")
    {
        return WiFi.SSID();
    }
    else if (var == "SIGNAL_STRENGTH")
    {
        return String(WiFi.RSSI()) + " dBm";
    }

    return String();
}
```

in .h file

```
#ifndef ServerManager_h
#define ServerManager_h
#include <Arduino.h>
#include <ESPAsyncWebServer.h>

class MyServerManager
{
private:
    AsyncWebServer *server = NULL;
    AsyncWebSocket *ws = NULL;
    void notifyClients(const String *msg);
    void handleWebSocketMessage(void *arg, uint8_t *data, size_t len);
    void onEvent(AsyncWebSocket *server, AsyncWebSocketClient *client, AwsEventType type, void *arg, uint8_t *data, size_t len);
    void initWebSocket();
    String statusProcessor(const String &var);

public:
    MyServerManager(uint16_t port, const String url);
    ~MyServerManager();

    void init();
};

#endif
```

**Comment by BlueAndi** [comment]
Why do yoou use a lambda function form the statusProcessor, instead of using it directly in the on()? There is btw your problem,  because you try to capture this in the 2nd lambda, but it does not exists there.

**Comment by oguzkaganyaglioglu** [comment]
Because when I use it like that I get another error.

```
    server->on("/", HTTP_GET, [](AsyncWebServerRequest *request) {
        request->send(LittleFS, "/status.html", String(), false, statusProcessor);
    });
```

Error: 

> src\ServerManager.cpp:25:81: error: no matching function for call to 'AsyncWebServerRequest::send(fs::FS&, const char [13], String, bool, <unresolved overloaded function type>)'

**Comment by oguzkaganyaglioglu** [comment]
When I add this to the outer lambda function it worked. So is there another way to do it without seccond lambda?

this is worked:
```
    server->on("/", HTTP_GET, [this](AsyncWebServerRequest *request) {
        request->send(LittleFS, "/status.html", String(), false, [this](const String &var) -> String { return statusProcessor(var); });
    });
```

**Comment by BlueAndi** [comment]
Now I see, the send method expects a function, not a method. That is why without the 2nd lambda, it won't work. But your last proposal do.
