### ISSUE TITLE
Example Asyncwebserver and javascript fetch

### ISSUE THREAD

**Issue by plofski** [me-no-dev/ESPAsyncWebServer#913]
Hello,
I was using the asyncwebserver for my projects, and I don't find a working example of javascript fetching a json from the board, `request->send(200, "application/json",data)` doesn't work, the code runs but in javascript i recieve an empty array, any suggestions?

**Comment by lbussy** [comment]
I use this and it works.  You'll need to check your returned object on the browser side:
```
console.log('DEBUG: ', obj);
```
(Note the comma, without which this will not work.)
