### ISSUE TITLE
AsyncFileResponse adds problematic Content-Disposition Header value for Safari Browser

### ISSUE THREAD

**Issue by pkerspe** [me-no-dev/ESPAsyncWebServer#926]
When trying to send a file from SPIFFS to the browser with gzip encoding that is supposed to be used inline, the 
`AsyncFileResponse::AsyncFileResponse(FS &fs, const String& path, const String& contentType, bool download, AwsTemplateProcessor callback): AsyncAbstractResponse(callback)` function automatically adds a Content-Disposition header with the value 'inline; filename="..."'. Besides that I did not find any documentation that filename should be used in combination with inline (other than with the "attachment" value) it also causes serious problems in Safari Browser on the Mac. The mac will not properly load any gzip compressed js file if the "filename" is added to the header in combination with "inline" and will fail to interpret the compressed js code.

I do not see a reason why the filnemae needs to be added to a Content-Dispisiton header when it is set a inline.

When replacing line https://github.com/me-no-dev/ESPAsyncWebServer/blob/f6fff3f91ebf45b91ca4cff2460d2febd61f1e27/src/WebResponses.cpp#L536
with 
`    snprintf(buf, sizeof (buf), "inline");`(for ease of calirty, obviously you can directly call the addheader() function only with the "inline" value)
It works also in Safari browser.

Is there any browser or use case where the filename is needed in addition to the "inline" value?

**Comment by vojty** [comment]
I had the same issue. I don't think that `AsyncFileResponse` should add `Content-Disposition` header by default.
Anyway I ended up with custom Response class, which clears the headers:
```
#include "ESPAsyncWebServer.h"

class FileResponse : public AsyncFileResponse {
  using File = fs::File;
  using FS = fs::FS;

 public:
  FileResponse(FS& fs, const String& path, const String& contentType = String(), bool download = false,
               AwsTemplateProcessor callback = nullptr)
      : AsyncFileResponse(fs, path, contentType, download, callback) {
    this->_headers.free();
  };
};

```
