### ISSUE TITLE
Will the AsyncJsonResponse get deleted upon request->send()

### ISSUE THREAD

**Issue by timkoers** [me-no-dev/ESPAsyncWebServer#929]
Following the code in https://github.com/me-no-dev/ESPAsyncWebServer#arduinojson-advanced-response
Will the response get deleted once the request->send(response) returns or do I need to do that manually?

Also, will the response get deleted when you use the object inside a lambda function?

**Comment by bboynton97** [comment]
Check [here](https://github.com/me-no-dev/ESPAsyncWebServer#request-life-cycle) in the docs and look at the last bullet point in Request Life Cycle
