### ISSUE TITLE
How to wait?

### ISSUE THREAD

**Issue by kwalkerk** [me-no-dev/ESPAsyncWebServer#938]
I know I can't use the delay function in the callbacks.  But I have a relay I want to turn on for a certain length of time and then turn back off.

Cant this be done?  If so how?

**Comment by Pablo2048** [comment]
I see 3 options you have:
Option 1 - use global (volatile) flag. Set this flag in async callback, and clear it (and do your delay) in the main loop
Option 2 - use lets say "command queue" - put specific command into the queue in callback, read from queue and handle commands in loop()
Option 3 - turn relay on in callback and set Ticker() object to interrupt later. Point the Ticker handler to function which turns off the relay
Better (and most universal) is IMO Option 2...
