### ISSUE TITLE
SPIFFS,LITTLEFS multi-thread safe issue with SemaphoreHandle

### ISSUE THREAD

**Issue by johnnytolengo** [me-no-dev/ESPAsyncWebServer#945]
I have to protect the filesystem access to avoid crashes while I use both processors on ESP32.

I am looking the way to fire a callback function after the` request->send(LITTLEFS, LOG_FILE, WEB_APPTEXT)` is already sent.
Without success tried :

```
_asyc_webserver->on("/get_logs", API_HTTP, [this] (AsyncWebServerRequest * request) {
 
 fs_lock(); //SET LOCK  protection FS semaphore

 AsyncWebServerResponse *response = request->beginResponse(LITTLEFS, LOG_FILE, WEB_APPTEXT );

fs_unlock(); //try to UNLOCK FS semaphore after response ready but doesn't work because AsyncWebServerResponse runs async

request->send(response);

fs_unlock(); // try again but the same as before this is called before request->send()

});
```

As you see I just have to call `fs_unlock()` AFTER the request is sent, but I have not clue how to do that :(

any idea?

**Comment by BlueAndi** [comment]
You can register a callback onDisconnect(), see:

https://github.com/BlueAndi/esp-rgb-led-matrix/blob/9b5f07662359878393f222522179aa310db57be0/src/Web/CaptivePortalHandler.cpp#L115-L117

And lock before you start sending, unlock in the callback.
