### ISSUE TITLE
POST requests ends up with 404 while using web browser

### ISSUE THREAD

**Issue by bustedbunny** [me-no-dev/ESPAsyncWebServer#962]
![Screenshot_1](https://user-images.githubusercontent.com/30902981/112197758-79c7a780-8c1d-11eb-834f-cfe9868cf2b4.png)
 Every time I'm trying to make POST request from browser (chrome), I get 404 error.
 But, using any other HTTP Client (I use Nightingale) and sending simple POST request everything works and I get 200 response, and basically everything works fine.

``` 
server.on("/post", HTTP_POST, [](AsyncWebServerRequest * request) {
    request->send(200, "text/plain", "Post route");
  });
```

That's the code I'm using on web page. (I also tried pure JS without jQuery, but it's all the same -> 404)
```
$(document).ready(function(){
  $("#console").keyup(function(event){
    if (event.which == 13) {
        $.post('/post', $("#console").val() + '\n', function() {
              $("#console").val("");
              });
              }
    });
});
```

**Comment by 7doctor7** [comment]
I think that you have a CORS issue.
Try to add default response Headers to your server before init

```
  DefaultHeaders::Instance().addHeader("Access-Control-Allow-Origin", "*");
  DefaultHeaders::Instance().addHeader("Access-Control-Allow-Headers", "*");
```
