### ISSUE TITLE
How to serve huge generated content

### ISSUE THREAD

**Issue by copych** [me-no-dev/ESPAsyncWebServer#966]
I have a functions in my project that generate graphic content. Several MBs, but in case of ESP we can call it huge )
What is the right way to feed such content. Intuitively I'd use chunked response, but I don't quite get how to wrap this. When I tried response->print(), it only feeds a certain amount of kB and then reboots :-/
Please, advise.

**Comment by lorol** [comment]
Try websockets

**Comment by zekageri** [comment]
I would suggest you to write it to a file and download that file client side with ajax.

**Comment by copych** [comment]
> I would suggest you to write it to a file and download that file client side with ajax.

This is what I do, but don't like it, cause I spend precious FS bytes while I could do that just sending content generated on the fly.
