### ISSUE TITLE
Max character in array json to send to web server

### ISSUE THREAD

**Issue by Cutiino** [me-no-dev/ESPAsyncWebServer#968]
Hello, I am triying to send a json array to local web server with esp32. Until now, I can send a array json with a max of 10.000 characters. Once over this character, the esp32 is reset.

This is my code in the part that I send the array json

  server.on("/cosecha", HTTP_GET, [](AsyncWebServerRequest * request) {
    char response[10000]; 
    JsonCosecha.printTo(response, JsonCosecha.measureLength() + 1);
    request->send(200, "application/json", response);
    //request->send(200, "text/plain", JsonCosecha);
  });

I aprecciate any help

**Comment by zekageri** [comment]
Your client side language is Javascript?

**Comment by Cutiino** [comment]
No, I have been checking with a notebook connected to ESP32 network. Then I put the URL 192.168.4.1 in the browser and in web page appear the array json.

**Comment by zekageri** [comment]
But are you in controll of the client's script?

**Comment by Cutiino** [comment]
Yes, the client's script is in Javascript.  Finally, I used WebSockets for fixing this issue.
