### ISSUE TITLE
Add ESPAsyncWebServer to the Arduino Library Manager

### ISSUE THREAD

**Issue by dok-net** [me-no-dev/ESPAsyncWebServer#971]
Subsequently to issue https://github.com/me-no-dev/ESPAsyncTCP/issues/168,
the library.properties file should probably be updated to list the exclusively supported architectures,
plus the automatic dependency on ESPAsyncTCP should be declared as well.
Instructions for the publishing process are [here](https://support.arduino.cc/hc/en-us/articles/360012175419-How-can-I-add-my-library-to-the-Library-Manager-)

**Comment by zekageri** [comment]
Currently this webserver has a lot of issues. Ofc this is a really really amazing piece of art but dozens of users reporting crashes by websockets, events and http requests. Do you think it would be wise if it will be in the library manager?

**Comment by dok-net** [comment]
It's an open issue nevertheless.
But for the time being, you are right, and it would take a release before announcing it to the library manager support.

**Comment by s-light** [comment]
> It's an open issue nevertheless. But for the time being, you are right, and it would take a release before announcing it to the library manager support.

do you think this will happen this year?

iam a little bit skeptical of what the status of this project is.....
(there are 59 outstanding PullRequests - my feeling is that it is a little bit stale..)

**Comment by per1234** [comment]
There is a new incarnation of the request at https://github.com/me-no-dev/ESPAsyncWebServer/issues/1433
