### ISSUE TITLE
ESPAsyncWebServer-master\WebServer.cpp.o: No such file or directory

### ISSUE THREAD

**Issue by podaen** [me-no-dev/ESPAsyncWebServer#982]
Hardware:
Board: ESP-WROOM-32
Core Installation/update date: 01/MAY/2021
IDE name: Visual Micro

Description:
I am using the example. I am able to find all libary's accept one and recieve this message 

> Error linking for board DOIT ESP32 DEVKIT V1
> xtensa-esp32-elf-gcc*: error: ESPAsyncWebServer-master\WebServer.cpp.o: No such file or directory
> Debug build failed for project 'File server'

h file that's found it at Arduino\libraries\ESP8266WiFi\src -> contains WiFiServer.cpp & WiFiServer.h

When I look at "Arduino\libraries\ESPAsyncWebServer-master\src" I only can find WebServer.cpp, I cannot find WebServer.h and others are missing. I thought that the .h files also is needed in the same directory or am I wrong, it certain he look for the ccp but I can't find any direction to it in the code.

**Comment by Gishanx** [comment]
I'm having the exact same issue in Visual Studio using the Visual Micro Extension.
Anyone got an idea what I'm doing wrong? Or is this a bug in the library?

**Hardware**
- Board: HUZZA32 (Adafruit ESP32 Feather)
- Core: 2.0.0
- IDE: Visual Micro

**Software**
- using latest version of ESPAsyncWebserver (1.2.3)
- installed all dependencies mentioned in the readme (AsyncTCP)
- even tried installing WebServer (error msg points to it) but didn't make a difference

**Error message**
```
Error linking for board Adafruit ESP32 Feather
Build failed for project 'myproject'
xtensa-esp32-elf-g++*: error: WebServer\WebServer.cpp.o: No such file or directory
```
