### ISSUE TITLE
prevent gzip in response

### ISSUE THREAD

**Issue by marchingband** [me-no-dev/ESPAsyncWebServer#998]
I am using Axios to fetch data from my ESP32, and I want to use the Axios.onProgress() callback to display the transfer progress in my UI.
In Google Chrome, any gzipped response always returns "total:0" for the file size, so I cannot display the progress.
I would like to prevent AsyncWebserver from gzipping my "text/plain" file.
Is this possible?

**Comment by zekageri** [comment]
Async webserver does not gzipping anything
